### ISSUE TITLE
Bad translation 'Casa'

### ISSUE THREAD

**Issue by plindry** [eventum/eventum#100]
I'm using Eventum with spanish as Language. (Spanish from Spain/Europe).
There is a terrible translation that is 'Casa' from the English word Case or issue. I think it is a direct wrong translation. I would prefer 'Casos' or 'Caso', or much better 'Estadísticas' that is the Word used in the 2.2 versión.
'Casa' means home or house not issue, the translation is complete mistaken.

It is the Word between my assignments and reports in the upper part of the page when you logon.

**Comment by glensc** [comment]
did you even search how to contribute translation?!

https://github.com/eventum/eventum/wiki/System-Advanced:-Localization
https://github.com/eventum/eventum/wiki/System-Advanced:-Localization:-Old-Style

**Comment by plindry** [comment]
Thanks glensc i didn't realize that here the only language used is English.--) Is good to know it.

I didn't search anything (as i said in previous post i'm new here https://github.com/eventum/eventum/issues/91)
I joined to the Lanchpad Translation platform. I translate some words and i'll contribute in the future.
