### ISSUE TITLE
Password for pop account are plain text in the database

### ISSUE THREAD

**Issue by plindry** [eventum/eventum#102]
Like user passwords i consider the email passwords must to be hashed in the database.
Consider this like an enhacement.

**Comment by cpinfold** [comment]
It would be nice to be able to do that.

The POP server requires an unhashed password (being an older standard).  If
you are using Google as an example, you can setup an application specific
password for Eventum though.

Craig

**Comment by glensc** [comment]
Eventum needs plain text to authenticate to POP3/IMAP, as it acts like mail client like your mail agent. You should be using TLS to enhance security.

**Comment by plindry** [comment]
I think you wan't understandme. Yes of course you can use TLS. 

Eventum as you when you talk with the mail server need plain text but not the database and the database administrator needs this kinds of information as plain text saved . Eventum can get the hash, decript and use the plain text with TLS if you want.

**Comment by glensc** [comment]
you're speaking of symmetric encryption, not one way hashing then! passwords are hashed in database, which is one way only! https://en.wikipedia.org/wiki/Cryptographic_hash_function

**Comment by plindry** [comment]
Yes symetric encryption, I Know is not a very secure way but it's better than plain text.
I supposed that the passwords are saved with symetric encription. In my mind i translated hashed passwords as the result of a symetric encryption in two ways. (my fault)

**Comment by glensc** [comment]
no, passwords are hashed

https://github.com/eventum/eventum/releases/tag/v3.0.4
https://github.com/eventum/eventum/pull/77

**Comment by plindry** [comment]
Nice job

**Comment by glensc** [comment]
#134 is now merged

**Comment by glensc** [comment]
btw, do you actually use this feature now?
