### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by cohuser** [eventum/eventum#1027]
**Version(s) affected**: 2.1.1

**PHP Version**: x.y.z

**Browser and Version**: Browser x.y.z

**Description**  

In the attached file section where is the uploaded attachment file stored in the application ? 
**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by glensc** [comment]
hello hello.

**Comment by cohuser** [comment]
We are using Eventum 2.1.1. In the attached file section where is the uploaded attachment file stored in the application ?
