### ISSUE TITLE
Error in the first pie chart in main.php

### ISSUE THREAD

**Issue by plindry** [eventum/eventum#103]
I'm getting an error when i access to:
https://github.com/eventum/eventum/blob/v3.0.6/htdocs/main.php

in the first pie chart. The error message: "SetRGBColor(): Color Green is not valid." The rest of pie charts are ok and i see the Green colors in the rest of pie charts.

Someone is getting this error or know why? 
(I'll debug glesnc..)

**Comment by glensc** [comment]
need line number where error comes from, or screenshot.

but have you defined custom colors for your issue statuses and used `green` there instead of rgb hex?

**Comment by glensc** [comment]
btw, i suggest installing [xdebug](http://pecl.php.net/package/xdebug) pecl extension and enabling [display_errors](http://php.net/display_errors) in your dev (**not production**) installation. this way you can get better error reporting including automatic stack traces.

**Comment by plindry** [comment]
Yes glensc you are right, i change the word 'green' in the color of state for the hex color. 
I never thought that this is wrong becuase you can see the Green color in the issue.
Appreciated

**Comment by glensc** [comment]
strack trace still necessary to address this properly!

**Comment by plindry** [comment]
I'll put the stack trace on monday

**Comment by plindry** [comment]
The problem is not the word Green, if you put Green the pie chart is correct. My problem was i miss a figure in an hex color in other state.

 If you forgot this figure an is not a valid hex color you get the error from 
https://github.com/eventum/eventum/blob/v3.0.6/lib/eventum/PlotHelper.php#L128

that

Is a method that calls a class in ../vendor/Phplot.php/phplot/phplot/phplot.php and there  is the message that i get "SetRGBColor (): #ffddf is not a valid"
Perhaps it would be an enhancement check in some way the color in the field when you fill the hex color as backgroundcolor of field or changing the error message i get "SetRGBColor (): #ffddf is not a valid. Please review if your colours are correct" But i suppose phplot.php is another external development

**Comment by glensc** [comment]
included the missing screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/199095/11219103/32998cea-8d61-11e5-86c2-b13f1aa85fac.png)

**Comment by glensc** [comment]
commited fix to prevent save of invalid values.

@balsdorf can you fix  that the `validateForm` javascript function is called from `manage/statuses.php?cat=edit&id=1`, currently seems the method is not invoked.

**Comment by balsdorf** [comment]
Done.

On Tue, Nov 17, 2015 at 11:42 AM, Elan Ruusamäe <notifications@github.com>
wrote:

> commited fix to prevent save of invalid values.
>
> @balsdorf <https://github.com/balsdorf> can you fix that the validateForm
> javascript function is called from manage/statuses.php?cat=edit&id=1,
> currently seems the method is not invoked.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eventum/eventum/issues/103#issuecomment-157448932>.
>



-- 
Bryan Alsdorf
MariaDB Corporation | http://mariadb.com
