### ISSUE TITLE
project dependencies, run the following commands

### ISSUE THREAD

**Issue by khanpeach** [eventum/eventum#1055]
You must set up the project dependencies, run the following commands: $ curl -sS https://getcomposer.org/installer | php $ php composer.phar install

im getting the above error on all the hosting servers and shared hosting servers when i tried to access first time eventum, tried to run the same command and still no success. any solution for this?

**Comment by glensc** [comment]
1. you have not described how you installed this, exact steps to reproduce your situation! version info? why have you ignored issue template?
2. fix issue body use markdown code block to paste code
3. have you followed install instructions?
4. if you ran the command, maybe it errored out, show your details!
