### ISSUE TITLE
Attachment corruption

### ISSUE THREAD

**Issue by m39yur1p7** [eventum/eventum#1068]
**Version(s) affected**: 3.10.3

**PHP Version**: 7.3.27

**Browser and Version**: Chrome 90.0.4430.72

**Description**  
Excel (binary) attachment is corrupted in emails sent to notification list or downloaded from the link in view_email.php.

**How to reproduce**  
Reply to an issue with an Excel (binary) attachment and users on notification list will receive the file corrupted. Also when trying to download the same attachment from the link in the corresponding email shown by view_email.php (referring to get_attachment.php) the file is also corrupted. These two corrupted files are not identical that is both are different from the original but not in the same way - eg. files' sizes differ.

**Additional Context**  
The attachment of the same reply can be downloaded OK (healthy) via the link under Attached Files in view.php (referring to download.php?cat=attachment).

**Comment by glensc** [comment]
Without deep looking into this, are you using mbstring overload?
- https://www.php.net/manual/en/mbstring.overload.php

**Comment by glensc** [comment]
Binary diff shows already diffs in first few bytes:

```diff
--- Test_original_OK.xlsx.xxd    2021-04-20 10:32:44.000000000 +0300
+++ Test_sent2notlist_CORRUPTED.xlsx.xxd    2021-04-20 10:32:49.000000000 +0300
@@ -1,39 +1,39 @@
-00000000: 504b 0304 1400 0600 0800 0000 2100 a453  PK..........!..S
-00000010: c5cf 4e01 0000 0804 0000 1300 0802 5b43  ..N...........[C
+00000000: 504b 0304 1480 0680 0880 8080 2180 a453  PK..........!..S
+00000010: c5cf 4e01 8080 0804 8080 1380 0802 5b43  ..N...........[C
 00000020: 6f6e 7465 6e74 5f54 7970 6573 5d2e 786d  ontent_Types].xm
```

**Comment by glensc** [comment]
This must be 0:

```
php -r 'var_dump(ini_get("mbstring.func_overload"));'
string(1) "0"
```

**Comment by glensc** [comment]
Most of the changes are 0x00 -> 0x80, this does smell like ASCII being translated to UTF-8

```
00000006 00 80
00000008 00 80
0000000A 00 80
0000000B 00 80
0000000C 00 80
0000000E 00 80
00000015 00 80
```

- https://superuser.com/a/125408/679361

**Comment by m39yur1p7** [comment]
> This must be 0:
> 
> ```
> php -r 'var_dump(ini_get("mbstring.func_overload"));'
> string(1) "0"
> ```

It is 0.

IMHO the three different results, one correct and two altered, suggests app (not system) level (processing) difference.

**Comment by glensc** [comment]
what attachment storage are you using?

**Comment by m39yur1p7** [comment]
> what attachment storage are you using?

how can I look it up?

**Comment by glensc** [comment]
Made test:

1. send email via web interface
2. download email from the sent email in web interface

```
[~/Downloads] ➔ md5sum Test_original_OK*
fa05d3c388f778eee674e0b5cc2945c3  Test_original_OK.xlsx
43dbd6d1ebf60d68b9dd040115ec293d  Test_original_OK (1).xlsx

[~/Downloads] ➔ LC_ALL=C la Test_original_OK*
-rw-r--r-- 1 glen staff 8828 Apr 20 17:46 Test_original_OK.xlsx
-rw-r--r-- 1 glen staff 8803 Apr 20 17:52 Test_original_OK (1).xlsx
[~/Downloads] ➔
```

indeed, the checksum differs, and the file became smaller. wut?!

**Comment by glensc** [comment]
So, my impression is that attaching mail to email corrupts it. The email attachment downloaded from view email is extracted from email.

**Comment by glensc** [comment]
@m39yur1p7 do yoy have info when this was okay? maybe it's easier to bisect that way the problem.

**Comment by m39yur1p7** [comment]
Last working was 3.1.2 that I upgraded to 3.10.2 without testing the intermediary releases.

**Comment by m39yur1p7** [comment]
> -rw-r--r-- 1 glen staff 8828 Apr 20 17:46 Test_original_OK.xlsx
> -rw-r--r-- 1 glen staff 8803 Apr 20 17:52 Test_original_OK (1).xlsx
> 
> indeed, the checksum differs, and the file became smaller. wut?!
> but, my corruption here is different than yours!

Sizes at least are the same for me: 8828 bytes for the original and 8803 for the downloaded one via the view_email.php link. Do you mean "different than yours" bytewise? Or maybe just overlooked?

**Comment by glensc** [comment]
What you mean overlooked? What does it even mean? 

If you say your test sizes remain the same but then copied two different numbers? Huh? Copied wrong numbers? 

I compared the binary diffs, and my difference did not show changes in file header like yours. Looks like I forgot to post the diff.

Should also make a test, is the corruption varying each time, or it's always the same. I.e do the same test multiple times.

**Comment by m39yur1p7** [comment]
> If you say your test sizes remain the same but then copied two different numbers? Huh? Copied wrong numbers?
> 

The file "Test_original_OK.xlsx" with size 8828 bytes is the untouched one that I used to attach to a relpy email in the issue using send.php.

The last one "Test_view.php_OK.xlsx" is the file downloaded using the link in the issue body (view.php) after it got attached to the issue when the above reply email got processed; this is healthy and has the same size as the first, 8828 bytes.

The second file "Test_sent2notlist_CORRUPTED.xlsx" is the one notification list members receive in their mail client as attachment when they receive the above mentioned reply. This has size 8876 bytes and is corrupted.

Then the third file "Test_view_email.php_CORRUPTED.xlsx" is the issue attachment downloaded from Eventum, but this time accessing it following the email link in the issue body and then using the attachment link displayed by view_email.php. This has size 8803, corrupt, and that size is exactly the number I saw in your reply:

```
[~/Downloads] ➔ LC_ALL=C la Test_original_OK*
-rw-r--r-- 1 glen staff 8828 Apr 20 17:46 Test_original_OK.xlsx
-rw-r--r-- 1 glen staff 8803 Apr 20 17:52 Test_original_OK (1).xlsx
```

Because of the size match I thought that you reproduced the same corruption and did not understand your comment:

> but, my corruption here is different than yours!

Unless the content (cheksum) of my third file and your "Test_original_OK (1).xlsx" file also differs.

Let me know if I misinterpret the context.

> Should also make a test, is the corruption varying each time, or it's always the same. I.e do the same test multiple times.

I'll do repetitive tests.

**Comment by glensc** [comment]
The attachment created by laminas mail (formerly zend mail) some why adds the attachment as 8bit:

![image](https://user-images.githubusercontent.com/199095/115576318-112b2380-a2cc-11eb-82e9-cf186dc8a5b4.png)

this may be the culprit. as i think attachng binary data with 8bit encoding is prone to errors, as the email is typically word wrapped too. so if it manages not to get corrupted in `support_email_body` it will definitely get broken over smtp and smtp servers

**Comment by glensc** [comment]
you can find email body id's for issue 22 like this:

```
mysql> select sup_iss_id, seb_sup_id, sup_date, sup_subject from support_email_body, support_email where sup_iss_id=22 and sup_id=seb_sup_id;
+------------+------------+---------------------+-------------+
| sup_iss_id | seb_sup_id | sup_date            | sup_subject |
+------------+------------+---------------------+-------------+
|         22 |      22635 | 2021-04-21 15:01:52 | a           |
|         22 |      22636 | 2021-04-21 15:10:57 | a           |
+------------+------------+---------------------+-------------+
2 rows in set (0.00 sec)
```

and then do something lke this:

```
mysql> select seb_full_email from support_email_body where seb_sup_id=22636\G
[snip]
1 row in set (0.00 sec)
```

i should be base64 encoded, not binary.

i'm looking latest releases from laminas, can't find anthihng that could be relevant:
- https://github.com/laminas/laminas-mail/releases
- https://github.com/laminas/laminas-mime/releases

but then 3.1.2  is very old, i think at that time we used zend components, but i don't believe the bug is that old, somebody else would have reported it!

**Comment by glensc** [comment]
I've tested with v3.8.0, problem is still there!

It's difficult to git checkout older ersions as some composer vendor packages no longer exist. should be still possible to use release tarballs.

**Comment by glensc** [comment]
made a fix in https://github.com/eventum/eventum/pull/1076, but the area it modifies is basically never changed, and so are the used libraries not changed that much.

Switch to zend\mail was done in 3.4.0 (2018-04-22), perhaps this never worked with zend\mail component.

**Comment by m39yur1p7** [comment]
> what attachment storage are you using?

Is this what you asked:
```
    'attachments' => [
        'default_adapter' => 'pdo',
        'adapters' => [],
    ],
```
There was one long email-migration step along the upgrades from 3.1 to 3.10 somewhen, was that a storage change?

**Comment by glensc** [comment]
No, storage doesn't get changed automatically. you need to actually invoke the migration command if you want to move existing uploads.
