### ISSUE TITLE
how to have a separate sequence issue id in eventum version 2.2

### ISSUE THREAD

**Issue by khanpeach** [eventum/eventum#1077]
Hi,

Im trying to have separate issue id for each projects in eventum version 2.2, im not a developer. any suggestions?

**Comment by glensc** [comment]
1. version 2.2 is 12 years old, nobody supports that old version or that old php. I can create a branch if you want to submit pull requests against that version
2. please elaborate on why. what problem is that solving? why is that needed?

**Comment by khanpeach** [comment]
Hi @glensc 
Thanks for the prompt response, yes its a legacy version and we were using it for sometime.what we are trying to achieve is each project we are trying to have a separate sequence of issue ID starting with eg: "B1000" instead if "1" and the second project to have "C1000" instead of having the next number in the issue id order. 

currently across all the project we get unique number eg: project A got issue id "1" and project B starts with issue id "2"

can we have own auto issue id sequence for each project?

**Comment by glensc** [comment]
It's difficult to implement even to latest version, as issue_id is everywhere in relations.

**Comment by khanpeach** [comment]
Understood, Thanks @glensc

**Comment by glensc** [comment]
Hit the close issue button then?

**Comment by khanpeach** [comment]
is there any possibility to start from 1000 issue id instead of 1?

**Comment by glensc** [comment]
the id is produced by auto-increment mysql table feature, so insert into `issue` table entry with `iss_id=1000` or alter the table and change `AUTO_INCREMENT` value. but it doesn't solve your problem, all projects continue having issue ids from there, starting from 1001

that's why I asked, what is the problem you are trying to solve. you only explained what you want.

**Comment by khanpeach** [comment]
What i did now installed a separate eventum with only 1 project and there wont be any more project in that eventum instance. So if i do the change as u said it will resolve my issue, let me try it and come back to you. Thanks

**Comment by khanpeach** [comment]
Thanks the solution you provided is solving one of my issue - Thanks
