### ISSUE TITLE
Invalid header value detected exception thrown in case of non-7bit(?) attachment filename

### ISSUE THREAD

**Issue by m39yur1p7** [eventum/eventum#1078]
**Version(s) affected**: 3.10.3-4a611eed8

**PHP Version**: 7.3.27

**Browser and Version**: Chrome 90.0.4430.72

**Description**
vendor/laminas/laminas-mail/src/Header/HeaderValue.php throws 'Invalid header value detected' exception when file with non-7bit(?) name is attached in send.php

**How To Reproduce**
Reply to an issue either with the issue's overview 'Reply' button or any associated email using 'reply to this email' function attaching a file with filename eg. 'Testá.xls' and press 'Send Email'

**Comment by m39yur1p7** [comment]
[Testá.xlsx](https://github.com/eventum/eventum/files/6356004/Testa.xlsx)

**Comment by glensc** [comment]
Reply as note or reply as email? please correct issue details.

**Comment by m39yur1p7** [comment]
> Reply as note or reply as email? please correct issue details.

I did. AFAIK the 'reply as note' does not accept attachments, does it?

**Comment by glensc** [comment]
@m39yur1p7 just pointed out the issue to be specific and exact. will look into it later.

**Comment by glensc** [comment]
Your example file is not saved as `Testá.xlsx`, but `Testa.xlsx`.

**Comment by glensc** [comment]
Looks. like laminas\mime doesn't do any encoding to filename:
- https://github.com/laminas/laminas-mime/blob/2.8.0/src/Part.php#L148-L157
- https://github.com/laminas/laminas-mime/blob/2.8.0/src/Part.php#L447-L449

these are called from MalBuilder, which also doesn't do any encode;
- https://github.com/eventum/eventum/blob/v3.10.4/src/Mail/MailBuilder.php#L57-L70

also their documentation is rather minimal:
- https://docs.laminas.dev/laminas-mime/

**Comment by glensc** [comment]
created bugreport for now:
- https://github.com/laminas/laminas-mime/issues/16

**Comment by glensc** [comment]
shit, laminas/mime is in security-only maintenance mode:
- https://github.com/laminas/laminas-mime/issues/16#issuecomment-825188239

they suggest to migrate to https://symfony.com/doc/current/components/mime.html

**Comment by glensc** [comment]
I found a shortcut, the filename could be just QP encoded:

```
--=_a6956f59ae8a75d69a2b181056eebc04
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet; charset=UTF-8
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="=?UTF-8?Q?Test=C3=A1.xlsx?="
```
