### ISSUE TITLE
Workflow: shouldAutoAddToNotificationList: Return false

### ISSUE THREAD

**Issue by poing** [eventum/eventum#113]
I have been unable to prevent 3.0.6 from adding addresses to the NL.

```php
// ./config/workflow/class.foo.php
class Foo_Workflow_Backend extends Abstract_Workflow_Backend
{
    public function shouldAutoAddToNotificationList($prj_id)
    {
        return false;
    }
}
```

I also tried the following:

```php
// ./lib/eventum/workflow/class.abstract_workflow_backend.php
class Abstract_Workflow_Backend
{
    public function shouldAutoAddToNotificationList($prj_id)
    {
        return false;
    }
}
```
Even trying to overide the function in class.workflow.php, but it didn't help.  
```php
// ./lib/eventum/class.workflow.php
public static function shouldAutoAddToNotificationList($prj_id)
   {
      if (!self::hasWorkflowIntegration($prj_id)) {
         return false;
      }
      $backend = self::_getBackend($prj_id);
      
      // return $backend->shouldAutoAddToNotificationList($prj_id);
      return false;
}
```
But the address is still being added to the NL.
My best guess, it's in [class.support.php](https://github.com/eventum/eventum/blob/v3.0.6/lib/eventum/class.support.php#L2203)

```php
// Eventum 2.3.6
if ((@$_POST['add_unknown'] == 'yes') || (Workflow::shouldAutoAddToNotificationList(Issue::getProjectID($_POST['issue_id'])))) {
...
}

// Eventum 3.0.6
if (($add_unknown || Workflow::shouldAutoAddToNotificationList($prj_id)) && $issue_id) {
...
}
```

**Comment by glensc** [comment]
always use git tag when linking to line of code, not master.
as "master" branch is moving target, the line may not match at the time i go and try to look at it. 

i've corrected this issue now myself.

**Comment by glensc** [comment]
is the `$issue_id` empty in your condition? as there seems to be a slight logic change:

old code:
```php
        // only send a direct email if the user doesn't want to add the Cc'ed people to the notification list
        if ($add_unknown || Workflow::shouldAutoAddToNotificationList($prj_id)) {
            if ($issue_id) {
                        // add the recipients to the notification list of the associated issue
            }
        } else {
        }
```

new code:
```php
        // only send a direct email if the user doesn't want to add the Cc'ed people to the notification list
        if (($add_unknown || Workflow::shouldAutoAddToNotificationList($prj_id)) && $issue_id) {
            // add the recipients to the notification list of the associated issue
        } else {
        }
```

i wonder, is that the case, or is the problem that value of `$add_unknown` is incorrect.

**Comment by poing** [comment]
The issue is created by mail, ```Auto-Creation of Issues = Enabled```

So ```$issue_id``` shouldn't be empty.

**Comment by glensc** [comment]
can you `git bisect` to exact commit that breaks it?

**Comment by poing** [comment]
@glensc seems I misinterpreted the symptom to the cause.  Workflow ```shouldAutoAddToNotificationList``` does NOT seem to work in 2.3.6 either.

The symptom I was chasing down, external users would receive BOTH ```Issue Created``` && ```New Issue``` notifications.  ```New Issue``` notifications should only be sent to Eventum Users.  **I thought**, this was caused because the user being added to the notification list.  

So I tried to remove the user from the notification list, without success.  It's still a bug in the workflow, but I'm not sure when it was working (or where it broke).

**Comment by glensc** [comment]
i think @balsdorf found the same bug when he worked on #123 testing.

**Comment by balsdorf** [comment]
@glensc The bug I found was relating to the ambiguity of the UI when sending emails.  I don't believe this is the root cause of this (#113) though.

@poing I'm trying to track down the cause of this. Can you share screenshots of your mail queue and notification list please?

**Comment by balsdorf** [comment]
@poing No need for those screenshots, I've tracked it down.

#124 Fixes this by not sending the new issue email to the sender of the original email. Please reopen this if this doesn't solve the problem for you
