### ISSUE TITLE
eventum 2.2 to 3

### ISSUE THREAD

**Issue by khanpeach** [eventum/eventum#1144]
Hi All,

Currently im running eventum version 2.2 on an Ubuntu OS and planning to upgrade the eventum to the latest version which was recently released.

Please advise how can I do this? is there any article? will it break my existing setup or data?

**Comment by glensc** [comment]
- https://github.com/eventum/eventum/blob/v3.10.5/docs/wiki/Upgrading.md

**Comment by khanpeach** [comment]
Thank you
