### ISSUE TITLE
2.2 -> 3.10 upgrade, RHEL6 -> RHEL8  config.php empty on source

### ISSUE THREAD

**Issue by ScottDunkley** [eventum/eventum#1157]
**Version(s) affected**: x.y.z

Source RHEL6, MySQL5.7, PHP 5.3, Eventum 2.2

target RHEL8, MYSQL8, PHP7.3, Eventum 3.10

**PHP Version**: x.y.z
source 5.3
target 7.3
**Browser and Version**: Browser x.y.z

**Description**  
Attempted up[grade straight to 3.10 and realised error of my ways.

So have now downloaded 2.3, 2.4, 3.0, 3.1, 3.2 etc

copied DB from source system to Target

copied over var and config directories

2.2 -> 2.3 php upgrade/update-database.php  returned to prompt no errors or any messages
2.3 -> 2.4 copiec ocnifg files and ran php upgrade/update-database.php, retruns error:

[php_admin@hrmnxpd5153 Relay]$ php upgrade/update-database.php
ERROR: Can't get config.php in '/app/Relay/config'
Did you forgot to copy config from old install? Is file readable?

chmod 777 the file but then realised it 0 bytes and has nothing in it.

Checked source system and that is also 0 bytes but up and running fine.

Any way to dump config in to that file?

**How to reproduce**  
attempt upgrade using [php_admin@hrmnxpd5153 Relay]$ php upgrade/update-database.php
ERROR: Can't get config.php in '/app/Relay/config'
Did you forgot to copy config from old install? Is file readable?

**Possible Solution**  
need a way to dump the source system config in to config.php file and then update for new server/db details?

**Additional context**

**Comment by glensc** [comment]
Follow the upgrade steps:
- https://github.com/eventum/eventum/blob/v3.10.5/docs/wiki/Upgrading.md

Do not skip any versions unless you know what you are doing.

Restart the upgrade process from backup and retry if you messed up.

Also, be sure your steps are recorded in detail enough for a third party to understand what you were doing. And fix typos if you want any help.

**Comment by ScottDunkley** [comment]
Hi,

thanks for reply.

i got this sorted, config file was in different location.  Have now found it but have new issue, will raise separate thread.
