### ISSUE TITLE
email address used for notifications

### ISSUE THREAD

**Issue by cmiller1111** [eventum/eventum#119]
Hey Eventum dudes, thanks for the help with the email issues in upgrading to 3.0.5.  Email is working awesomely now, however I'd like to change the email address that Eventum is sending notifications from.  I went into https://ourserver.com/eventum/manage/general.php and changed the email address there for all of our projects, however when I make a new issues I'm still getting notifications from the old email address.  Where do I need to make this change?

**Comment by poing** [comment]
I updated the wiki with a better explanation of outgoing mail.  If it doesn't answer your question, please let me know.

https://github.com/eventum/eventum/wiki/System-Admin:-Email-integration#outgoing-mail

**Comment by cmiller1111** [comment]
Perfect, everything I needed was there.  Thank you!
