### ISSUE TITLE
Check boxes: Edit Notification List

### ISSUE THREAD

**Issue by cmiller1111** [eventum/eventum#121]
Hi again, not sure if there is anything that can be done about this, but when I'm in an issue and I click Edit Notification List a window pops up allowing me to add emails to be notified for various things; I'm wondering if the "Get a Notification When" checkboxes can be prechecked when I open this window?  Is there somewhere in the settings that those boxes can default as checked so that when adding several emails to an issue I don't have to click 4 boxes every time?

**Comment by cmiller1111** [comment]
To add an update to this I have already changed the default settings in https://ourserver.com/eventum/manage/general.php under "Default Options for Notifications" and all the boxes there are checked. However, in an issue if I go to Edit Notification List and add an email address, none of those boxes are checked.  If I leave the boxes unchecked the added email will get 0 notifications....this kind of seems like a bug?

**Comment by glensc** [comment]
there's bug, which is i just fixed in dev branch!

#120 - f7213479ce6372661bf8a59347a993f0efcf622e

**Comment by cmiller1111** [comment]
oh great thanks!  so should I just wait for the 3.0.7 update or should I go make changes in the notification.php file?

**Comment by glensc** [comment]
up to you, there is no ETA when 3.0.7 be released.

i will keep this ticket open until #120 is merged to master.

**Comment by cmiller1111** [comment]
thanks, what's the dir of notification.php?

**Comment by cmiller1111** [comment]
Found it, thanks for the help.  That fixed it!

**Comment by glensc** [comment]
closing #120 is merged in
