### ISSUE TITLE
Responsible disclosure policy

### ISSUE THREAD

**Issue by zidingz** [eventum/eventum#1241]
Hey there!

I belong to an open source security research community, and a member (@noobpk) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by noobpk** [comment]
@glensc Did you receive an email about my report from the huntr?

**Comment by glensc** [comment]
@noobpk yes, but been busy with other things in life, so haven't opened it. do you have a patch ready to resolve the problems?

**Comment by noobpk** [comment]
> @noobpk yes, but been busy with other things in life, so haven't opened it. do you have a patch ready to resolve the problems?

@glensc ah oke. I will submit the patch in the next few days and hope you will confirm it. ^^
