### ISSUE TITLE
fresh installation. cannot access administration tab

### ISSUE THREAD

**Issue by shiyamk** [eventum/eventum#1261]
Hi,

I have installed eventum 3.10.8 with PHP 7.3 and Apache2.

I can access all tabs except for Administration tab. when i check log i get the following;

[Fri Nov 12 13:53:28.399476 2021] [php7:error] [pid 3364] [client 112.134.208.182:48895] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /var/www/html/eventum/src/ServiceContainer.php:89\nStack trace:\n#0 /var/www/html/eventum/src/Auth/Adapter/LdapAdapter.php(71): Eventum\\ServiceContainer::getLogger('auth')\n#1 /var/www/html/eventum/src/Controller/Manage/ManageBaseController.php(49): Eventum\\Auth\\Adapter\\LdapAdapter->__construct()\n#2 /var/www/html/eventum/src/Controller/Manage/ManageBaseController.php(33): Eventum\\Controller\\Manage\\ManageBaseController->hasLdapAuth()\n#3 /var/www/html/eventum/htdocs/manage/projects.php(16): Eventum\\Controller\\Manage\\ManageBaseController->__construct()\n#4 {main}\n  thrown in /var/www/html/eventum/src/ServiceContainer.php on line 89, referer: http://example.com/new.php

i have the following extensions installed and enabled
[PHP Modules]
calendar
Core
ctype
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache

please help.

**Comment by glensc** [comment]
Duplicate: https://github.com/eventum/eventum/issues/1174

Use workaround from there.
