### ISSUE TITLE
Bad link in Eventum organization

### ISSUE THREAD

**Issue by Neustradamus** [eventum/eventum#1431]
Hello the @eventum team,

I have seen a bad website link in website section here: https://github.com/eventum.

Can you replace by the good link?

**Comment by glensc** [comment]
unclear what you mean, what link?

**Comment by Neustradamus** [comment]
@glensc: Sorry for the delay: On https://github.com/eventum/eventum, I see:
Eventum Issue tracking system
 https://github.com/eventum/eventum

https://github.com/eventum/eventum on https://github.com/eventum/eventum...
