### ISSUE TITLE
/manage/projects.php - error

### ISSUE THREAD

**Issue by JuergenUniVie** [eventum/eventum#1435]
**Version(s) affected**: 3.10.11
**PHP Version**: 7.4.30
**Description** :

Lots of errors are displayed when you open Administration (new installation):

```
Fatal error: Uncaught Error: Call to a member function get() on null in /srv/www/eventum-3.10.11/src/ServiceContainer.php:112
Stack trace: 
#0 /srv/www/eventum-3.10.11/src/Auth/Adapter/LdapAdapter.php(71): Eventum\ServiceContainer::getLogger('auth') 
#1 /srv/www/eventum-3.10.11/src/Controller/Manage/ManageBaseController.php(49): Eventum\Auth\Adapter\LdapAdapter->__construct() 
#2 /srv/www/eventum-3.10.11/src/Controller/Manage/ManageBaseController.php(33): Eventum\Controller\Manage\ManageBaseController->hasLdapAuth() 
#3 /srv/www/eventum-3.10.11/htdocs/manage/projects.php(16): Eventum\Controller\Manage\ManageBaseController->__construct() 
#4 {main} thrown in /srv/www/eventum-3.10.11/src/ServiceContainer.php on line 112
```

Thanks for your help!

**Comment by vladsf** [comment]
Try workaround from #1174

**Comment by JuergenUniVie** [comment]
> Try workaround from #1174

doesn't work - allready tried - error changes to:

Fatal error: Uncaught Error: Call to a member function get() on null in /srv/www/eventum-3.10.11/src/ServiceContainer.php:94 Stack trace: #0 /srv/www/eventum-3.10.11/src/Auth/Adapter/LdapAdapter.php(71): Eventum\ServiceContainer::getLogger('auth') #1 /srv/www/eventum-3.10.11/src/Controller/Manage/ManageBaseController.php(49): Eventum\Auth\Adapter\LdapAdapter->__construct() #2 /srv/www/eventum-3.10.11/src/Controller/Manage/ManageBaseController.php(33): Eventum\Controller\Manage\ManageBaseController->hasLdapAuth() #3 /srv/www/eventum-3.10.11/htdocs/manage/projects.php(16): Eventum\Controller\Manage\ManageBaseController->__construct() #4 {main} thrown in /srv/www/eventum-3.10.11/src/ServiceContainer.php on line 94

**Comment by inguin** [comment]
This fixes it for me:

```
diff --git a/src/ServiceContainer.php b/src/ServiceContainer.php
index 421682620..21473018d 100644
--- a/src/ServiceContainer.php
+++ b/src/ServiceContainer.php
@@ -107,7 +107,7 @@ class ServiceContainer
     public static function getLogger($name = null): LoggerInterface
     {
         if ($name !== null) {
-            $container = static::getKernel()->getContainer();
+            $container = static::getKernel()->ensureBooted()->getContainer();
             /** @var LoggerInterface $logger */
             $logger = $container->get("monolog.logger.$name");
```

**Comment by vladsf** [comment]
LGTM.

Can you provide a pull request?
