### ISSUE TITLE
Sending emails inside an issue

### ISSUE THREAD

**Issue by plindry** [eventum/eventum#147]
Hy, i'm running 3.0.6 version.
Yes Glensc I know i've to update. 

Only a question, when you send an email inside an issue the mail don't reach the notification list members. Is not a problem of the mail server because the other mails of eventum (when you create or you are assigned) reach you. I download the email sent in the original format and it seems the RCPT TO is not fullfill with the emails from the people in the notification list. I check the database tables eventum_mail_queue and eventum_mail_queue_log and i can't see the mails.

Do you have the similar behavior?

**Comment by glensc** [comment]
i am having trouble understanding what are you talking about. so i'll ignore it and leave others to respond.

**Comment by plindry** [comment]
Inside an issue you have the option for sending emails. In this part

**Comment by poing** [comment]
Are you talking about, only a single recipient shown in the ```eventum_mail_queue``` record?  There will be **one** for each recipient.  But multiple records for the message.

**Comment by poing** [comment]
Is ``` Emails are Received or Sent``` checked for each member in the notification list?  Should show **emails** listed under ```Actions```

**Comment by glensc** [comment]
there's also page to view mail queue for specific issue: `mail_queue.php?iss_id=#`

**Comment by plindry** [comment]
Thanks glensc.

You're right poing. 

I desactivated in the configuration project page for all becuase sometimes the email addrees is a mail list and was horrible for notifications for all people. I dindn't know this behaviour.

I really appreciated.
Thanks
