### ISSUE TITLE
"List Issues" display only one column for issues in new projects

### ISSUE THREAD

**Issue by eriklille** [eventum/eventum#153]
When creating a new project and adding issues, the "List Issues" only shows the "All" column with the checkbox. But not problem for issues in Default project. (Running a fresh install of v3.0.10).

**Comment by balsdorf** [comment]
The solution to this is to go to "Manage Projects" -> "Edit Columns to Display".  This should be handled automatically though.

**Comment by balsdorf** [comment]
Good news, this actually was fixed by #151 and will be included in the next release.
