### ISSUE TITLE
Progress Bar for % Complete

### ISSUE THREAD

**Issue by phavel** [eventum/eventum#162]
If you have interest, I offer this improvements. 

Patch is created on version 3.0.11. I am beginner in git, I can't work with Fork and Pull requests.

[Eventum_ProgressBar.zip](https://github.com/eventum/eventum/files/214910/Eventum_ProgressBar.zip)

**Comment by glensc** [comment]
`htdocs/components/jquery-ui/ui/progressbar-full.js` where this file comes from?

**Comment by glensc** [comment]
nevermind. found a way to use existing ui files! thanks!

**Comment by glensc** [comment]
integrated in f58857fd, thanks! looks awesome!

**Comment by phavel** [comment]
Thanks.

**Comment by glensc** [comment]
huh. the white background progressbar is confusing. we have issue status also colored white, so brief looking at issue makes fee that issue is "done". i'm thinking of moving it to second column, or remove the white i progressbar.
