### ISSUE TITLE
buttons do not work in listing view

### ISSUE THREAD

**Issue by slay123** [eventum/eventum#171]
All clickable nonlinks in issue view do not work. Well, except header button Search.

In header:
* Clear filters

In Search Results:
* All
* |<
* <<
* Go
* >>
* >|
* Set
* Hide Closed Issues

In Bulk Update Tool:
* Bulk Update
* Reset

Click so much if you want, nothing happens. Nothing in console.

**Comment by glensc** [comment]
original problem caused with changes from #170
