### ISSUE TITLE
Eventum git scm plugin does not detect issues on lines 2 and later of commit message

### ISSUE THREAD

**Issue by rjroos** [eventum/eventum#172]
Hi, I was playing around with the git hook in eventum/scm against a 3.1 eventum installation. This is really nice guys, great work!

The problem I encountered is that my commit message most of the time contain the issue id on line number 3, and this code only returns the first line of the commit message:

function git_scm_ping($rev, $refname)
{
    $commit_msg = git_commit_msg($rev);
    $issues = match_issues($commit_msg);
    ...

git_commit_msg runs git_format with an explicit comment that it should return 1 line which breaks issue matching. This hack solves that problem, but this breaks the comment:

diff --git a/eventum-git-hook.php b/eventum-git-hook.php
index c71b800..456e301 100755
--- a/eventum-git-hook.php
+++ b/eventum-git-hook.php
@@ -207,7 +207,7 @@ function git_commit_msg($rev)
  */
 function git_format($rev, $format)
 {
-    return execl("git log --format=$format -n1 $rev");
+    return implode("\n", execx("git log --format=$format -n1 $rev"));
 }

 
Regards,
Robbert-Jan

**Comment by glensc** [comment]
don't get from here what is your change or how to reproduce it

please submit Pull-Request to appropriate repository:
https://github.com/eventum/scm

and reproducer if possible (exact commit message perhaps)
