### ISSUE TITLE
Status Change Date column missing in list

### ISSUE THREAD

**Issue by cpinfold** [eventum/eventum#179]
In v 3.1.1 when viewing an issue list (list.php) with the "Status Change Date" column showing the column is blank even if the status has changed after creation of the issue.

Looking at the values passed to smarty:

the "list" passed to smarty includes for every issue:
`"status_change_date" => "" `

for **all** values (even where the status was changed after issue creation)

The "columns" passed to smarty show this:
```
...
"sta_change_date" => array:2 [
      "title" => "Status Change Date"
      "width" => ""
    ]
...
```

I'm not sure if the "sta_change_date" should match "status_change_date" or if it matters if no data is passed into the Smarty "list"?

Craig.

**Comment by balsdorf** [comment]
The status change column is a bit weird. You need to go into "manage/customize_listing.php" and setup what which date you want to show for each status. It is powerful to be able to do that, but it is not obvious.  We probably need to add an obvious pointer to that page.

**Comment by cpinfold** [comment]
Thanks Bryan I didn't know that.  A great place to add that link would be:
"manage/column_display.php"

I'll close this as a non-issue.
