### ISSUE TITLE
tar.gz bundle contains filenames with : which don't play nice with Windows

### ISSUE THREAD

**Issue by rjroos** [eventum/eventum#180]
Windows cannot have filenames with ":". Having these in the docs/wiki folder is a bit annoying when working with people who use Windows.

My problem is they will be removed from our git repository when they check in a completely different file but I suppose on Windows unpacking the distribution will also give errors.

Is it possible to rename them?

$ tar tf eventum-3.1.2.tar.gz | grep ':'
eventum-3.1.2/docs/wiki/Basic-User/Basic-User:-Creating-Issues.md
eventum-3.1.2/docs/wiki/Basic-User/Basic-User:-Editing-Preferences.md
eventum-3.1.2/docs/wiki/Basic-User/Basic-User:-FAQ.md
eventum-3.1.2/docs/wiki/Basic-User/Basic-User:-How-issues-are-handled-in-Eventum.md
eventum-3.1.2/docs/wiki/Basic-User/Basic-User:-Listing-Issues.md
eventum-3.1.2/docs/wiki/Basic-User/Basic-User:-Projects.md
eventum-3.1.2/docs/wiki/Basic-User/Basic-User:-RSS-feeds.md
...

**Comment by balsdorf** [comment]
I've looked into this a lot. If I remove the ":" from the title, github no longer puts the file into a subdirectory, instead it just puts it in the root. This is probably okay, but not as clean as I would like it. I'm going to look into alternatives and get back.

As a workaround for the moment, you should be able to tell your git client on windows to not clone the wiki submodule.

**Comment by glensc** [comment]
probably should just rename the files when making release tarball. unlikely for someone to matter that the markdown relative links stay working

**Comment by glensc** [comment]
will be fixed with next release
