### ISSUE TITLE
Is Eventum susceptable to HTTPoxy attack? 

### ISSUE THREAD

**Issue by jmhickman** [eventum/eventum#181]
Saw [this](//httpoxy.org) in my twitter feed. I don't know if Eventum is vulnerable to this handling of the Proxy header, or some component it depends upon is, but probably worth a check.

There will be a script coming from the `nmap` project soon that will make it trivial to check for, so I'd like to get my install patched before then, if possible.

**Comment by glensc** [comment]
Eventum is not webserver or any other CGI runner, so I do not see how is this relevant.

**Comment by jmhickman** [comment]
I know Eventum isn't a webserver, I'm not an idiot.

Owncloud is not a webserver either, and yet _one of its components,_ Guzzle, _was_ vulnerable because it makes HTTP requests that can be poisoned by the environment variables. 

If Eventum has no vulnerable dependecies, then great. If Eventum does not, itself, make HTTP requests, then great. Just trying to raise awareness about the issue.

**Comment by glensc** [comment]
Eventum Core doesn't do web requests that I know. But you are free to write anything in your Workflow or Custom Field or Customer classes.

**Comment by glensc** [comment]
btw, php-core commit in this area:
https://github.com/php/php-src/commit/98b9dfaec95e6f910f125ed172cdbd25abd006ec
and their related bug: http://bugs.php.net/72573
