### ISSUE TITLE
Standard Users get notes (maybe even see red items)

### ISSUE THREAD

**Issue by slay123** [eventum/eventum#193]
Recently we had internal discussion with Developers+ users and reporter wrote email that she doesn't understand what we ask from her. It wasn't meant for her. When replying to a note, I see that she is Recipient which is wrong.

![screenshot 2016-09-09 18 40 53](https://cloud.githubusercontent.com/assets/12842560/18393420/ec38f442-76bd-11e6-8abf-f45586138916.png)

Please do not send to non developers internal (red) stuff

**Comment by balsdorf** [comment]
Not a bug. Notes go to Standard users and above. If you don't want her to get notes, she should be given the role of reporter.
