### ISSUE TITLE
can not update user's Available Languages in Preference

### ISSUE THREAD

**Issue by yangmx** [eventum/eventum#194]
When I modify user't Available Languages in Preference , I can't modify it. I found the reason of mistake by 1 day ,because I know none about PHP.
In src/Controller/PreferencesController, the program can't obtain "$this->lang" in "function __construct()".So the "if ($this->lang)"  is false forever. Move the codes to "case 'update_account'" in "function defaultAction()", the result is right.
Thanks to your work ! It's very good !

**Comment by glensc** [comment]
yet it's very hard to understand what you describe here. navigate to the file in gitlab and press "edit" to the file. make changes. and create pull request. it's very trivial.

**Comment by yangmx** [comment]
![qq 20160913090323](https://cloud.githubusercontent.com/assets/8045753/18458116/f46ca05c-7990-11e6-8ece-3bf71843a15c.png)
my work environment :
apache 2.2
php 5.6.25

**Comment by glensc** [comment]
fixed in ca0c96fc464f7a0d57e49603bcad14a02fa2201f
