### ISSUE TITLE
Advanced search page broken (missing javascript call adv_search.ready()?)

### ISSUE THREAD

**Issue by rjroos** [eventum/eventum#199]
On eventum 3.1.2 if I go to advanced search and press 'Run search' it will not find anything because it uses these filters:

Current filters: Created Date: Is greater than 2016-09-27; Updated Date: Is greater than 2016-09-27; Last Response Date: Is greater than 2016-09-27; First Response Date: Is greater than 2016-09-27; Closed Date: Is greater than 2016-09-27 

Also, the checkbox 'Show date fields to search by' does nothing when clicked.

If I open the javascript console while on adv_search.php and execute 'adv_search.ready()' everything seems to work as expected.

**Comment by balsdorf** [comment]
This is working for me in the latest version. It sounded familiar though so I looked into it, I believe this is the patch I fixed it in: https://github.com/eventum/eventum/commit/99598a10c7db2489060d1712cb6882a574f65b7c
