### ISSUE TITLE
Running php bin/upgrade.php gives me a class PEAR_Error not found. (3.1.2 -> 3.1.3)

### ISSUE THREAD

**Issue by rjroos** [eventum/eventum#200]
PHP Fatal error:  Class 'PEAR_Error' not found in /X/eventum-3.1.3/vendor/pear/db/DB.php on line 948
app.ALERT: Fatal Error (E_ERROR): Class 'PEAR_Error' not found {"code":1,"message":"Class 'PEAR_Error' not found","file":"/X/eventum-3.1.3/vendor/pear/db/DB.php","line":948} {"file":null,"line":null,"class":null,"function":null,"memory_usage":"2.5 MB","memory_peak_usage":"2.5 MB","version":"3.1.3","usr_id":""}

If I edit vendor/pear/db/DB.php and uncomment the require_once 'PEAR.php' on line 30 it works.

**Comment by glensc** [comment]
damn. looks like the "require_once" removal is broken. we use composer autoloader so the pear require_once calls are not needed

**Comment by glensc** [comment]
weird. i am not able to reproduce this

```
➔ php -r 'require_once "init.php"; $db = new DB();'
➔ php -r 'require_once "init.php"; $db = new PEAR_Error();'
```

**Comment by glensc** [comment]
how did you upgrade? did you follow the [upgrade procedure](https://github.com/eventum/eventum/wiki/Upgrading)?

**Comment by rjroos** [comment]
Yep.

I always unpack eventum-X.tar.gz, copy over config/ from the old
installation and run php bin/upgrade.php.

I suspect my problem is in config.php, but can't find anything. Maybe
you have an idea?


if I unpack eventum-3.1.3.tar.gz and run:
$ php -r 'require_once "init.php"; $db = new PEAR_Error();'

It's fine.
$ echo ' ' > config/config.php
$ php -r 'require_once "init.php"; $db = new PEAR_Error();'
.. PHP_NOTICE about SITE_APP_NAME
PHP Stack trace:
PHP   1. {main}() Command line code:0
app.ALERT: Fatal Error (E_ERROR): Class 'PEAR_Error' not found {"code":1,"message":"Class 'PEAR_Error' not found","file":"Command line code","line":1} {"file":null,"line":null,"class":null,"function":null,"memory_usage":"2.25 MB","memory_peak_usage":"2.25 MB","version":"3.1.3","usr_id":""}


So something in config.php is making autoload not work...

Any ideas?

**Comment by glensc** [comment]
perhaps you run some code in config, but config is intended to be declarative. it should contain only `define` statements.

if you could post your `config.php` (with sensitive information obfuscated) i could test it myself and suggest some solution.

**Comment by rjroos** [comment]
See attached.

Your test 
'php -r 'require_once "init.php"; $db = new PEAR_Error();'
might be flawed... init.php exit(0)s if there is no
config.php, so new PEAR_Error() will never be called.


I just checked it with the git checkout with manual composer install
of dependencies, it works fine there :-(

It's the distribution one that doesn't work:

$ tar xf eventum-3.1.3.tar.gz 
$ cd eventum-3.1.3
$ echo ' ' > config/config.php
$ php -r 'require_once "init.php"; $db = new DB();'
 
PHP Notice:  Use of undefined constant APP_SITE_NAME - assumed 'APP_SITE_NAME' in
/home/user/ev/eventum-3.1.3/src/Monolog/MailHandler.php on line 38
app.WARNING: E_WARNING: Cannot modify header information - headers already sent by (output started at /home/user/ev/eventum-3.1.3/config/config.php:2)
{"code":2,"message":"Cannot modify header information - headers already sent by (output started at /home/user/ev/eventum-3.1.3/config/config.php:2)","file":"/home/user/ev/eventum-3.1.3/init.php","line":122} {"file":null,"line":null,"class":null,"function":"header","memory_usage":"2.25 MB","memory_peak_usage":"2.25 MB","version":"3.1.3","usr_id":""}
PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/user/ev/eventum-3.1.3/config/config.php:2) in /home/user/ev/eventum-3.1.3/init.php on line 122

PHP Fatal error:  Class 'PEAR_Error' not found in
/home/user/ev/eventum-3.1.3/vendor/pear/db/DB.php on line 948
app.ALERT: Fatal Error (E_ERROR): Class 'PEAR_Error' not found
{"code":1,"message":"Class 'PEAR_Error' not
found","file":"/home/user/ev/eventum-3.1.3/vendor/pear/db/DB.php","line":948}
{"file":null,"line":null,"class":null,"function":null,"memory_usage":"2.5
MB","memory_peak_usage":"2.5 MB","version":"3.1.3","usr_id":""}


Is it possible everybody has PEAR.php as some automatic php include
'thing'? Or is that nonsense, just guessing?

RJ


On 28/09/2016 11:07, Elan Ruusamäe wrote:
> perhaps you run some code in config, but config is intended to be declarative.
> it should contain only define statements.
> 
> if you could post your config.php (with sensitive information obfuscated) i
> could test it myself and suggest some solution.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

<?php

/* vim: set expandtab tabstop=4 shiftwidth=4 encoding=utf-8: */
// +----------------------------------------------------------------------+
// | Eventum - Issue Tracking System                                      |
// +----------------------------------------------------------------------+
// | Copyright (c) 2003 - 2008 MySQL AB                                   |
// | Copyright (c) 2008 - 2010 Sun Microsystem Inc.                       |
// | Copyright (c) 2011 - 2014 Eventum Team.                              |
// |                                                                      |
// | This program is free software; you can redistribute it and/or modify |
// | it under the terms of the GNU General Public License as published by |
// | the Free Software Foundation; either version 2 of the License, or    |
// | (at your option) any later version.                                  |
// |                                                                      |
// | This program is distributed in the hope that it will be useful,      |
// | but WITHOUT ANY WARRANTY; without even the implied warranty of       |
// | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        |
// | GNU General Public License for more details.                         |
// |                                                                      |
// | You should have received a copy of the GNU General Public License    |
// | along with this program; if not, write to:                           |
// |                                                                      |
// | Free Software Foundation, Inc.                                       |
// | 51 Franklin Street, Suite 330                                          |
// | Boston, MA 02110-1301, USA.                                          |
// +----------------------------------------------------------------------+
// | Authors: Bryan Alsdorf <bryan@mysql.com>                             |
// | Authors: Elan Ruusamäe <glen@delfi.ee>                               |
// +----------------------------------------------------------------------+

// Contains constants defined for this specific eventum installation.
// This file will not be overwritten when upgrading Eventum

// NOTE: if you are looking for database connection info in this file,
// then since 2.4.0 database configuration lies in setup.php

define('APP_NAME', 'Eventum');
define('APP_SHORT_NAME', APP_NAME); // used in the subject of notification emails
define('APP_HOSTNAME', 'XXXXXXXXX');
define('APP_SITE_NAME', APP_NAME);
define('APP_RELATIVE_URL', '/eventum/');
define('APP_BASE_URL', 'https://' . APP_HOSTNAME . APP_RELATIVE_URL);
define('APP_COOKIE_URL', APP_RELATIVE_URL);
define('APP_COOKIE_DOMAIN', null);
define('APP_COOKIE', 'eventum');
define('APP_COOKIE_EXPIRE', time() + (60 * 60 * 8));
define('APP_PROJECT_COOKIE', 'eventum_project');
define('APP_PROJECT_COOKIE_EXPIRE', time() + (60 * 60 * 24));

define('APP_DEFAULT_PAGER_SIZE', 100);
define('APP_DEFAULT_REFRESH_RATE', 5); // in minutes

// new users will use these for default preferences
// if the user will recieve an email when an issue is assigned to him
define('APP_DEFAULT_ASSIGNED_EMAILS', true);
// if the user will recieve an email when ANY issue is created
define('APP_DEFAULT_NEW_EMAILS', false);
// locale used for localized messages
define('APP_DEFAULT_LOCALE', 'en_US');
// timezone for displayed times in web and emails
define('APP_DEFAULT_TIMEZONE', 'Europe/Amsterdam');
// default day of week start: 0 = sunday; 1 = monday
define('APP_DEFAULT_WEEKDAY', 1);

// application charset, there is no good reason to use anything else than utf8,
// unless you use really old mysql which doesn't support charsets
define('APP_CHARSET', 'UTF-8');

// define colors used by eventum
define('APP_CELL_COLOR', '#255282');
define('APP_LIGHT_COLOR', '#DDDDDD');
define('APP_MIDDLE_COLOR', '#CACACA');
define('APP_DARK_COLOR', '#CACACA');
define('APP_CYCLE_COLORS', '#DDDDDD,#CACACA');
define('APP_INTERNAL_COLOR', '#9C494B');

// define the user_id of system user
define('APP_SYSTEM_USER_ID', 1);

// define the type of password hashing to use (MD5, MD5-64)
define('APP_HASH_TYPE', 'MD5');

// if full text searching is enabled
define('APP_ENABLE_FULLTEXT', true);
define('APP_FULLTEXT_SEARCH_CLASS', 'mysql_fulltext_search');

// auth backend. 'Mysql_Auth_Backend' (default), 'LDAP_Auth_Backend' for LDAP
//define('APP_AUTH_BACKEND', 'Mysql_Auth_Backend');

// 'native' or 'php'. Try native first, if you experience strange issues
// such as language switching randomly, try php
define('APP_GETTEXT_MODE', 'native');

// directory where to save routed drafts/notes/emails. leave empty/undefined to disable.
define('APP_ROUTED_MAILS_SAVEDIR', APP_PATH . '/misc');

**Comment by glensc** [comment]
ok, you're right at that part if `config/config.php` is empty problem is not reproducible

however, if i unpack the release, run clean install, i'm able to reproduce your error, but the upgrade script runs fine:

```
[~/scm/eventum/eventum/releases/eventum (master)⚡] ➔ ./bin/upgrade.php 
* Your database is already up-to-date. Version 58
[~/scm/eventum/eventum/releases/eventum (master)⚡] ➔ php -r 'require_once "init.php"; $db = new DB();print_r($db);'
PHP Fatal error:  Class 'PEAR_Error' not found in /home/glen/scm/eventum/eventum/releases/eventum-3.1.3/vendor/pear/db/DB.php on line 948
PHP Stack trace:
PHP   1. {main}() Command line code:0
PHP   2. spl_autoload_call() Command line code:1
PHP   3. Composer\Autoload\ClassLoader->loadClass() Command line code:1
PHP   4. Composer\Autoload\includeFile() /home/glen/scm/eventum/eventum/releases/eventum-3.1.3/vendor/composer/ClassLoader.php:301
PHP   5. include() /home/glen/scm/eventum/eventum/releases/eventum-3.1.3/vendor/composer/ClassLoader.php:414
app.ALERT: Fatal Error (E_ERROR): Class 'PEAR_Error' not found {"code":1,"message":"Class 'PEAR_Error' not found","file":"/home/glen/scm/eventum/eventum/releases/eventum-3.1.3/vendor/pear/db/DB.php","line":948} {"file":null,"line":null,"class":null,"function":null,"memory_usage":"2.75 MB","memory_peak_usage":"2.75 MB","version":"3.1.3","usr_id":""}
```

**Comment by glensc** [comment]
oh. default install uses `PDO`, but seems you are using `PEAR`, so if i do clean install, and change in `config/setup.php`:

```php
  'database' =>
  array (
    'driver' => 'mysql',
    'classname' => 'Pear',
```

i can indeed get same error. the `PEAR_Error` is defined in `PEAR.php`, but no autoloader map. so need to probe `PEAR` class before `PEAR_Errror` use:

```
➔ php -r 'require_once "init.php"; new PEAR; $db = new DB();print_r($db);'
DB Object
(
)
```

**Comment by rjroos** [comment]
Aha! Thanks for finding and fixing this.


FYI, my setup.php contained just this, no classname:

'database' =>
  array (
    'driver' => 'mysqli',
    'hostname' => 'REDACTED',
    'database' => 'REDACTED',
    'username' => 'REDACTED',
    'password' => 'REDACTED',
    'port' => 3306,
    'table_prefix' => '',
  ),



Thanks again!

Robbert-Jan

**Comment by glensc** [comment]
yes default is `PEAR` if not declared. new installations get `PDO`. it's so because `PDO` supports only utf8 (or at least how we use it here), so it's ok to force that on new installations.

ps: when posting comments via email, and you do a top-post, cut out the email you are not replying to.
