### ISSUE TITLE
process_mail_queue.php error

### ISSUE THREAD

**Issue by johnBim** [eventum/eventum#202]
Hi, 
I try to procress the maill queue and I have the error message bellow. I even tried with the quesry string fix-lock=1, but still the same issue. Could you please help? 
Many thanks

#!/usr/bin/php ERROR: Another instance of the script is still running for the specified account. 
If this is not accurate, you may fix it by running this script with 'fix-lock=1'
in the query string or you may unlock ALL accounts by running this script with 'fix-lock=1'
as the only parameter.

**Comment by cpinfold** [comment]
Hi John,

Do you have access to the command line?  

Are you able to run:
```
/path/to/eventum/bin/process_mail_queue.php --fix-lock
```
(replacing /path/to/eventum with your path)

What is the output of running that command?  Or if through the web server, what does it show?  You should be seeing: "Removed lock file"
How are you causing the process_mail_queue.php to run?  On what frequency?

Craig.

**Comment by glensc** [comment]
running cron scripts from web has been dropped long time ago

you probably should remove the lock file from `var/` dir and retry whatever you are doing. 

i mean you didn't even report what version you are using or how exactly are you invoking the script!

**Comment by johnBim** [comment]
Hi,
basically I have windows hosting and I use Windows Tasks Scheduler to call process_mail_queue.php with browser
I use the version 3.1.2
Thanks

**Comment by glensc** [comment]
did you remove the pid files [as told](https://github.com/eventum/eventum/issues/202#issuecomment-250758504)? if not why so?

**Comment by glensc** [comment]
Remove the lock files and retry. New Eventum version will remove support for lock files when #209 gets merged.
