### ISSUE TITLE
Editing "Manage Time Tracking Categories" - Sql Error

### ISSUE THREAD

**Issue by ramin-git** [eventum/eventum#208]
**Fatal error:** Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') GROUP BY 1' at line 7' in PdoAdapter.php:153 Stack trace: #0 .......

**Comment by glensc** [comment]
don't know what you error was, no information how to reproduce.

but i assume this was fixed in #197 or #196

**Comment by glensc** [comment]
@balsdorf i see you created branch to solve this? please finish it by creating PR!

**Comment by balsdorf** [comment]
@glensc You fixed it in #196 but I forgot to close this bug and delete the branch.

@ramin-git Thank you for the report, this has been fixed.
