### ISSUE TITLE
Eventum 3.1.3 Authorized Replier no option to select users

### ISSUE THREAD

**Issue by dgossage** [eventum/eventum#210]
I noticed after my update to 3.1.3 when adding authorized repliers their is no drop down in old style or the new style that notification list has of selecting users to add to list.

Perhaps it was just stripped from the template for some reason?

**Comment by glensc** [comment]
What was your previous version you upgraded from? There aren't any changes in that area in any recent releases.

**Comment by glensc** [comment]
Notification user list picker was removed long time ago in UI refactory process (43cc7ae - 2013) and restored years later in #34, i do not see changes to authorized repliers in 43cc7ae.

**Comment by dgossage** [comment]
original install was running from 2.3.3 which I believe I had obtained and installed from https://launchpad.net/eventum/trunk/2.3.3

This was few years back though so can't be sure this was url it was under at the time.

**Comment by glensc** [comment]
The `assoc_users` was removed from model in 052e9fd6, but from template it was removed earlier, that's also reason why it was removed from Controller.

**Comment by glensc** [comment]
Also, all releases are present on [GitHub Releases page](https://github.com/eventum/eventum/releases). so no worries.

**Comment by glensc** [comment]
593231d: removed from template.

what the user autocomplete list should be? the same as in Notification popup?

**Comment by glensc** [comment]
i've updated `snapshot` tag to include changes containing the fix.

so if travis has finished building the tarball should appear here:
https://github.com/eventum/eventum/releases/tag/snapshot

or you could just use master branch from git checkout, but then you have to handle composer dependencies yourself.

**Comment by dgossage** [comment]
Thanks looks to be working well so far
