### ISSUE TITLE
Your session has expired. Please login again to continue.

### ISSUE THREAD

**Issue by lmoralesa** [eventum/eventum#213]
Hi, I upgrade from version 3.0.12 to 3.1.4, when I login to Events I got the message "Your session has expired. Please login again to continue."

**Comment by lmoralesa** [comment]
I'll check my database and before upgrade my  database use a prefix vpn_, after the upgrade the prefix dissapear.

**Comment by glensc** [comment]
post your upgrade log.

**Comment by lmoralesa** [comment]
It keeps asking to sign in, the message I got is Your session has expired. Please login again to continue., It does not recognice the users on the db, I'll check the database and all users are created.

**Comment by glensc** [comment]
Please recheck the situation in Incognito window to ensure any stale cookie does not cause issues. Also it's known that cookies do not work well if using "IP" or "localhost" urls (http://1.3.3.4, http://localhost).

if it is unable to authenticate with users, the error should be `Error: The login / password combination could not be found in the system.` not session expired.

Do you have any other custom code initialized when Eventum is launched? perhaps it's messing up sessions? there were several session related changes in 3.1.1-3.1.3, please see the Changelog.

**Comment by lmoralesa** [comment]
Thanks for your answer, I'll follow you recommendations and check if I got a success login.
