### ISSUE TITLE
SCM Integration section bugs - it's colored blue (Public) and show/hide gives fatal error

### ISSUE THREAD

**Issue by slay123** [eventum/eventum#215]
1. it is painted blue, as Public section, but de facto is visible only for internal users, see issue #214 for screenshot.
2. clicking show/hide gives JS error

![screenshot 2016-10-31 14 38 10](https://cloud.githubusercontent.com/assets/12842560/19854471/c730a162-9f77-11e6-8d00-42b540235332.png)

**Comment by glensc** [comment]
i'm unable to reproduce the js error. do you get the error with regular user or reporter?

**Comment by glensc** [comment]
ah, the js error comes when clicking these:
![image](https://cloud.githubusercontent.com/assets/199095/19869538/6bedb2d4-9fb5-11e6-916d-cba24869b9c8.png)
not these:
![image](https://cloud.githubusercontent.com/assets/199095/19869555/7b652f80-9fb5-11e6-85dd-0b7f99357fb2.png)
