### ISSUE TITLE
Error when creating a new issue on a fresh install

### ISSUE THREAD

**Issue by tiagom62** [eventum/eventum#218]
Installed on a server running cPanel. Apache 2.4.23 and 5.6.27. Eventum 3.1.4. 

When i attempt to create a new issue i receive the following errors:

Strict Standards: Non-static method Issue::insertIssue() should not be called statically in /home/eventum/public_html/eventum/lib/eventum/class.issue.php on line 2021

Strict Standards: Non-static method Notification::addType() should not be called statically in /home/eventum/public_html/eventum/lib/eventum/class.notification.php on line 2124

Strict Standards: Non-static method Notification::addType() should not be called statically in /home/eventum/public_html/eventum/lib/eventum/class.notification.php on line 2124

Strict Standards: Non-static method Notification::addType() should not be called statically in /home/eventum/public_html/eventum/lib/eventum/class.notification.php on line 2124

Strict Standards: Non-static method Notification::addType() should not be called statically in /home/eventum/public_html/eventum/lib/eventum/class.notification.php on line 2124

Strict Standards: Non-static method Issue::updateAssociatedIssuesRelations() should not be called statically in /home/eventum/public_html/eventum/lib/eventum/class.issue.php on line 2180

Strict Standards: Non-static method Notification::notifySubscribers() should not be called statically in /home/eventum/public_html/eventum/lib/eventum/class.notification.php on line 1170

Warning: Cannot modify header information - headers already sent by (output started at /home/eventum/public_html/eventum/lib/eventum/class.issue.php:2021) in /home/eventum/public_html/eventum/lib/eventum/class.auth.php on line 286

**Comment by glensc** [comment]
made some fixes in #230

you can test that branch by using tarball from "snapshot" release:
https://github.com/eventum/eventum/releases/snapshot
