### ISSUE TITLE
From field is garbled if senders name contains unicode

### ISSUE THREAD

**Issue by balsdorf** [eventum/eventum#225]
When sending an email from the web interface, if the senders name contains unicode and "Add Unknown Recipients to Issue Notification List" is **not** checked the from field will contain the Quoted-printable version of the name, such as =?UTF-8?Q?Admi=C3=B1_User?= <issue-60@example.com>

![image](https://cloud.githubusercontent.com/assets/127861/21061223/066469ec-be11-11e6-83d4-bba0f2e00e43.png)

This is caused by a line of code that is only executed when "Add Unknown" is not checked: https://github.com/eventum/eventum/blob/2415165ab30ab24cd6bed16feb11085705b77720/lib/eventum/class.support.php#L2110

**Comment by glensc** [comment]
never refer to source line using branch name, use git tag or git commit instead. problem is that the line numbers get out of place over time.

**Comment by balsdorf** [comment]
Thanks!  I had remembered you said something about this  before but I couldn't remember what exactly. I've updated this issue
