### ISSUE TITLE
Force https

### ISSUE THREAD

**Issue by tiagom62** [eventum/eventum#227]
Is it possible to force eventum to use https?

`define('APP_BASE_URL', 'http://' . APP_HOSTNAME . APP_RELATIVE_URL);`
to
`define('APP_BASE_URL', 'https://' . APP_HOSTNAME . APP_RELATIVE_URL);`
Doesn't do it.

I am unable to edit the rewriterules to force https

```#
# You should not expose Eventum to web root.
# Only htdocs directory should be exposed to webroot
#
# See installation documentation from wiki:
# https://github.com/eventum/eventum/wiki/System-Admin%3A-Doing-a-fresh-install
#

# This is just workaround to redirect all requests outside /htdocs/ to /htdocs/.
# Not perfect, but covers likely most of the cases.

RewriteEngine On

# Capture $BASE variable
# http://stackoverflow.com/a/18589126/2314626
RewriteCond %{REQUEST_URI}::$1 ^(/.+)/(.*)::\2$
RewriteRule ^(.*)$ - [E=BASE:%1]

# Redirect to htdocs/ if url already does not match 'htdocs'
RewriteCond %{REQUEST_URI} !/htdocs/
RewriteCond %{REQUEST_FILENAME} !/htdocs/
RewriteRule ^(.*)$ %{ENV:BASE}/htdocs/$1 [R=302,L]
```

Normally i would do something like 

```
RewriteCond %{HTTPS} !=on 
RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
```

**Comment by tiagom62** [comment]
Looks like adding the following to the end of the eventums .htaccess accomplishes what i'm after. Does anyone see any downsides?

```
RewriteCond %{HTTPS} !=on 
RewriteRule ^/?(.*) https://%{HTTP_HOST}%{REQUEST_URI}
```

**Comment by tiagom62** [comment]
If there is an easier way it is not stated here https://github.com/eventum/eventum/wiki/System-Admin%3A-Doing-a-fresh-install#installing-on-ssl-https

**Comment by glensc** [comment]
You should not modify [/.htaccess](https://github.com/eventum/eventum/blob/v3.1.6/.htaccess) this is workaround for dudes who failed to setup their `Alias`/`VirtualHost` properly.

You must use `htdocs/` directory: [Point your webserver to that /path-to-eventum/htdocs/](https://github.com/eventum/eventum/wiki/System-Admin%3A-Doing-a-fresh-install#installation-process)

The redirect rules should be therefore added to [/htdocs/.htaccess](https://github.com/eventum/eventum/blob/v3.1.6/htdocs/.htaccess)

As for the [Documentation](https://github.com/eventum/eventum/wiki/System-Admin%3A-Doing-a-fresh-install#installing-on-ssl-https), do not confuse `use https` url with `force https`. Documentation mentions how to `use`, you are looking how to `enforce`.
