### ISSUE TITLE
Enventum unable to login

### ISSUE THREAD

**Issue by bkeve** [eventum/eventum#231]
I need to get some help on login to into Eventum, am very new to this tool. 
I have  box installed with version 1.7.1 on  Linux box, this was installed someone in a different company .
it came to a box and no information  about login.  

after login to hit hub and reading the all the documents, still I could not get through it. tried default account admin@eample.com  with admin passwd etc..
 also tried to create an account with following option

GRANT SELECT, UPDATE, DELETE, INSERT ON eventum.* TO
'eventum_username'@'%' IDENTIFIED BY 'eventum_password';

so far nothing worked I get following error message in the log file

2016-12-20 08:07:47 - Login attempt by 'eventum_username' was not successful because of 'unknown user'.
2016-12-20 08:10:46 - Login attempt by 'eventum@localhost' was not successful because of 'unknown user'.
2016-12-20 07:22:13 - Login attempt by 'admin@example.com' was not successful because of 'unknown user'.
2016-12-20 08:21:42 - Login attempt by 'admin' was not successful because of 'unknown user'.

**Comment by glensc** [comment]
what you did was mysql username allowing eventum app to use mysql. what you need is eventum user.

here's some wiki doc: https://github.com/eventum/eventum/wiki/System-Admin:-Become-Super-Administrator

it's likely out of date, so i will update it

**Comment by bkeve** [comment]
Leave a comment

**Comment by bkeve** [comment]
thank you for the note, I am not familiar with MySQL command, if you can correct me appreciate that.
here is steps I have followed
SELECT usr_id FROM eventum_user WHERE usr_email='admin@example.com';
UPDATE eventum_project_user SET pru_role = 7 WHERE pru_usr_id = 2 LIMIT 1;

command tools without any error
I am sure did not do it right, will you correct me my sytancx. when I list the user list from eventum database, here is the list I find.

eventum     | %                     | eventum_username |
| eventum     | %                     | evreadonly       |
| eventum     | %                     | evuser           |
| gopal       | %                     | gopal            |
| test        | %                     |                  |
| test\_%     | %                     |                  |
| wikidb      | %                     | wikiuser         |
| eventum     | java                  | root             |
| eventum     | localhost             | root             |

**Comment by glensc** [comment]
You are still mixing Eventum users (Eventum Accounts) and MySQL database users!

i do not know what the table is that you pasted (no information provided), but it definately looks like something `select * from mysql.users`

**Comment by glensc** [comment]
and you should NOT BLINDLY execute the two commands:

```sql
SELECT usr_id FROM eventum_user WHERE usr_email='admin@example.com';
UPDATE eventum_project_user SET pru_role = 7 WHERE pru_usr_id = <USR_ID_RESULT_FROM_PREVIOUS_QUERY> LIMIT 1;
```

you must run the first command, capture result of that, in the example the result is `2`:

```sql
UPDATE eventum_project_user SET pru_role = 7 WHERE pru_usr_id = 2 LIMIT 1;
```

otherwise you be setting as admin random user whose id is `2`

**Comment by bkeve** [comment]
sorry bother you, if you can guide that would be grate, 
, I  get the following output

use eventum
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> UPDATE eventum_project_user SET pru_role = 7 WHERE pru_usr_id = 2 LIMIT 1                                    ;
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0

what is need to be done next ?

thanks

**Comment by glensc** [comment]
now your user with id `2` is admin, as the wiki document explained.

**Comment by bkeve** [comment]
thank you, I am lost 

confusing me here  which is the user ID belong to "2"  enabling the admin privilege, is it going to be admin@example.com?  what should I do next? 
UPDATE eventum_project_user SET pru_role = 7 WHERE pru_usr_id = 2 LIMIT 1;

**Comment by glensc** [comment]
i don't know what is your database, that's what you're supposed to execute yourself as i already said:
https://github.com/eventum/eventum/issues/231#issuecomment-268474908

use `usr_email` value whatever email you intend to promote to admin. it does not have to be `admin@example.com`, it's just example what it could be

**Comment by bkeve** [comment]
database name is eventum, when I look into the database I could not find following  list is users form the database.  in this case which user I should make it administrator,  I don't know the passwd of any of theses accounts. 

thanks
eventum     | %                     | eventum_username |
| eventum     | %                     | evreadonly       |
| eventum     | %                     | evuser           |
| gopal       | %                     | gopal            |
| test        | %                     |                  |
| test\_%     | %                     |                  |
| wikidb      | %                     | wikiuser         |
| eventum     | java                  | root             |
| eventum     | localhost             | root

**Comment by glensc** [comment]
and yet again you're pasting mysql users, not eventum users! i already answered you this: https://github.com/eventum/eventum/issues/231#issuecomment-268474578
and told you to show actual command you ran, not only output!
https://github.com/eventum/eventum/issues/231#issuecomment-268474578

eventum users are in `eventum_user` table, which i've pointed you several times:
https://github.com/eventum/eventum/issues/231#issuecomment-268474908
https://github.com/eventum/eventum/issues/231#issuecomment-269356269

**Comment by glensc** [comment]
the default password is inserted here:

https://github.com/eventum/eventum/blob/v1.7.1/eventum/setup/schema.sql#L504

so something like this will set default password for user with id=2:

```sql
update eventum_user set usr_password= '21232f297a57a5a743894a0e4a801fc3' usr_id=2;
```

and what is the actual id you need to use, i don't know your database. you need to figure out that yourself.

and before you start to dump mysql users again, familarize yourself what is [mysql users](http://dev.mysql.com/doc/refman/5.7/en/adding-users.html) and what is eventum users.

**Comment by bkeve** [comment]
okay, how do find out my eventum database. my understating database name is eventum, I know am annoying  you,  someone dumped on me without all the this information, not even passwd, accounts ....etc.. 
is there any way I can list out user names?
thanks

**Comment by glensc** [comment]
table name should be `eventum_user`.

this is not mysql support forum, ask mysql related questions in appropriate forums.
