### ISSUE TITLE
Not Able To login After Successfull Installation

### ISSUE THREAD

**Issue by sonumaddheshiya** [eventum/eventum#232]
Hi
I Have Installed a Latest Version of Eventum 3.1.6 but Not Able To login After Successfull Installation

i am using 
Apache/2.2.31
php 5.4
Mysql Server version: 5.5.53

Getting Following Error on Login
**Fatal error**: Call to undefined function password_verify() in **lib/eventum/auth/AuthPassword.php** on line **55**

**Comment by glensc** [comment]
looks like your install is broken. how exactly did you install? give exact urls you downloaded (or commands executed if installed via git).

**Comment by sonumaddheshiya** [comment]
Thanks 👍
