### ISSUE TITLE
Error creating new priorities in new projects

### ISSUE THREAD

**Issue by plindry** [eventum/eventum#242]
Hi,
in a fresh installation (3.1.9) i get this error when i try to create new priorities in a new project. 

Fatal error: Uncaught PDOException: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in /opt/lampp/htdocs/eventum-3.1.9/src/Db/Adapter/PdoAdapter.php:139 Stack trace: #0 /opt/lampp/htdocs/eventum-3.1.9/src/Db/Adapter/PdoAdapter.php(139): PDOStatement->execute(Array) #1 /opt/lampp/htdocs/eventum-3.1.9/lib/eventum/class.priority.php(221): Eventum\Db\Adapter\PdoAdapter->query('INSERT INTO\n ...', Array) #2 /opt/lampp/htdocs/eventum-3.1.9/src/Controller/Manage/PrioritiesController.php(64): Priority::insert() #3 /opt/lampp/htdocs/eventum-3.1.9/src/Controller/Manage/PrioritiesController.php(48): Eventum\Controller\Manage\PrioritiesController->newAction() #4 /opt/lampp/htdocs/eventum-3.1.9/src/Controller/BaseController.php(63): Eventum\Controller\Manage\PrioritiesController->defaultAction() #5 /opt/lampp/htdocs/eventum-3.1.9/htdocs/manage/priorities.php(17): Eventum\Controller\BaseController->run() #6 {main} thrown in /opt/lampp/htdocs/eventum-3.1.9/src/Db/Adapter/PdoAdapter.php on line 139

I try two differents installs and the error is the same.
No issue in our production eventum (3.0.6) creating new priorities in a new project

**Comment by phavel** [comment]
It will be fixed in next release apparently (f34bf3f ).

**Comment by plindry** [comment]
Ok thanks

**Comment by balsdorf** [comment]
@plindry It is a one line fix in the linked commit if you want to apply it now. Thanks @phavel for the quick response. I'm going to close this issue.
