### ISSUE TITLE
Uncaught exception creating a repeated release

### ISSUE THREAD

**Issue by plindry** [eventum/eventum#246]
When you create a Release in a project with the same name you get an uncaught exception:

Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2-ARID' for key 'pre_title' in /opt/lampp/htdocs/eventum-3.1.9/src/Db/Adapter/PdoAdapter.php:139 Stack trace: #0 /opt/lampp/htdocs/eventum-3.1.9/src/Db/Adapter/PdoAdapter.php(139): PDOStatement->execute(Array) #1 /opt/lampp/htdocs/eventum-3.1.9/lib/eventum/class.release.php(196): Eventum\Db\Adapter\PdoAdapter->query('INSERT INTO\n ...', Array) #2 /opt/lampp/htdocs/eventum-3.1.9/src/Controller/Manage/ReleasesController.php(62): Release::insert() #3 /opt/lampp/htdocs/eventum-3.1.9/src/Controller/Manage/ReleasesController.php(48): Eventum\Controller\Manage\ReleasesController->newAction() #4 /opt/lampp/htdocs/eventum-3.1.9/src/Controller/BaseController.php(63): Eventum\Controller\Manage\ReleasesController->defaultAction() #5 /opt/lampp/htdocs/eventum-3.1.9/htdocs/manage/releases.php(17): Eventum\Controller\BaseController->run() #6 {main} thrown in /opt/lampp/htdocs/eventum-3.1.9/src/Db/Adapter/PdoAdapter.php on line 139

**Comment by balsdorf** [comment]
Thanks for the report. I've added a check for uniqueness before the release is created.
