### ISSUE TITLE
modern uploader

### ISSUE THREAD

**Issue by glensc** [eventum/eventum#25]
should modernize uploader, upload should be drag and droppable, allow multiple files and previews if upload is type image

here's 15 minute review of [drag and drop upload](https://www.google.com/search?q=drag+and+drop+upload) google search:

http://html5demos.com/dnd-upload
- no library, inline js, but tiny

https://github.com/devbridge/html5-file-uploader
- license: mit
- pure js
- code: 15 commits, 0 releases
- demo: https://www.devbridge.com/sourcery/components/drag-and-drop-uploader/

https://github.com/ProgerXP/FileDrop
- license public domain
- version 2.0.0
- code: 41 commits, 0 releases 
- pure js
- jquery ready
- 500+ lines of unit tests
- demo: http://filedropjs.org/
- bower integration

https://github.com/enyo/dropzone 
- license: mit
- no jquery, pure js
- version 3.12.0
- code: 708 commits, 88 releases
- demo: http://www.dropzonejs.com/
- examples: https://github.com/enyo/dropzone/wiki 
- includes "component" integration
- image thumbnail previews
- retina enabled
- big files not problem
- ui and code separated, clean apis
- previews via callback that doesn't kill browser
- does not care for old browsers

https://github.com/danielm/uploader 
- mit/gpl license 
- code 11 commits, 1 release 
- version 0.1.0 
- jquery plugin 
- focuses modern browsers, but legacy ones should work too 
- callbacks 
- image preview 
- blog http://blog.daniel.com.uy/2013/11/jquery-drag-and-drop-progress-files.html 
- demo bootstrap: http://danielm.herokuapp.com/demos/dnd/ 
- demo plain: http://danielm.herokuapp.com/demos/dnd/simple.php 
- demo with preview: http://danielm.herokuapp.com/demos/dnd/image-preview.php 

https://github.com/Formstone/Dropper
- code 11 commits, 6 releases
- version 1.0.1
- bower integration
- jquery plugin
- demo http://formstone.it/components/Dropper/demo/index.html
- multiple files drop
- events

**Comment by glensc** [comment]
WIP: https://github.com/glensc/eventum/compare/dropzone

some todo items came up:
- [ ] add dropzone new issue page
- [ ] add dropzone send note popup
- [ ] improve error handling if dragged file could not be uploaded
- [ ] current ui says about file upload, make it plural and talk about attachment instead of file
- [ ] do not allow finish upload dialog if nothing is uploaded
- [ ] cleanup api

**Comment by glensc** [comment]
noted that in send email popup, when you save email as draft instead of sending it out, the attachments are lost

**Comment by glensc** [comment]
e4b54b73 changes behavior a bit. should make more hacks to avoid these, or let it be?

**Comment by balsdorf** [comment]
I think this should be fine. If later we have a reason to change it we can.

On Sat, Mar 28, 2015 at 11:58 AM, Elan Ruusamäe <notifications@github.com>
wrote:

> e4b54b7
> <https://github.com/eventum/eventum/commit/e4b54b737c57d7cb38cfc5bc9c052bc33c73abe0>
> changes behavior a bit. should make more hacks to avoid these, or let it be?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eventum/eventum/issues/25#issuecomment-87268134>.
>



-- 
Bryan Alsdorf
MariaDB Corporation | http://mariadb.com
