### ISSUE TITLE
length of email headers

### ISSUE THREAD

**Issue by glensc** [eventum/eventum#266]
i was investigating why code from here:
[lib/eventum/class.support.php:1551-1552](https://github.com/eventum/eventum/blob/v3.1.10/lib/eventum/class.support.php#L1551-L1552)

was throwing mail parse errors:
```
Zend\Mail\Exception\InvalidArgumentException(code: 0):
'blah, blah <blah.blah' can not be matched against dot-atom format at ...
```

seems that `to_cc` was truncated to 255 chars at the time data was inserted.
i checked the database, and the field is longer now, however can't find patch which increased the size, and seems they are inconsistent:

```mysql
  `sup_from` varchar(255) NOT NULL DEFAULT '',  
  `sup_to` text,
  `sup_cc` mediumtext,
  `sup_subject` varchar(255) NOT NULL DEFAULT '',
```

we should decide what the field type and length are and unify it everywhere, possibly fixing corrupted fields as well.

**PS**: in pristine installation `sup_cc` is:
```mysql
  `sup_cc` text,
```

**Comment by glensc** [comment]
from my system:

```
mysql> select max(length(sup_to)) max_to, max(length(sup_cc)) max_cc, max(length(sup_subject)) max_subject from support_email;
+--------+--------+-------------+
| max_to | max_cc | max_subject |
+--------+--------+-------------+
|   2135 |    728 |         255 |  
+--------+--------+-------------+
1 row in set (0.24 sec) ```

wow

**Comment by balsdorf** [comment]
```
+--------+--------+-------------+
| max_to | max_cc | max_subject |
+--------+--------+-------------+
|    505 |    487 |         176 |
+--------+--------+-------------+
```

my production system is `text` as well. 

Looks like this was done in the 1.7.1 to 2.0 upgrade: https://github.com/eventum/eventum/blob/61756798fdafcd28bb0eb9d7c3c752a885d56b00/eventum/misc/upgrade/v1.7.1_to_v2.0/database_changes.php

I'd say text is the right type for both sup_to and sup_cc. For subject, technically text would be appropriate, but I practically speaking I'm okay with truncating it down. The UI would do bad things with a 1000+ character subject.

**Comment by cpinfold** [comment]
+--------+--------+-------------+
| max_to | max_cc | max_subject |
+--------+--------+-------------+
|    641 |    403 |         208 |
+--------+--------+-------------+

| sup_to             | text
| sup_cc             | mediumtext
| sup_subject        | varchar(255)

Craig.

**Comment by glensc** [comment]
- TINYTEXT 256 bytes
- TEXT 65,535 bytes ~64kb
- MEDIUMTEXT 16,777,215 bytes ~16MB
- LONGTEXT 4,294,967,295 bytes ~4GB
- VARCHAR <65,535 bytes excluding max row size limit

not sure why `sup_cc` is mediumtext, should be same as `to_cc`.
but why not `varchar(4096)` or something?

there are some differences with `TEXT` vs `VARCHAR` i understand:
> The internal representation of a table has a maximum row size of 65,535 bytes, even if the storage engine is capable of supporting larger rows. This figure excludes BLOB or TEXT columns, which contribute only 9 to 12 bytes toward this size. For BLOB and TEXT data, the information is stored internally in a different area of memory than the row buffer. https://dev.mysql.com/doc/refman/5.7/en/storage-requirements.html#data-types-storage-reqs-strings

so, sum of length of `VARCHAR` columns must not exceed 65,535 bytes and compared to `TEXT` column, it uses same buffer that was allocated for row.

so using `VARCHAR` seems better option?

**Comment by glensc** [comment]
also, should the values be NULLable or empty strings?


```
mysql> select count(*) from support_email where sup_to='';
|    32990 |

mysql> select count(*) from support_email where sup_cc='';
|   108532 |

mysql> select count(*) from support_email where sup_cc is null;
|    16412 |

mysql> select count(*) from support_email where sup_to is null;
|     1875 |
``

**Comment by glensc** [comment]
i've created PR #271 to passing code from creating Address objects and formatting them again.

**Comment by balsdorf** [comment]
Upon reading up on the differences, VARCHAR seems a better fit. It can be indexed and has less overhead when retrieving it.

Lets go with empty strings. No real reason other than having both empty strings and null is annoying.
