### ISSUE TITLE
Error in custom fileds

### ISSUE THREAD

**Issue by plindry** [eventum/eventum#267]
Hi,

I was running 3.1.9 version. When i update to the new release(3.1.10) i get this error in ../eventum/manage/custom_fields.php line 120.

https://github.com/eventum/eventum/blob/master/src/Controller/Manage/CustomFieldsController.php#L120

Fatal error: Uncaught Error: Access to undeclared static property: Custom_Field::$order_by_choices in /opt/lampp/htdocs/eventum-3.1.10/src/Controller/Manage/CustomFieldsController.php:120 Stack trace: #0 /opt/lampp/htdocs/eventum-3.1.10/src/Controller/BaseController.php(64): Eventum\Controller\Manage\CustomFieldsController->prepareTemplate() #1 /opt/lampp/htdocs/eventum-3.1.10/htdocs/manage/custom_fields.php(17): Eventum\Controller\BaseController->run() #2 {main} thrown in /opt/lampp/htdocs/eventum-3.1.10/src/Controller/Manage/CustomFieldsController.php on line 120

I'll try in a new install in a test enviroment

**Comment by plindry** [comment]
In a fresh installtion is ok. 
We are investigating, we found this error Uncaught PDOException: SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet'.

We will increase de max_allowed_packet.

**Comment by balsdorf** [comment]
I cannot reproduce the error with custom fields. If you look in your actual install directory does $order_by_choices exist?

The max_allowed_packet is unrelated.

**Comment by plindry** [comment]
Thanks balsdorf, in a fresh installation we can't reproduce the error either.
We increase the packet size and is running now. Perhaps different errors at the same time.

Regards
