### ISSUE TITLE
Time Tracking - editing text containting quotation mark

### ISSUE THREAD

**Issue by pkrupicka** [eventum/eventum#273]
**Edit Time Worked** dialog mishandles text containing quotation mark.

![eventum-edit-time-worked-error](https://cloud.githubusercontent.com/assets/544580/26627016/47d7d484-45f9-11e7-8d91-72856c02b92f.png)

**Comment by balsdorf** [comment]
Thanks for reporting! I've fixed it and it will be in our next release.
