### ISSUE TITLE
Zend\Mail\Transport\Factory missing from eventum-3.2.0 release tarball

### ISSUE THREAD

**Issue by rjroos** [eventum/eventum#274]
After upgrading to eventum-3.2.0 my process_mail_queue crashes:

```
$ /usr/bin/php -q process_mail_queue.php
PHP Fatal error:  Class 'Zend\Mail\Transport\Factory' not found in X/eventum-3.2.0/src/Mail/MailTransport.php on line 84
app.ALERT: Fatal Error (E_ERROR): Class 'Zend\Mail\Transport\Factory' not found {"code":1,"message":"Class 'Zend\\Mail\\Transport\\Factory' not found","file":"X/eventum-3.2.0/src/Mail/MailTransport.php","line":84} {"file":null,"line":null,"class":null,"function":null,"memory_usage":"3.5 MB","memory_peak_usage":"3.5 MB","version":"3.2.0","usr_id":""}
```

I would suspect this file being in the tarball but it isn't
```
$ wget https://github.com/eventum/eventum/releases/download/v3.2.0/eventum-3.2.0.tar.gz
$ tar xf eventum-3.2.0.tar.gz
$ find eventum-3.2.0 | grep Transport
eventum-3.2.0/src/Mail/MailTransport.php
$
```

**Comment by glensc** [comment]
fixed.

can be tested with snapshot tarball:
```
$ wget https://github.com/eventum/eventum/releases/download/snapshot/eventum-3.2.0-34-g2e79513b8.tar.gz
$ tar tvf eventum-3.2.0-34-g2e79513b8.tar.gz | grep Transport.Factory
-rw-rw-r-- root/root      2703 2017-06-06 20:43 eventum-3.2.0-34-g2e79513b8/vendor/zendframework/zend-mail/src/Transport/Factory.php
$
```

**Comment by rjroos** [comment]
On 06/06/2017 19:52, Elan Ruusamäe wrote:
> fixed.
> 
> can be tested with snapshot tarball:
> 
> $ wget https://github.com/eventum/eventum/releases/download/snapshot/eventum-3.2.0-34-g2e79513b8.tar.gz
> $ tar tvf eventum-3.2.0-34-g2e79513b8.tar.gz | grep Transport.Factory
> -rw-rw-r-- root/root      2703 2017-06-06 20:43 eventum-3.2.0-34-g2e79513b8/vendor/zendframework/zend-mail/src/Transport/Factory.php


Cool, thanks!

The commit makes sense so I assume it works, but the file mentioned
does not exist:

$ wget https://github.com/eventum/eventum/releases/download/snapshot/eventum-3.2.0-34-g2e79513b8.tar.gz
--2017-06-07 16:11:45--
https://github.com/eventum/eventum/releases/download/snapshot/eventum-3.2.0-34-g2e79513b8.tar.gz
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443...  connected.
HTTP request sent, awaiting response... 404 Not Found
2017-06-07 16:11:46 ERROR 404: Not Found.

Regards,
Robbert-Jan

**Comment by glensc** [comment]
you grab the proper snapshot release from "snapshot" tag:
https://github.com/eventum/eventum/releases/tag/snapshot

i'll release 3.2.1 soonish!
