### ISSUE TITLE
Expected Resolution Date

### ISSUE THREAD

**Issue by lmoralesa** [eventum/eventum#275]
I have and issue with eventum 3.1.10

I have a situation, for example, creates a case dated 06/02/2017, at the time of choosing Expected Resolution Date I choose the 06/06/2017, filled the other fields and everything normal.
At the moment of going to the section of list of cases the column of Expected Resolution Date shows me the date of resolution chosen less one day, or 05/06/2017.
I would like to know if someone else has had this problem or some clue how to solve it.
Thank you.

**Comment by balsdorf** [comment]
Hi!

Are you entering the date manually or using the date picker? I'm wondering if it is a matter of Eventum expecting the date to be in the format YYYY-MM-DD. My other thought would be timezone, but that field is not supposed to be converted anywhere.

What is the raw value in the database? 
`SELECT iss_expected_resolution_date FROM issue WHERE iss_id = XXX`

**Comment by lmoralesa** [comment]
Thanks for the quick response, I was looking for options to solve the problem and this was solved by making the change in the server's php.ini with the time zone to which I belong and also in the preferences of the user of the eventum, I select UTC time zone And the problem was solved.
Thank you very much for yor answer  and support

**Comment by balsdorf** [comment]
Ah great to know. I will close this issue now. Thanks for using Eventum
