### ISSUE TITLE
Password Recovery

### ISSUE THREAD

**Issue by lmoralesa** [eventum/eventum#276]
I have install Eventum 3.1.10.

I want to configure the option I Forgot My Password,  so the users that forgot their passwords can do it by this option automatically.

I need help on getting info on how to configure these option.

**Comment by balsdorf** [comment]
There is no configuration that needs to happen, it should work out of the box.

Do you have the mail setup so they can receive their new password?

https://github.com/eventum/eventum/wiki/System-Admin%3A-Doing-a-fresh-install#mail-queue-process-process_mail_queuephp

**Comment by lmoralesa** [comment]
Thanks for your help.

I already configure the option.

**Comment by glensc** [comment]
reporter can close their issues in github

**Comment by glensc** [comment]
@lmoralesa did not close the issue (even if asked), closing myself then
