### ISSUE TITLE
Empty PHP Sessions

### ISSUE THREAD

**Issue by webguy2004** [eventum/eventum#281]
We are noticing lots of empty php sessions on our server and can't figure out how/why they are getting there.

Does eventum create lots of empty session data?  We don't have many php applications running on our server so if it's not one of them, we are concerned there may be something malicious running.

**Comment by balsdorf** [comment]
Eventum will create a session for everyone who logs in, but it should at least have the usr_id stored in it.

Depending on your PHP settings sessions could be auto starting anytime someone visits a PHP page, even if it doesn't use sessions. See http://php.net/manual/en/session.configuration.php#ini.session.auto-start

**Comment by webguy2004** [comment]
Great thanks for the quick followup.  Our auto-start variable is disabled so it's not that.  I'll investigate a bit further.
