### ISSUE TITLE
5.1.3 Invalid Address

### ISSUE THREAD

**Issue by manord831** [eventum/eventum#282]
After upgrading to 3.2.1 email notification stopped working.
the mail_queue_log error is5.1.3 Invalid Address.
None of the setting have been changed.

thank you,

Dror

**Comment by glensc** [comment]
not enough information

**Comment by manord831** [comment]
Sorry for that,
I'm running Eventum on a windows 2012 R2. 
PHP 5.6.23.
I am able to sent an email from the server using telnet and the same credentials as Eventum.

Can let me know what information I can provide? 

Thank you.

**Comment by glensc** [comment]
as you said nothing changed in your system, so it's clearly related to the input, i.e the email that is being sent. so you need to debug yourself the php code to figure out why it fails. as you did not report from what version you upgraded, it's really shooting into water what the breaking change was, but likely it was replacing pear classes with zend classes, see changelog file.
