### ISSUE TITLE
release 3.2.2

### ISSUE THREAD

**Issue by glensc** [eventum/eventum#283]
https://github.com/eventum/eventum/pull/254#issuecomment-317543071

> @balsdorf i also wish you do the last 3.2 release, to see the validity of docs and maybe some ideas/issues you encounter! :)

- [x] merge #280 (@balsdorf)
- [x] make release (@balsdorf)

**Comment by balsdorf** [comment]
FYI, I see this and will try to take care of it over the weekend / early next week.

**Comment by balsdorf** [comment]
@glensc I'm not sure how to update the translation keywords?
```
- update translation keywords to launchpad
this should be done day before release so launchpad cron would update .po files.
```

Testing snapshot looks good so far.

**Comment by glensc** [comment]
`make pot` should do it

**Comment by glensc** [comment]
which snapshot? i don't see you made fresh snapshot:
https://github.com/eventum/eventum/releases/tag/snapshot

seems to be from May 20

`make snapshot` to make travis  build one.

**Comment by balsdorf** [comment]
I did run `make snapshot`, if you look at the commit for the snapshot it points to feda838, the latest. Not sure why the description didn't update. 

Do I need to delete the old snapshot before running that command?

**Comment by glensc** [comment]
seems github currently shows tag creation date, so added date to the tag message 4b590fcf7

no need to delete existing tag.

**Comment by balsdorf** [comment]
Thanks. I'll wait till tomorrow for Launchpad to update the .po files and continue on with the process.

**Comment by glensc** [comment]
seems the part skipped bzr push, because it pushes to my account.
and there's no automatic git->bzr sync anymore.

last time i checked they did not have translations support for git repos.
and not sure can i add more pushers to my repo.

pushed myself now

```
make[1]: Leaving directory '/home/glen/scm/eventum/eventum/localization'
# push to bzr if "po" directory exists
if test -d po; then \
        test -d po/.bzr && (cd po && bzr pull); \
        cp -p localization/*.pot po/localization; \
        test -d po/.bzr && (cd po && bzr commit -m "update .pot" && bzr push); \
fi
Using saved parent location: bzr+ssh://bazaar.launchpad.net/~glen666/eventum/po/
No revisions or tags to pull.                                                                                                 
Committing to: /home/glen/scm/eventum/po/                                                                                     
modified localization/eventum.pot
Committed revision 4421.                                                                                                      
Using saved push location: bzr+ssh://bazaar.launchpad.net/~glen666/eventum/po/
Pushed up to revision 4421.
```

**Comment by balsdorf** [comment]
So I messed up / ran into a few problems.

I accidentally pushed all local tags I had instead of just 3.2.2 (I am adding the correct command to the release doc). They were all the duplicate release-XXX-final and I've removed them.

I signed v3.2.2 with the wrong gpg key so I had to remove it and re-push

**Comment by balsdorf** [comment]
Okay I think I've done everything, please review and give feedback.

I have updated the release howto, but will wait till you approve everything before I commit and push.

**Comment by glensc** [comment]
seems you cleaned up after your mess. all looks fine. great job!

however, as i guessed you forgot to tag and push wiki repo and `docs/wiki` submodule reference pointer :)

one thing i noticed, that the tag was created by with my identity from travis:

`@glensc glensc released this 10 hours ago · 1 commit to master since this release`

i can't upgrade my production right now, because i'm behind two releases (need to update workflow project) :)

**Comment by balsdorf** [comment]
Ah yes, meant to ask you about that. I ran the commands from the doc, but wasn't sure what happened:

```
$ git submodule update
$ cd docs/wiki/
$ git fetch origin
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ cd ../..
$ git commit -am 'updated wiki submodule'
```
and

```
$ cd docs/wiki/
$ git tag v3.2.2
bryan@odin:wiki$ git push origin v3.2.2
Everything up-to-date
```

I haven't worked with submodules before so I wasn't sure if anything was wrong or how to verify this. Let me know so I can perform the action and document in the howto

**Comment by glensc** [comment]
i can only  guess that docs/wiki is not submodule for you, `git remote -v` shows main git repo not wiki?

`git submodule init` to initialize submodules

**Comment by glensc** [comment]
@balsdorf can you finish this up and merge #254? i believe it's complete? and then 3.2.3 milestone can be deleted instead?

**Comment by balsdorf** [comment]
Sorry, we have had a little [distraction here](http://www.bbc.com/news/world-us-canada-41074919)

I've pushed the wiki changes, now, do we need to generate a new tarball or anything else?

I'll handle #254 and update everything for 3.3.0 as our next release.

**Comment by glensc** [comment]
no need for new tarball. it's already fine there.
