### ISSUE TITLE
'Uncaught Exception SmartyException ' while visting Administration -> Customize Status Action Dates

### ISSUE THREAD

**Issue by timjohnshon2017** [eventum/eventum#285]
Installed Eventum 3.2.2 on Linux environment.
PHP version - 5.5 
MYSQL - 5.5 
I get a blank page while visiting the following tab 
Administration -> Customize Status Action Dates in Default Project .
On turning error_reporting the following error is shown : 
Fatal error: Uncaught -->Smarty : Unable to load template 'file:manage/status_action_date.tpl.html' at 
/home/mydir/public_html/event82/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:185.

What could be causing this possible  issue?.I am attaching copy of the error log with this for your reference .

[eventum.txt](https://github.com/eventum/eventum/files/1259924/eventum.txt)

**Comment by glensc** [comment]
indeed, @balsdorf forgot to add the file in #277?

```
$ git ls-files|grep status_action_date
htdocs/manage/status_action_date.php
templates/help/status_action_date.tpl.html

$ git show -s HEAD
commit 071b5c494dc630460dd633b603ebc160cfc161ba (HEAD -> master, upstream/master, upstream/HEAD)
Author: Bryan Alsdorf <bryan@mariadb.com>
Date:   Thu Aug 24 16:04:12 2017 -0500

    3.2.3-dev
```

**Comment by balsdorf** [comment]
/me hangs head in shame

Sorry about that!

**Comment by glensc** [comment]
@balsdorf nothing to shame. happens.

perhaps lesson for future: you should had tested it elsewhere where you made commits from.

however, please make new release containing the fix.

**Comment by timjohnshon2017** [comment]
@balsdorf : Thanks for the fix .It's working absolutely fine now .
