### ISSUE TITLE
Problem installing Font Awesome within composer?

### ISSUE THREAD

**Issue by infracritical** [eventum/eventum#293]
I get the following error message:

www-data@server:~/html$ **php ./composer.phar install**
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 7 installs, 0 updates, 0 removals
  - Installing fortawesome/font-awesome (4.7.0): Downloading (100%)

  **[UnexpectedValueException]
  phar error: "/var/www/html/vendor/fortawesome/font-awesome/8197468a33164b28
  b6c3efaf29528464.gz" is a corrupted tar file (checksum mismatch of file "52
   comment=a8386aae19e200ddb0f6845b5feeee5eb7013687
  ")**

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

===

Ideas anyone?  What step did I miss?

**Comment by infracritical** [comment]
BTW, am running Ubuntu 14.04.5, 64-bit version.

**Comment by infracritical** [comment]
I temporarily removed the font-awesome entry within the "composer.json" file to determine if it was only that package, or included others.  It was *only* the Font Awesome package.

**Comment by glensc** [comment]
use release tarballs, unless you're developing eventum.

**Comment by glensc** [comment]
looks like you did get corrupted file. i can't figure out heads or tails of your error. please edit your post and ensure all output is there, not truncated by line wrapping or anything. and also use markdown codeblock for such pastes. or upload output as .txt file.

tested locally, and i get proper file with proper sha1 checksum:

```
➔ wget https://github.com/FortAwesome/Font-Awesome/archive/v4.7.0.tar.gz
--2017-09-19 22:17:49--  https://github.com/FortAwesome/Font-Awesome/archive/v4.7.0.tar.gz
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/FortAwesome/Font-Awesome/tar.gz/v4.7.0 [following]
--2017-09-19 22:17:49--  https://codeload.github.com/FortAwesome/Font-Awesome/tar.gz/v4.7.0
Resolving codeload.github.com (codeload.github.com)... 192.30.253.121, 192.30.253.120
Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2672776 (2,5M) [application/x-gzip]
Saving to: ‘v4.7.0.tar.gz’

v4.7.0.tar.gz                   100%[======================================================>]   2,55M   448KB/s    in 6,9s

2017-09-19 22:17:57 (380 KB/s) - ‘v4.7.0.tar.gz’ saved [2672776/2672776]

➔ sha1sum v4.7.0.tar.gz
7a94b1800202e20c382d9847cdf51e8d1c106b7e  v4.7.0.tar.gz

```

and that is the checksum in eventum composer satis repository:
```
 ➔ curl -s https://eventum.github.io/composer/all.json|grep 7a94b1800202e20c382d9847cdf51e8d1c106b7e
                    "shasum": "7a94b1800202e20c382d9847cdf51e8d1c106b7e"
```
and you should probably run composer install with -vvv option, and maybe even report it  to composer, not eventum.

**Comment by cpinfold** [comment]
It may also have been corrupted while in transit to you.  Possibly try
again ensuring any composer cache is cleared?  `composer clear-cache`

Craig.

**Comment by infracritical** [comment]
OK...this is what I got after running the command

```hp ./composer.phar install -vvv```

within **/var/www/html** as **www-data**

===

Downloading http://packagist.org/p/pear/net_ldap2%24cbc213db488dfed85c05badf196dc4fa0ec3738de3b7085954f7e892cba2da2e.json

Writing /var/www/.cache/composer/repo/https---packagist.org/provider-pear$net-ldap2.json into cache

Downloading http://packagist.org/p/rsky/pear-core-min%24b66d4b2b04252ffeb217f94fe1d6d78c89a543ebae1b7b7fcee48ad5aa877be9.json

Writing /var/www/.cache/composer/repo/https---packagist.org/provider-rsky$pear-core-min.json into cache

Downloading http://packagist.org/p/phpunit/phpunit%24443734a1a95b069404dbace73b86b77087a1468cb6bddbd5bc405a8285d3486b.json

Writing /var/www/.cache/composer/repo/https---packagist.org/provider-phpunit$phpunit.json into cache

Downloading http://packagist.org/p/raven/raven%24ef2cd04aadd63c69b3a29900f6ffe9f9481fd5a64a695a0738b468ea184116d0.json

Writing /var/www/.cache/composer/repo/https---packagist.org/provider-raven$raven.json into cache

Resolving dependencies through SAT

Dependency resolution completed in 0.439 seconds

Analyzed 15483 packages to resolve dependencies

Analyzed 60000 rules to resolve dependencies

Resolving dependencies through SAT

Dependency resolution completed in 0.002 seconds

Package operations: 1 install, 0 updates, 0 removals

Installs: fortawesome/font-awesome:4.7.0

  - Installing fortawesome/font-awesome (4.7.0): Downloading https://github.com/FortAwesome/Font-Awesome/archive/v4.7.0.tar.gz

Downloading (connecting...)

Following redirect (2) https://codeload.github.com/FortAwesome/Font-Awesome/tar.gz/v4.7.0

DoDownloading (100%)Writing /var/www/.cache/composer/files/fortawesome/font-awesome/ae34fdf0510846a1494fb62b0db3210b7ee41723.tar into cache from /var/www/html/vendor/fortawesome/font-awesome/ac152636850de4f00dfa27d35bb0bca3.gz

 

Extracting archive

 

  [UnexpectedValueException]

  phar error: "/var/www/html/vendor/fortawesome/font-awesome/ac152636850de4f0

  0dfa27d35bb0bca3.gz" is a corrupted tar file (checksum mismatch of file "52

   comment=a8386aae19e200ddb0f6845b5feeee5eb7013687

  ")

 

 

Exception trace:

() at phar:///var/www/html/composer.phar/src/Composer/Downloader/TarDownloader.php:28

PharData->__construct() at phar:///var/www/html/composer.phar/src/Composer/Downloader/TarDownloader.php:28

Composer\Downloader\TarDownloader->extract() at phar:///var/www/html/composer.phar/src/Composer/Downloader/ArchiveDownloader.php:43

Composer\Downloader\ArchiveDownloader->download() at phar:///var/www/html/composer.phar/src/Composer/Downloader/DownloadManager.php:213

Composer\Downloader\DownloadManager->download() at phar:///var/www/html/composer.phar/src/Composer/Installer/LibraryInstaller.php:186

Composer\Installer\LibraryInstaller->installCode() at phar:///var/www/html/composer.phar/src/Composer/Installer/LibraryInstaller.php:90

Composer\Installer\LibraryInstaller->install() at phar:///var/www/html/composer.phar/src/Composer/Installer/InstallationManager.php:173

Composer\Installer\InstallationManager->install() at phar:///var/www/html/composer.phar/src/Composer/Installer/InstallationManager.php:160

Composer\Installer\InstallationManager->execute() at phar:///var/www/html/composer.phar/src/Composer/Installer.php:587

Composer\Installer->doInstall() at phar:///var/www/html/composer.phar/src/Composer/Installer.php:223

Composer\Installer->run() at phar:///var/www/html/composer.phar/src/Composer/Command/InstallCommand.php:119

Composer\Command\InstallCommand->execute() at phar:///var/www/html/composer.phar/vendor/symfony/console/Command/Command.php:266

Symfony\Component\Console\Command\Command->run() at phar:///var/www/html/composer.phar/vendor/symfony/console/Application.php:861

Symfony\Component\Console\Application->doRunCommand() at phar:///var/www/html/composer.phar/vendor/symfony/console/Application.php:208

Symfony\Component\Console\Application->doRun() at phar:///var/www/html/composer.phar/src/Composer/Console/Application.php:245

Composer\Console\Application->doRun() at phar:///var/www/html/composer.phar/vendor/symfony/console/Application.php:127

Symfony\Component\Console\Application->run() at phar:///var/www/html/composer.phar/src/Composer/Console/Application.php:100

Composer\Console\Application->run() at phar:///var/www/html/composer.phar/bin/composer:54

require() at /var/www/html/composer.phar:24

 

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

**Comment by infracritical** [comment]
If I were to place a different version of font-awesome, where would I place it to re-run composer.phar?

**Comment by cpinfold** [comment]
You can change version in composer.json - although 4.7.0 is the latest.

Is this your composer.json file:
https://github.com/eventum/eventum/blob/master/composer.json

@glensc - wouldn't composer load from https://eventum.github.io/composer/ using
the default composer.json file?

Craig.

**Comment by cpinfold** [comment]
I was able to pull down 4.7 on my machine without issue.. a few things to
try:

1) /path/to/composer.phar selfupdate
Should update to 1.5.2
2) create a new empty directory, go into it and execute:
/path/to/composer.phar require fortawesome/font-awesome
3) Try a different computer in case there is another issue.

Craig.

**Comment by glensc** [comment]
@infracritical please fix your output paste as requested. ensure it is identical with your terminal output. i find it hard to believe there's spaces and newlines as you pasted:

```
(checksum mismatch of file "52

   comment=a8386aae19e200ddb0f6845b5feeee5eb7013687
  "
```

**Comment by glensc** [comment]
@cpinfold we do not use packagist version:
https://github.com/eventum/composer/commit/fbe0670e15c07a7ad8bf4cb4055b8841b6baee6f

so therefore to test from scratch should run composer init with repository parameter, and better [disable packagist.org](https://getcomposer.org/doc/05-repositories.md#disabling-packagist-org
) to isolate problem closer

```
mkdir test
cd test
composer init --repository=https://eventum.github.io/composer/
composer config repo.packagist false
composer clear-cache
composer require fortawesome/font-awesome=^4.7 -vvv
```

**Comment by glensc** [comment]
also given the output, there's something wrong with your php or your firewall.
try to download the tarball, check it's checksum and extract it using php phar:

```
wget https://github.com/FortAwesome/Font-Awesome/archive/v4.7.0.tar.gz
sha1sum v4.7.0.tar.gz
php -r '$archive = new PharData("v4.7.0.tar.gz"); $archive->extractTo("test-extract", null, true);'
```

the above code is used by composer to extract the download:
https://github.com/composer/composer/blob/1.5.2/src/Composer/Downloader/TarDownloader.php#L28-L29

**Comment by infracritical** [comment]
Honestly, with how I am using Eventum, I don't really need Font Awesome.  I am closing this issue; if at all, I can re-open it if you gents think that this is worth addressing.

**Comment by glensc** [comment]
@infracritical for the future sake, please run the commands i wrote in last comments (and share output).

this one first:
https://github.com/eventum/eventum/issues/293#issuecomment-330906029

and if it succeeds, then the previous one as well:
https://github.com/eventum/eventum/issues/293#issuecomment-330903678

i think you might have hit bug in composer package!

**Comment by balsdorf** [comment]
So I hit this bug. 

```
wget https://github.com/FortAwesome/Font-Awesome/archive/v4.7.0.tar.gz
sha1sum v4.7.0.tar.gz
php -r '$archive = new PharData("v4.7.0.tar.gz"); $archive->extractTo("test-extract", null, true);'
```
worked correctly, no problem.

But the other commands failed with this output:
```
composer require fortawesome/font-awesome=^4.7 -vvv
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/tmp/test): git branch --no-color --no-abbrev -v
Executing command (/tmp/test): git describe --exact-match --tags
Executing command (/tmp/test): git log --pretty="%H" -n1 HEAD
Executing command (/tmp/test): hg branch
Executing command (/tmp/test): fossil branch list
Executing command (/tmp/test): fossil tag list
Executing command (/tmp/test): svn info --xml
Failed to initialize global composer: Composer could not find the config file: /var/www/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 1.5.2 (2017-09-11 16:59:25) with PHP 5.5.9-1ubuntu4.21 on Linux / 3.2.0-60-generic
./composer.json has been updated
Reading ./composer.json
Loading config file ./composer.json
Executing command (/tmp/test): git branch --no-color --no-abbrev -v
Executing command (/tmp/test): git describe --exact-match --tags
Executing command (/tmp/test): git log --pretty="%H" -n1 HEAD
Executing command (/tmp/test): hg branch
Executing command (/tmp/test): fossil branch list
Executing command (/tmp/test): fossil tag list
Executing command (/tmp/test): svn info --xml
Failed to initialize global composer: Composer could not find the config file: /var/www/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Loading composer repositories with package information
Downloading https://eventum.github.io/composer/packages.json

Using www.github.com as CN for subjectAltName enabled host eventum.github.io:443
Downloading https://eventum.github.io/composer/packages.json
Writing /var/www/.cache/composer/repo/https---eventum.github.io-composer/packages.json into cache
Reading /var/www/.cache/composer/repo/https---eventum.github.io-composer/all.json from cache
Downloading https://packagist.org/packages.json
Writing /var/www/.cache/composer/repo/https---packagist.org/packages.json into cache
Updating dependencies (including require-dev)
Reading /var/www/.cache/composer/repo/https---packagist.org/p-provider-2013.json from cache
Reading /var/www/.cache/composer/repo/https---packagist.org/p-provider-2014.json from cache
Reading /var/www/.cache/composer/repo/https---packagist.org/p-provider-2015.json from cache
Reading /var/www/.cache/composer/repo/https---packagist.org/p-provider-2016.json from cache
Reading /var/www/.cache/composer/repo/https---packagist.org/p-provider-2017-01.json from cache
Reading /var/www/.cache/composer/repo/https---packagist.org/p-provider-2017-04.json from cache
Downloading http://packagist.org/p/provider-2017-07%24cf324b1162d6c295e40a019b9f02ce575484c2d8b6a42cf6dbbc2840b5f6611c.json
Writing /var/www/.cache/composer/repo/https---packagist.org/p-provider-2017-07.json into cache
Reading /var/www/.cache/composer/repo/https---packagist.org/p-provider-archived.json from cache
Downloading http://packagist.org/p/provider-latest%2420c8d5e5a6ca38ae363537642ab33da8d10f1ba1016b90535bc5f8f5bc6a071b.json
Writing /var/www/.cache/composer/repo/https---packagist.org/p-provider-latest.json into cache
Reading /var/www/.cache/composer/repo/https---packagist.org/provider-fortawesome$font-awesome.json from cache
Resolving dependencies through SAT
Dependency resolution completed in 0.001 seconds
Analyzed 161 packages to resolve dependencies
Analyzed 64 rules to resolve dependencies
Package operations: 1 install, 0 updates, 0 removals
Installs: fortawesome/font-awesome:4.7.0
  - Installing fortawesome/font-awesome (4.7.0): Downloading https://github.com/FortAwesome/Font-Awesome/archive/v4.7.0.tar.gz
Downloading (connecting...)
Following redirect (2) https://codeload.github.com/FortAwesome/Font-Awesome/tar.gz/v4.7.0
Downloading https://codeload.github.com/FortAwesome/Font-Awesome/tar.gz/v4.7.0
Downloading (100%)Writing /var/www/.cache/composer/files/fortawesome/font-awesome/ae34fdf0510846a1494fb62b0db3210b7ee41723.tar into cache from /tmp/test/vendor/fortawesome/font-awesome/f10c6fb96ef1b117c82eda383d42ca3b.gz

 Extracting archive
Installation failed, reverting ./composer.json to its original content.

                                                                                                                                                                                                       
  [UnexpectedValueException]                                                                                                                                                                           
  phar error: "/tmp/test/vendor/fortawesome/font-awesome/f10c6fb96ef1b117c82eda383d42ca3b.gz" is a corrupted tar file (checksum mismatch of file "52 comment=a8386aae19e200ddb0f6845b5feeee5eb7013687  
  ")                                                                                                                                                                                                   
                                                                                                                                                                                                       

Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Downloader/TarDownloader.php:28
 PharData->__construct() at phar:///usr/local/bin/composer/src/Composer/Downloader/TarDownloader.php:28
 Composer\Downloader\TarDownloader->extract() at phar:///usr/local/bin/composer/src/Composer/Downloader/ArchiveDownloader.php:43
 Composer\Downloader\ArchiveDownloader->download() at phar:///usr/local/bin/composer/src/Composer/Downloader/DownloadManager.php:213
 Composer\Downloader\DownloadManager->download() at phar:///usr/local/bin/composer/src/Composer/Installer/LibraryInstaller.php:186
 Composer\Installer\LibraryInstaller->installCode() at phar:///usr/local/bin/composer/src/Composer/Installer/LibraryInstaller.php:90
 Composer\Installer\LibraryInstaller->install() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:173
 Composer\Installer\InstallationManager->install() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:160
 Composer\Installer\InstallationManager->execute() at phar:///usr/local/bin/composer/src/Composer/Installer.php:587
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:223
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/RequireCommand.php:180
 Composer\Command\RequireCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:266
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:861
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:208
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:245
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:127
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:54
 require() at /usr/local/bin/composer:24

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

```

I'm going to re-open this and report to composer

**Comment by balsdorf** [comment]
Never mind, I'm going to go ahead and close this. I was running the commands that worked on a machine with 5.6 and the accidently running the invalid commands on a machine running 5.5. So this appears to be a bug in php 5.5, which is no longer supported.
