### ISSUE TITLE
PHP 7.1 Support

### ISSUE THREAD

**Issue by balsdorf** [eventum/eventum#299]
This is a placeholder issue to track adding support for PHP 7.1 to Eventum. 

Personally I've run Eventum on PHP 7.1 and only noticed a few problems, but these need to be fixed before we can provide official support.

**Comment by glensc** [comment]
to me goal is dropping pear packages. #263 for example.

i haven't been able to test that branch anymore due the attachments PR.

**Comment by glensc** [comment]
PR: #426

**Comment by glensc** [comment]
Eventum 3.6.0 requires php 7.1: https://github.com/eventum/eventum/pull/426; closing issue.
