### ISSUE TITLE
3.3.0 release

### ISSUE THREAD

**Issue by glensc** [eventum/eventum#300]
- [x] update min php requirement to 5.6.0 (@balsdorf)
- [x] some docs how to upgrade (does one need extra disk space or not, or how to estimate needed disk space). #254

**Comment by balsdorf** [comment]
Disk space question is a good one. I'll do some tests and let you know.

**Comment by glensc** [comment]
there are two kind of disk requirements:
- uprading 3.2.3 -> 3.3.0
- migrating from one storage type to another

in this issue scope, only the first one is interesting

**Comment by balsdorf** [comment]
For upgrading from 3.2.3 -> 3.3.0 there should be no additional disk space required. The upgrade process just adds the new tables and columns but leaves existing attachments in the current table. New attachments will be inserted into the new table but unless you run `migrate_storage_adapter.php` it won't move anything.

**Comment by glensc** [comment]
thanks for the info! i'll copy that to original PR too. should we add something to changelog.md too or as nothing special, not necessary?

**Comment by glensc** [comment]
i think i'll roll out 3.3.0 release, today-tomorrow, unless @balsdorf want to do that yourself.

**Comment by balsdorf** [comment]
Nothing is needed in changelog.md regarding disk space, but not sure if we want to add text letting people know they can switch to a different adapter? I'm undecided as I view this as an advanced feature that most people won't need so I don't know if we want to advertise it. I went ahead and added a [new page in the wiki](https://github.com/eventum/eventum/wiki/Attachments) regarding it. Think this is good enough or we should advertise it in the changelog?

And please go ahead with the release when you can.

**Comment by phavel** [comment]
On the contrary, it is a important function.
I'm waiting for it and I am happy it will be released. My MySQL storage on a web host is already full because of attachments.

Thanks for the function!

**Comment by balsdorf** [comment]
@phavel I'm not worried about people like you who are reading these PRs! :) Once you try it out let me know any feedback you have, updated docs are appreciated as well.

**Comment by glensc** [comment]
@balsdorf damn, your analyze is wrong! EventumAttachments does alter on issue_attachment and issue_attachment_file tables! meaning there's need for double of those tables size!

**Comment by glensc** [comment]
@balsdorf how you propose to solve this, add the new column of `issue_attachment_file` table to some new table perhaps instead?

**Comment by balsdorf** [comment]
What version of MySQL are you using and what engine?

For InnoDB newer than 5.6 it table adds / drops are handled INPLACE. For
MyISAM, yeah it is going to be locked and copied.

I read the docs and this is why I said it would not take additional disk
space. I did not have a pre-release database available for testing.

After your email I got a fresh snapshot of our live DB (pre-release) and
applied the upgrade I saw that disk space was being used and spoke with our
senior support staff. "INPLACE" for InnoDB means that the while the table
is available during the alter it is still copied.

Where does this leave us? If we need to avoid altering the
issue_attachment_file table then yes, we will need to add a new table, say
issue_attachment_path that contains the path. I can start working on this
tonight.

Sorry for not doing a complete test before I gave you the disk usage info,
I read the docs and made an incorrect assumption.

**Comment by balsdorf** [comment]
I've made the changes and submitted #302 . I'd like to do more testing tomorrow, but all my current testing looks good, including migrating data.

**Comment by glensc** [comment]
@balsdorf InnoDB is not supported in Eventum, it's default is still MyISAM. If you have it as InnoDB it's your own hack and you likely need to convert every new table manually :).

altho with introducing phinx migration tool, we could easily make engine configurable. i haven't done that myself because i still use MyISAM. i don't have viable replication/backup/restore plan using InnoDB, using mysqldump is rather lame solution. for MyISAM i use mysqlhotbackup via [bacula-backup-mysql](https://github.com/glensc/bacula-backup-mysql) on slave instance.

would like to solve that problem first before looking into InnoDB.

**Comment by balsdorf** [comment]
Hah, sometimes I forget that people have other environments than I do. InnoDB is faster and safer (and now supports fulltext which was the reason we used to stay on MyISAM. Maybe with 4.0.0 we change the default to InnoDB. I'll ask our team what they recommend for InnoDB backups for you.

**Comment by balsdorf** [comment]
[Xtrabackup](https://www.percona.com/doc/percona-xtrabackup/LATEST/how_xtrabackup_works.html) is what my team recommends.
Personally we are using LVM Snapshots on one slave and mydumper on the other.

**Comment by phavel** [comment]
> Once you try it out let me know any feedback you have, updated docs are appreciated as well.

Sorry, now I can't try it (development version), but I am looking forward to production version.

**Comment by glensc** [comment]
upgraded my production with [snapshot](https://github.com/eventum/eventum/releases/tag/snapshot) build. [eventum-3.2.3-189-g7b4eddae.tar.gz](https://github.com/eventum/eventum/releases/download/snapshot/eventum-3.2.3-189-g7b4eddae.tar.gz) to be exact.

looks fine, so making release now.

**Comment by glensc** [comment]
[v3.3.0](https://github.com/eventum/eventum/releases/tag/v3.3.0) released

**Comment by glensc** [comment]
@balsdorf another issue with attachments. the upgrade was supposed not to require filesystem storage. i.e everything is still stored to database.

however it gives me error:
```

root@eventum ~/eventum# /tmp/eventum.phar add-att 62998 sync-20171008.log -i

                                                                              
  [Eventum_RPC_Exception]                                                     
  Impossible to create the root directory "/usr/share/eventum/var/storage/".  
                                                                              

add-attachment [-f|--filename FILENAME] [-m|--mimetype MIMETYPE] [-d|--description DESCRIPTION] [-i|--internal] [--] <issue_id> <file>
```

**Comment by glensc** [comment]
need to release 3.3.1 due #305

**Comment by balsdorf** [comment]
Was the issue with being unable to create the root storage directory solved by #305?

**Comment by glensc** [comment]
unable to create root directory error happened because there were no filesystem permissions. what i had in mind, i did not expect filesystem driver being used out of the box. that was my issue.

not sure if that needs to be fixed, i.e if the fix is going to make code too complex, it's not worth of it. in my system i granted the write permission. the dir is left empty with new attachment uploads, so it's not filled, but the unused driver initialization failed.

**Comment by balsdorf** [comment]
So the tarball contains the default storage directory so I'm not sure why
you are seeing that error. However, it is an easy fix. I'll add it to my
todo.

**Comment by glensc** [comment]
seems you still did not get my confusion.

1. from #254 i understood all will work the same for default upgrade path: using db only storage
2. but still "local" backend is configured (thus the error i got)

but as you're not going to do about it in short term, i'm going to release 3.3.1 now.
