### ISSUE TITLE
Problem with translation on Launchpad

### ISSUE THREAD

**Issue by phavel** [eventum/eventum#309]
In Launchpad Translations miss translation strings, which was added to code in Eventum approximately in the last year. It is not possible to do translations.

For example, new strings in #222 are not in Launchpad.

**Comment by glensc** [comment]
please be specific, which string is missing? and what language?

**Comment by phavel** [comment]
Missing a lot of strings, for example:

- [Issue closed comments](https://translations.launchpad.net/eventum/trunk/+pots/eventum/cs/+translate?batch=10&show=all&search=Issue+closed+comments)
- Customer Action
- Time Added
- File Uploaded
- Draft Saved
- Staff Response
- Customer Action
- Phone Call
- User Response
- SCM Checkin
- Status Change
- File Attached
- [#%1$s] New Issue Assigned: %2$s
- [#%1$s] New Assignment: %2$s
- Never Display
- Individual
- Remove this filter
- Users can set this on their preferences page. This provides the default for new users.
- This address will be notified when issues are created with this product.

and more.

I translate into Czech, but the strings are also missing in other languages (found randomly).

**Comment by glensc** [comment]
i see they are present in .pot in github:
- [localization/eventum.pot:3579-3582](https://github.com/eventum/eventum/blob/73f8aa62ad50a6a5a78ccf66bd216a25b032e137/localization/eventum.pot#L3579-L3582)

**Comment by glensc** [comment]
i checked no translations have been made 3.2.0->3.3.0

```
$ diff -ru eventum-3.2.0/localization/ eventum-3.3.0/localization/ -x '*.pot' -x '*.mo' -I 'X-*'  | wc -l
0
```

**Comment by glensc** [comment]
the earliest changes to translation i see are from 3.1.9:

```
➔ diff -ru eventum-3.1.9/localization/ eventum-3.1.10/localization/ -x '*.pot' -x '*.mo' -I 'X-*'  |lsdiff
eventum-3.1.9/localization/cs.po
eventum-3.1.9/localization/de.po
```

3.1.9 was released on 2017-01-10, so seems something changed in launchpad since then.

**Comment by glensc** [comment]
uploaded .pot manually to https://translations.launchpad.net/eventum/trunk/+pots/eventum/+upload
progress can be tracked here: https://translations.launchpad.net/eventum/trunk/+imports

but perhaps should look into different translations provider than launchpad, not sure if they still lack translations integration with git repos.

**Comment by phavel** [comment]
Great. After manually import is in Launchpad 196 new untranslated items.

**Comment by glensc** [comment]
always useful to enrich your notes with a link!
