### ISSUE TITLE
delete note broken since 3.3.0

### ISSUE THREAD

**Issue by glensc** [eventum/eventum#312]
seems code still contains references to `iat_status` column even it was dropped in #254.

```
[2017-10-10 15:26:48] app.ERROR: Uncaught Exception
Eventum\Db\DatabaseException: "SQLSTATE[42S22]: Column not found: 1054
Unknown column 'iat_status' in 'where clause'" at
/usr/share/eventum/src/Db/Adapter/PdoAdapter.php line 159
{"exception":"[object] (Eventum\\Db\\DatabaseException(code: 42S22):
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'iat_status' in
'where clause' at
/usr/share/eventum/src/Db/Adapter/PdoAdapter.php:159,
PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054
Unknown column 'iat_status' in 'where clause' at
/usr/share/eventum/src/Db/Adapter/PdoAdapter.php:157)"}
{"url":"/popup.php?cat=delete_note&id=169028"}
```

/cc @balsdorf

**Comment by glensc** [comment]
btw, the note itself was deleted, but it's accessible if you know note id.

**Comment by balsdorf** [comment]
I've pushed a fix but there is more to discuss regarding viewing "deleted" notes. You have been able to view deleted notes by entering the ID manually (if you have permission to view the issue and role).

"Deleting" notes just marks them as removed in the database and doesn't show them in the list. They aren't really gone. I believe this is done so if we are downloading notes the not_message_id is still stored and duplicate messages aren't displayed. 

Do we want to solve this as part of this bug or open another issue? I see two possible solutions.

**Comment by glensc** [comment]
i've known this "feature" already, but not sure what to do with the deleted notes. it sure is inconsistent, when rest of the stuff is deleted, not hidden.

perhaps just leave comment in code to your comment why it's not actually deleted, then can figure out this later (check your thought)
