### ISSUE TITLE
Priority Automatically Set to Urgent

### ISSUE THREAD

**Issue by tugrulcan** [eventum/eventum#318]
Hi, 
When we want to update an issue, Priority section automatically sets as"Urgent". 
Is this a feature? If so, is there any option to switch it off? If not, how can I find a guide book to contribute this repo? 

Best,
Tuğrul.

**Comment by glensc** [comment]
there's no special requirements for contributing: [CONTRIBUTING.md](https://github.com/eventum/eventum/blob/master/CONTRIBUTING.md#pull-requests)
you may just search for general github contributing guidelines if you're new to github.

as for your problem, you forgot to report version and environment details and how to reproduce. have you tried to reproduce yourself in fresh and latest version? i don't even have priority `Urgent`, could be your customization ahead or workflow method.

**Comment by tugrulcan** [comment]
@glensc Thanks for quick answer. 

>  i don't even have priority Urgent, could be your customization ahead or workflow method.
Probably it's because our internal infastructure has been customized as you mentioned. I'll get in touch with them.
