### ISSUE TITLE
closed issues not formatted as strike-trough 

### ISSUE THREAD

**Issue by glensc** [eventum/eventum#33]
the closed issues used to be displayed as strike-trough in 2.3, it seems to be not working in current master `v3.0.0-pre1-19-g7e2ab9c` (7e2ab9c)

**Comment by glensc** [comment]
partial fixes in 02a7376, 8f515f2c by @balsdorf

**Comment by glensc** [comment]
more fixes: 07e98a1

also some line comments:
https://github.com/eventum/eventum/commit/07e98a133b443c939011a0f39b0f07f3280be805#commitcomment-10325048
https://github.com/eventum/eventum/commit/07e98a133b443c939011a0f39b0f07f3280be805#commitcomment-10325053

**Comment by glensc** [comment]
added test so could test all expected links 0eb5cc5

**Comment by balsdorf** [comment]
Responded to line comments. I did this rather poorly it seems. Instead of me arbitrarily changing the pattern we should decide what we want to match and figure out a bug free solution..
I personally only care about "#1234" and maybe "issue #1234". Do you want anything else to match besides that?

**Comment by glensc** [comment]
i've always used "issue 123" (since 1.4 or so). some here use "Issue 123" and "Issue #123"

so why you suddenly want "#123", it was never supported? in our system #123 is ambiguous, could be trac ticket, could be eventum issue, and so on. and you did that in completely unrelated commit (fixing issues underlining problem, rather unexpected)

**Comment by glensc** [comment]
reverted link changes ad2039282f59014a6f76a5809777d5831e8c6d98
looks ok otherwise
