### ISSUE TITLE
Error after upgrade from 3.1.10 to 3.2.0

### ISSUE THREAD

**Issue by TexasGitHubber** [eventum/eventum#340]
My goal is to get to version 3.3.4 from 3.1.8.  The upgrade from 3.1.8 to 3.1.10 was successful.

However, after installing the 3.2.0 and the php PDO extension, I'm not able to run the program.

The var/log/eventum.log shows errors like these:

`[2018-01-23 22:24:08] app.ALERT: Fatal Error (E_COMPILE_ERROR): Cannot redeclare class Abstract_Workflow_Backend {"code":64,"message":"Cannot redeclare class Abstract_Workflow_Backend","file":"/var/www/html/eventum/config/workflow/class.abstract_workflow_backend.php","line":21} {"file":null,"line":null,"class":null,"function":null,"memory_usage":"2.5 MB","memory_peak_usage":"2.5 MB","version":"3.2.1","usr_id":""}
`

Any help and ideas would be greatly appreciated.

Thanks!

**Comment by balsdorf** [comment]
Did you see the instructions [here](https://github.com/eventum/eventum/wiki/Upgrading)? 3.2.0 has some special steps if you have workflow or customer backends.

**Comment by TexasGitHubber** [comment]
I don't use the workflow and/or customer backends.

I did see that the database encoding was set to latin1 and updated it using the convert-utf8.php script.  The results were as follows:

```
PHP Warning:  Module 'PDO' already loaded in Unknown on line 0
Performing database changes (1) queries
Done!
```

I checked the DB and see that the encoding seems to be utf8 now:
```

SELECT default_character_set_name FROM information_schema.SCHEMATA 
WHERE schema_name = "eventum";

```
When I follow the directions to go from 3.1.10 to 3.2.0, I get the following during upgrade.php:

```
php bin/upgrade.php
PHP Warning:  Module 'PDO' already loaded in Unknown on line 0
PHP Fatal error:  Cannot redeclare class Abstract_Workflow_Backend in /var/www/html/eventum/config/workflow/class.abstract_workflow_backend.php on line 21
app.ALERT: Fatal Error (E_COMPILE_ERROR): Cannot redeclare class Abstract_Workflow_Backend {"code":64,"message":"Cannot redeclare class Abstract_Workflow_Backend","file":"/var/www/html/eventum/config/workflow/class.abstract_workflow_backend.php","line":21} {"file":null,"line":null,"class":null,"function":null,"memory_usage":"2.5 MB","memory_peak_usage":"2.5 MB","version":"3.2.0","usr_id":""}
```

Any ideas as to which steps from the instructions I may have missed?  I tried to follow all instructions very carefully.

Thanks!

**Comment by balsdorf** [comment]
Can you show me a directory listing for /var/www/html/eventum/config/ ?

If you don't use the customer backend or workflows I don't think there need to be a workflow directory in config.

**Comment by TexasGitHubber** [comment]
Here is the directory listing of the current 3.1.10 directory:

```
ll -R /var/www/html/eventum/config/
/var/www/html/eventum/config/:
total 68
-rw-rw-rw- 1 root root  2827 Jan 23 16:34 config.dist.php
-rw-rw-rw- 1 root root  4079 Jan 23 16:34 config.php
-rwxr-xr-- 1 root root  4074 Jan 23 16:34 config.php.backup
-rwxr-xr-- 1 root root  4074 Jan 23 16:34 config.php.backup.20110803
-rwxr-xr-- 1 root root  4078 Jan 23 16:34 config.php.backup.20110923
-rw-r--r-- 1 root root  4087 Jan 23 16:34 config.php.backup.20161010
-rw-r--r-- 1 root root  4079 Jan 23 16:34 config.php.backup.20171213
-rwxr-xr-- 1 root root  4074 Jan 23 16:34 config.php_backupyp20151204
drwxrwxrwx 2 root root     6 Apr 20  2017 crm
drwxrwxrwx 2 root root    91 Jan 23 16:34 custom_field
drwxrwxrwx 2 root root     6 Apr 20  2017 include
-rw-rw-rw- 1 root root  2082 Jan 23 16:34 irc_config.dist.php
-rw-r--r-- 1 root root    24 Jan 23 16:34 ldap.php
drwxrwxrwx 2 root root     6 Apr 20  2017 partner
-rw-rw-rw- 1 root root    59 Jan 23 16:34 private_key.php
-rw-rw-rw- 1 root root     0 Jan 23 16:34 secret_key.php
-rwxrwxrwx 1 root root  2324 Jan 23 16:34 setup.php
-rwxr-xr-x 1 root root  2126 Jan 23 16:34 setup.php.backup.20161010
-rwxrwxrwx 1 root root 14205 Jan 23 16:34 sphinx.conf.php
drwxrwxrwx 2 root root     6 Apr 20  2017 templates
drwxrwxrwx 2 root root    48 Jan 23 16:34 workflow

/var/www/html/eventum/config/crm:
total 0

/var/www/html/eventum/config/custom_field:
total 12
-rw-r--r-- 1 root root  603 Jan 23 16:34 class.developer_list.php
-rw-r--r-- 1 root root 3633 Jan 23 16:34 class.dynamic.php
-rw-r--r-- 1 root root  603 Jan 23 16:34 class.reporter_list.php

/var/www/html/eventum/config/include:
total 0

/var/www/html/eventum/config/partner:
total 0

/var/www/html/eventum/config/templates:
total 0

/var/www/html/eventum/config/workflow:
total 24
-rw-r--r-- 1 root root 22829 Jan 23 16:34 class.abstract_workflow_backend.php

```

Are you saying I need to delete the workflow directory?

**Comment by balsdorf** [comment]
Yes, I would delete the workflow directory (and possibly the custom_field directory)

**Comment by TexasGitHubber** [comment]
Thank you!  That did the trick!
