### ISSUE TITLE
Eventum 3.3.4: Attempting to associate email to existing issue results in empty item[] array

### ISSUE THREAD

**Issue by spoollord** [eventum/eventum#341]
Line 60 in src/Controller/AssociateController.php $this->items = $request->request->get('item'); does not get items from the querystring. It continually returns null, causing the email association to an existing issue to error out.

Is anyone else experiencing this or can recommend a workaround?

I can assign a static array, which is then processed by the loop in the templates/associate.tpl.html file. But, I can't see any reason why it's not parsing the querystring.

**Comment by spoollord** [comment]
Disregard bug 2. I found the problem to that one in my config.php file. A switch from http to https was missed. Apologies for that one. Bug 1 remains.

**Comment by glensc** [comment]
what is the reproducer?

perhaps the request is type GET not POST?

patch (as pull request) welcome

**Comment by spoollord** [comment]
I'll have to look at it again later. I've not had time to re-examine. Title edited.
