### ISSUE TITLE
Date field limited for year drop down. Only 4 displayed 2017 to 2020

### ISSUE THREAD

**Issue by cohuser** [eventum/eventum#343]
We have been using Eventum for in house project tracking for some time. It has been working great until now  where we do not have the years prior to 2017 for date field year dropdown. Any ideas as to where we can look for a solution to fix this?

**Comment by balsdorf** [comment]
Which field in specific are you talking about? I can give you a file to edit.

Unfortunately there are multiple places where the date field first year is defined, some going back 10 years some just one year. Not sure why this was done but it can be solved, just need to update a bunch of templates to solve it.

**Comment by cohuser** [comment]
Thank you so much for the prompt response. I was referring to a custom field that was defined as a date field.  All other custom date fields have the same issue.

[cid:image001.png@01D396B1.C0D10D20]



The result on the front end is as below. There is data in the table that has the 2016 value for the date but not displayed anymore.



[cid:image002.png@01D396B3.0A9B7930]

**Comment by balsdorf** [comment]
Sorry for the delay in responding to this. Unfortunately your screenshots did not come through.

Custom date fields should just be a text box with a calendar popup, unless you are running a very old version of Eventum.  In that case, you need to go into the file templates/edit_custom_fields.tpl.html. Look for a line like this:
```
{html_select_date field_array="custom_fields[`$custom_fields[i].fld_id`]" prefix='' all_extra="class=\"default\"" year_empty='' time=$custom_fields[i].value|default:"0000-00-00" display_months=false display_days=false start_year=-1 end_year=+2 year_extra="id=\"custom_field_`$custom_field_id`_year\" tabindex=\"`$tabindex++`\""}
```

And change the "start_year=-1" to something like "start_year=2010" (or whatever you think your earliest year will be).

You can also search for "start_year" throughout all your templates and change them accordingly.

**Comment by cohuser** [comment]
Hello,
Thanks for the tip. I changed the code in the templates folder but do I also change this in the templates_c  folder ? I support  version 2.1.1
Regards,
Niki

**Comment by balsdorf** [comment]
the version in templates_c should automatically be regenerated when the
source file is updated.  If not, you can delete the file in templates_c to
force it to be refreshed.

**Comment by cohuser** [comment]
It worked!
Thank you for the prompt support.
Niki

**Comment by glensc** [comment]
attachments need to be uploaded via web interface in github. doesn't work over email

**Comment by cohuser** [comment]
Thanks for helping me resolve the issue.
