### ISSUE TITLE
feature? images imported and visible within the description field

### ISSUE THREAD

**Issue by rjmaris** [eventum/eventum#346]
Embedding images into the description field would be great. I wish to have some features found in some visual issue tracking systems out there.
Referring to the Dokuwiki effort I'd suggest to use DW-editor resources to enter text, markup & embed images.

**Comment by glensc** [comment]
there's one branch to use markdown for rendering: #291

**Comment by rjmaris** [comment]
Momentarily. I'm testing flyspray, which support dokuwiki syntax, close to Creole standard, which I prefer.

**Comment by rjmaris** [comment]
I know that markdown is "more mainstream" but creole's syntax (in a modified way e.g. used in Dokuwiki) is more intuitive and hence, better with casual users in mind..
Those who have the first offerings on the market are often most successful, but not best.

Creole, PHP? I only can search this, and find some hits, pointing e.g. to github.

**Comment by balsdorf** [comment]
We use Creole in the MariaDB Knowledge base and I'm wanting to move away
from it. It might be a simpler syntax but at the end of the day, it is
rarely used. I'm fine with pluggable drivers, but the most common
(markdown) should be the default.
