### ISSUE TITLE
No issues after upgrade

### ISSUE THREAD

**Issue by OanaOita** [eventum/eventum#348]
After i upgrade from 2.0.1 to 2.0.2 i cant see any issues in the list. They are thare and the graphics see them but they doesnt show in the list. What im doing wrong?

**Comment by balsdorf** [comment]
Did you run the upgrade scripts to alter the database?

**Comment by OanaOita** [comment]
Yes i did. I updates from 2.3.3 and it worked fine untill 3.2.1. As soon as i update to 3.2.2 the upgrade.php shows only #!/usr/bin/php. When i enter in the list section it says "No se encontraron casos" (It didnt find any issues). If i enter an issue number it shows me the issue. If i go to statistics it shows me the real numbers.

**Comment by OanaOita** [comment]
I upgraded from 2.3.3 but not directly. i did all the steps.

**Comment by OanaOita** [comment]
Last time the upgrade.php returned something was when i runned it from version 3.2.0 the second time.  :"#!/usr/bin/php * Your database is already up-to-date. Version 69 ". After that it only returns #!/usr/bin/php

**Comment by balsdorf** [comment]
That is the old upgrade script. The migration script is now `bin/upgrade.php`.

**Comment by OanaOita** [comment]
I know. I allready said that i folowed the steps correctly. I used first the /upgrade/ script then the /bin/ one. I upgraded correctly to 3.2.1 version. On the 3.2.1 version everything works fine. On the 3.2.2 it stops showing the issues.

**Comment by OanaOita** [comment]
Anyway, thanks for nothing. I made it work on my own installing a new version than copying the data fron the old database to the new one.
