### ISSUE TITLE
Mails doesnt send after upgarde

### ISSUE THREAD

**Issue by OanaOita** [eventum/eventum#349]
I have CRON on "/bin/process_mail_queue.php" and after upgrade eventum from 2.3.3 to 3.3.4 (with all stops ) stopped working send mail and show errors:
#!/usr/bin/php Mail_Queue: issue #7890: Can't send mail 37201: Could not open socket 
Mail_Queue: issue #7890: Can't send mail 37202: Could not open socket
 Mail_Queue: issue #7891: Can't send mail 37203: Could not open socket etc

**Comment by balsdorf** [comment]
Couple of things to check:

- Is all the smtp server information correct in manage/general.php ?
- Is there any additional error information in var/log/eventum.log ? If so, please share it.
