### ISSUE TITLE
severity field on issue create page

### ISSUE THREAD

**Issue by glensc** [eventum/eventum#35]
when severity is defined for project, it is marked as required field.

however, in new issue page (new.php), when i do not fill the field, and hit create issue, i see the field error appear for a second, and then redirected to new issue page with a flash message "Your issue was created successfully."

first should fix that when field is incorrectly filled, the submit would abort.

optionally maybe make field optional, but i can live with it being not optional.

**Comment by balsdorf** [comment]
This does not seem to be an issue anymore. When I go to create an issue not filling out severity properly aborts the submit.
