### ISSUE TITLE
Problem installing eventum due to depenency. 

### ISSUE THREAD

**Issue by rtmaki** [eventum/eventum#361]
Hi, I used to use Eventum a long time ago, and wanted to install it brand new into wampserver 64 bit. When it tries to run the following curl for installing:

curl -sS https://getcomposer.org/installer | php $ php composer.phar install

It gives an error that it is missing: cygcurl-4.dll. It is not part of the current curl installation, and I cannot find it in any older packages either, and I would probably need that in 64 bit. Can you tell me how to get past this error, or would you have the needed dll in 64 bit?

Thank you very much!

Rick

**Comment by glensc** [comment]
Sorry, php install questions are better asked/searched in StackOverflow: https://stackoverflow.com/questions/tagged/php+windows+64bit

**Comment by rtmaki** [comment]
Just an FYI for you. I ended up having to manually install composer on WAMPSERVER. And even that failed. I then had to create a fake directory in the www root called tests/src. Once that was created, the installation of composer worked, and created the autoload.php file. Once that was created in /vender/autoload.php, the installation continued. Thank you very much for making this awesome software. It seems that when Installed, it was supposed to email me a user and password. Is there anyway to get that if the email did not send? Thank you very much!

**Comment by rtmaki** [comment]
Sorry for all the replies. I guessed at the user and password and got in ... thanks

**Comment by glensc** [comment]
it's probably simpler to use .tar.gz from releases than use git checkout and composer.

**Comment by rtmaki** [comment]
I didn't realize there was a difference in packages zip or tar.gz. I will keep that in mind for next time .. thank you. So far all is working good.

**Comment by glensc** [comment]
each release has three downloads:

- eventum-3.4.0.tar.gz
- Source code (zip)
- Source code (tar.gz)

first is produced by eventum release, containing everything needed (dependencies) to run the app. the other two links are automatically created by github, containing only source code.

so even saying "zip vs tar.gz" is ambiguous, because there are two .tar.gz
