### ISSUE TITLE
How do we setup the email queue now?

### ISSUE THREAD

**Issue by rtmaki2000** [eventum/eventum#389]
I wanted to know how to setup the email queue now. The instructions refer to files that do NOT exist in the latest code download. There is NO CHRON folder either. Please advise. 

The following files do NOT exists now (perhaps you need to update the documentation?):

1./crons/download_emails.php (Downloads e-mail to Eventum)
2. ./crons/process_mail_queue.php (Sends e-mail from Eventum)

**Comment by balsdorf** [comment]
Hi, we do need to update our documentation.

The proper path for both of those scripts is `./bin/`

**Comment by glensc** [comment]
@rtmaki2000 perhaps link to documentation page you were reading.

anyway the folders rename is mentioned in upgrade doc: https://github.com/eventum/eventum/wiki/Upgrading

**Comment by glensc** [comment]
changed in wiki two pages as well

```
➔ git diff v3.5.1..HEAD --stat
 Home.md                                         | 14 +++++++-------
 System-Admin/System-Admin:-Email-integration.md | 13 +++++--------
 2 files changed, 12 insertions(+), 15 deletions(-)
```
