### ISSUE TITLE
Subject Based Routing : Not a valid Mime Message: End Missing

### ISSUE THREAD

**Issue by KumarPOnline** [eventum/eventum#390]
cd /home/example/public_html/bin 
php -f download_emails.php dm@example.in mail.example.in INBOX

In Decode.php line 54:
Not a valid Mime Message: End Missing

I've send mail with subject as, "Issue on dm index page" to  dm@example.in from my reported email address.

example.in is hosted on WHM server, and the eventum is installed with download package from github.

Version: Eventum 3.5.1 

How to over come this issue ? What is wrong in my flow ?

Regards,
Kumar P

**Comment by glensc** [comment]
If this is still relevant, provide reproducer (dump of mail for example).
