### ISSUE TITLE
Email not rendering in outlook

### ISSUE THREAD

**Issue by rtmaki** [eventum/eventum#391]
All email notifications are not rendering as HTML in outlook. I get all other emails as html fine, so the issue is not with outlook. What needs to be done to ensure that email I sent from the queue, and able to be properly rendered as html. 

Thanks for your help!

Rick Maki

**Comment by balsdorf** [comment]
Eventum's notifications are all text based currently, not HTML.

**Comment by rtmaki2000** [comment]
Okay, I'm the one that you said could enable markdown. I added HTML support as a WYSIWIG to the description and internal notes section using CKEDITOR, and would like to allow for HTML to be rendered in what gets sent to in email. Please let me know if that is at least on the roadmap. Thank you!

**Comment by glensc** [comment]
there is no roadmap. submit PR and it will be included if ready for merge.
