### ISSUE TITLE
Underscore characters being removed from the description view with normal view

### ISSUE THREAD

**Issue by rtmaki2000** [eventum/eventum#392]
Since the normal view and fixed width views toggle, it is hard to tell which is which. However, when the text is not set to auto wrap in the description view, all text seems to render properly. However, when in the mode where it auto wraps, some but not all of the underscore characters seem to get removed. I have a combination of characters in some of the text I enter in my entries, such as a=b_+$, and the underscore is removed in the view on one, but not the other view. This is easily recreated.

**Comment by rtmaki2000** [comment]
Please if you find a solution, can you post a patch here, as I cannot upgrade my version because of the many customizations I have in it. This area in the code was not customized however.

**Comment by glensc** [comment]
Unclear issue, no repeoducer. also renderer has been replaced with markdown by now.
