### ISSUE TITLE
Eventum UI shows the entire "raw" email source vs. just the body portion

### ISSUE THREAD

**Issue by TexasGitHubber** [eventum/eventum#399]
I noticed that since installing the 3.5.2 release, we are having issues when sending emails to Eventum.

Looking at the emails on the eventum UI shows the entire email source rather than just the body. 

It seems that when the emails are downloaded and loaded into the `support_email_body` table, the column `seb_body` contains the entire email source code rather than just the content within the `<body></body>`  tag.

Upon further investigation, we narrowed this down to an issue in TextMessage.php.

```php
class TextMessage
{
    /** @var MailMessage|Part\PartInterface */
    private $message; 
```

The following `foreach `is completely skipped:

```php
foreach ($this->message as $part) {
            $headers = $part->getHeaders();
            $ctype = $part->getHeaderField('Content-Type');
            $hasDisposition = $headers->has('Content-Disposition');
            $disposition = $hasDisposition ? $part->getHeaderField('Content-Disposition') : null;
            $filename = $hasDisposition ? $part->getHeaderField('Content-Disposition', 'filename') : null; 
```

It appears that the `MailMessage `object is not being evaluated as a `Zend\Mail\Storage\Part` Array.

This is our version info:

```
php -v 
PHP 5.6.32 (cli) (built: Oct 29 2017 14:02:30)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

```

Is there a Zend requirement or MIME type configuration necessary that we may be missing?

Thanks!!

**Comment by glensc** [comment]
probably specific to your email. save the raw input and add testcase into [tests/Mail/TextMessageTest.php](tests/Mail/TextMessageTest.php) so it could be reproduced locally by other developers.
