### ISSUE TITLE
Support for SSL/TLS/STARTTLS without auth

### ISSUE THREAD

**Issue by areis422** [eventum/eventum#403]
We use an anonymous mail relay which is restricted by IP vs restricted by user. When attempting to send using SSL/TLS or STARTTLS, receive the following:

app.ERROR: 5.7.0 Must issue a STARTTLS command first  {"traceFile":"/var/www/eventum-3.5.2/var/log/zf-mail-5b61de87b08ec4.53977553.json","exception":"[object] (Zend\\Mail\\Protocol\\Exception\\RuntimeException(code: 0): 5.7.0 Must issue a STARTTLS command first\r\n at /var/www/eventum-3.5.2/vendor/zendframework/zend-mail/src/Protocol/AbstractProtocol.php:327)"} {"file":"/var/www/eventum-3.5.2/src/Mail/MailTransport.php","line":55,"class":"Eventum\\Mail\\MailTransport","function":"send","memory_usage":"6 MB","memory_peak_usage":"6 MB","version":"3.5.2","usr_id":""}
Mail_Queue: Can't send mail 1014567 (3 tries): issue #70444: 5.7.0 Must issue a STARTTLS command first

Can SSL/TLS/STARTTLS support be changed to:
A. be allowed on an anonymous connection?
B. Support STARTTLS in addition to Plain or SSL/TLS?

**Comment by glensc** [comment]
share your config. not sure what `When attempting to send using SSL/TLS or STARTTLS` means.

**Comment by areis422** [comment]
snippet from setup.php

`  'smtp' =>
  array (
    'from' => 'Eventum 3.5.2 <eventum3@domain.tld>',
    'host' => 'mailrelayaddress.domain.tld',
    'port' => '587',
    'auth' => false,
    'ssl'   => 'tls',
  ),
`
There aren't any options that force the use of STARTTLS. I had to actually allow cleartext connections to my mail relay, where I had been forcing them to use SSL/TLS or STARTTLS after initial connection.

**Comment by areis422** [comment]
Which library is being used for mail operations?

**Comment by areis422** [comment]
Bump. I'd like to get rid of cleartext/unencrypted SMTP where possible..

**Comment by glensc** [comment]
zend/mail. patches (pull requests) are welcome.

**Comment by glensc** [comment]
@areis422 can you test https://github.com/eventum/eventum/pull/684

I don't have server to test with, but the change seems to have effect as error changed from

```
app.ERROR: 5.7.0 Must issue a STARTTLS command first. h5sm1469355ljf.83 - gsmtp
```

to

```
app.ERROR: 5.5.1 Authentication Required. Learn more at
 5.5.1  https://support.google.com/mail/?p=WantAuthError i6sm1324126lfo.83 - gsmtp
```

**Comment by areis422** [comment]
Worked fantastically @glensc 

Oct  3 10:02:42 HOSTNAME postfix/smtpd[11008]: connect from unknown[IP]
Oct  3 10:02:42 HOSTNAME postfix/smtpd[11008]: Anonymous TLS connection established from unknown[192.168.204.43]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (4096 bits) server-digest SHA256
Oct  3 10:02:42 HOSTNAME postfix/smtpd[11008]: 75F34E0063: client=unknown[IP]
Oct  3 10:02:42 HOSTNAME postfix/cleanup[11773]: 75F34E0063: message-id=<eventum.md5.5kd0ayskw.5luwn8pjfips@staging.eventum.domain.tld>
Oct  3 10:02:42 HOSTNAMEpostfix/qmgr[859]: 75F34E0063: from=<support@domain.tld>, size=2480, nrcpt=1 (queue active)
Oct  3 10:02:42 HOSTNAME postfix/smtpd[11008]: disconnect from unknown[IP] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
Oct  3 10:02:42 HOSTNAME postfix/smtpd[10510]: connect from unknown[IP]
Oct  3 10:02:42 HOSTNAME postfix/smtpd[10510]: Anonymous TLS connection established from unknown[192.168.204.43]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (4096 bits) server-digest SHA256
Oct  3 10:02:42 HOSTNAME postfix/smtpd[10510]: A1251E0065: client=unknown[IP]
Oct  3 10:02:42 HOSTNAME postfix/cleanup[11773]: A1251E0065: message-id=<eventum.md5.5kd0ayskw.5luwn8pjfips@staging.eventum.domain.tld>
Oct  3 10:02:42 HOSTNAME postfix/qmgr[859]: A1251E0065: from=<support@domain.tld>, size=2485, nrcpt=1 (queue active)
Oct  3 10:02:42 HOSTNAME postfix/smtpd[10510]: disconnect from unknown[IP] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
