### ISSUE TITLE
problems erasing attachments

### ISSUE THREAD

**Issue by lmoralesa** [eventum/eventum#412]
Hi, we did and upgrade from eventum 3.2.0 to 3.5.3, in version 3.2.0 users did have permissions to erase attachments, now I am receiving reports that users can not erase attachment.
I need help to see if you can guide me in this issue

**Comment by glensc** [comment]
You really need to give more information, can't just guess what might be wrong.

**Comment by lmoralesa** [comment]
for example, a user creates an issue, fills the fields with information on the issue, attaches a * .txt or * .pdf file. and the issue is created. Once the issue is created, it is detected that the attached file is not correct, it is about removing the attachment and eventum gives an error message that says "You do not have the permission to remove this attachment."
The funny thing is that the message is given to the same user who attached the file, if it guides me where to obtain a log to send it and help us analyze

**Comment by lmoralesa** [comment]
I have and user that attached some files, he tries to erase them but got an error.

![image](https://user-images.githubusercontent.com/23003333/47865428-ce0a2c80-ddc1-11e8-8511-8d2d439dd414.png)

**Comment by glensc** [comment]
what is the role of user who is trying to delete? how where attachments created? via issue create via email or via web interface?

**Comment by lmoralesa** [comment]
The user has standart role, but we change the user to admin role and still can not erase the attach, the  attach files are upload via web, files are .pdf and .docx

**Comment by glensc** [comment]
was able to reproduce:
- upload with user role "user" and set min role as "standard user"
- attempt to delete such attachments results "-2"
- uploading with min role lower than that, works okay

this corresponds to these code paths:
- https://github.com/eventum/eventum/blob/v3.5.5/src/Attachment/AttachmentManager.php#L409
- https://github.com/eventum/eventum/blob/v3.5.5/src/Attachment/AttachmentManager.php#L381


i found also funny bug:
- user with role "user" was able to pick userlevel bigger from their own. the ui displayed success and closed the popup.

cc @balsdorf
