### ISSUE TITLE
Add values to the Rows per Page drop down on the List Issues page

### ISSUE THREAD

**Issue by cohuser** [eventum/eventum#414]
Can more values be added to the drop down for the field Rows per Page? Currently the values are 5,10,25,50,100,ALL.

**Comment by cohuser** [comment]
I am using version 2.1.1.

**Comment by balsdorf** [comment]
Yes, if you edit "list.tpl.html"  there is a dropdown list where you can add different options.

**Comment by cohuser** [comment]
Thank you for the prompt response.
