### ISSUE TITLE
process_mail_queue.php 3.5.4

### ISSUE THREAD

**Issue by vallecas** [eventum/eventum#425]
Hi!

I do a fresh install 

Eventum 3.5.4
PHP 7.2
Apache 
Ubuntu Server 18.04

After putting the following command in the cron I can not get mail sent
```
*  *    * * *   root    cd /var/www/html/eventum/bin; /usr/bin/php -f process_mail_queue.php
```

I tested with mail port 25 and the following error

```
[2018-12-19 14:45:01] app.ERROR: Could not open socket {"traceFile":"/var/www/html/eventum/var/log/zf-mail-5c1a4b5d31af53.93089700.json","exception":"[object] (Zend\\Mail\\Protocol\\Exception\\RuntimeException(code: 0): Could not open socket at /var/www/ht
ml/eventum/vendor/zendframework/zend-mail/src/Protocol/AbstractProtocol.php:209)"} {"file":"/var/www/html/eventum/src/Mail/MailTransport.php","line":55,"class":"Eventum\\Mail\\MailTransport","function":"send","memory_usage":"6 MB","memory_peak_usage":"6 MB
","version":"3.5.4","usr_id":""}
```

If I change it to port 587, the following error occurs:

```
[2018-12-19 13:46:02] app.WARNING: E_WARNING: stream_socket_enable_crypto(): Peer certificate CN=`*.neodigit.net' did not match expected CN=`mail.networkstest.es' {"code":2,"message":"stream_socket_enable_crypto(): Peer certificate CN=`*.neodigit.net' did 
not match expected CN=`mail.networkstest.es'","file":"/var/www/html/eventum/vendor/zendframework/zend-mail/src/Protocol/Smtp.php","line":178} {"file":null,"line":null,"class":null,"function":"stream_socket_enable_crypto","memory_usage":"6 MB","memory_peak_
usage":"6 MB","version":"3.5.4","usr_id":""}
```

**Comment by vallecas** [comment]
Hi!

Port 25 is open

administrador@eventum:/var/www/html$ telnet mail.networkstest.es 25
Trying 31.47.73.188...
Connected to mail.networkstest.es.
Escape character is '^]'.
220 host0v1b21-a188.neodigit.net ESMTP

I have several mail managers against that port and they work without problem

**Comment by glensc** [comment]
the exception thrown at [vendor/zendframework/zend-mail/src/Protocol/AbstractProtocol.php:209](https://github.com/eventum/zend-mail/blob/cbabc38a56c2e1ea156b3646db9a6f5c25c79826/src/Protocol/AbstractProtocol.php#L209) leads to this code:

```php
        $this->socket = @stream_socket_client($remote, $errorNum, $errorStr, self::TIMEOUT_CONNECTION);

```

so, try locally:

```php
<?php

stream_socket_client("tcp://mail.example.com:25", $errorNum, $errorStr, 30);
```

or remove the `@` in front of `stream_socket_client`, maybe that yields more detailed error.

**Comment by vallecas** [comment]
Hi!

After changing the mail with another provider, it works correctly so the case can be closed.

Thanks!
