### ISSUE TITLE
Starting over to reduce large search times

### ISSUE THREAD

**Issue by dgossage** [eventum/eventum#434]
We have roughly 7 years of tickets which has made search features more or less unusable as tables are locked for large duration of time when someone looks for an issue.  Unless their are some known tweaks I can be making regarding that we had been planning on just archiving old database with read only access and starting fresh.

Is their a simpler way to keep configuration for projects and users but truncate all the ticket data other than a one by one trip through the tables?

Currently on 3.5.4

Thanks for any input

**Comment by balsdorf** [comment]
Are you using the default MySQL fulltext search or sphinx?

Also, what version of MySQL / MariaDB are you running and what is your table type?

**Comment by dgossage** [comment]
maria 5.5 thats in the centos 7 default repo.
All the tables are MyISAM

To be honest I am probably using default mysql, I must have glossed over the sphinx section at some point during updates and am not that familiar with it.  Is this likely the best place to read up on its use case?

https://github.com/eventum/eventum/blob/master/docs/sphinx.txt

**Comment by balsdorf** [comment]
Yes that is the best place for sphinx info.

You would probably get a boost by upgrading your MariaDB installation to
the latest available version and converting to InnoDB. Priority to 10.0 you
can't have fulltext indexes on InnoDB tables.

Eventum works great on MariaDB 10.3, but I'm not sure what else you are
running on that server that might be impacted.

**Comment by dgossage** [comment]
Nothing but eventum on this instance.  I had looked at one point if innodb
was supported but thought I had seen that it wasn't recommended, but this
could have been quite some time ago as well.

I may give both those changes a try after a backup.

*David Gossage*
*Carousel Checks Inc. | System Administrator*
*Office* 708.613.2284

**Comment by balsdorf** [comment]
I've had good luck with elasticsearch for my other projects, but it can be a bit complex and it certainly isn't an "out of the box" experience.

We have been looking at a hosted search provider like https://www.algolia.com/ for another project and if that goes well I might experiment with plugging them into Eventum.

**Comment by vladsf** [comment]
Running on Sphinx 2.2.11-id64-release (95ae9a6).

**Comment by vladsf** [comment]
looked into `lib/eventum/search/class.sphinx_fulltext_search.php`. I suggest replacing `Support::getEmailDetails` call with a faster function which does not bother with headers (which cause unexpected exceptions)
 ```
$email = Support::getEmailDetails($match['match_id']);
$documents = [$email['sup_subject'] . "\n" . $email['message']];
```

**Comment by dgossage** [comment]
Thanks.  Finally got around to having time to enable sphinx and so far it looks to behave better.
