### ISSUE TITLE
Question about sending mail inside the issue page

### ISSUE THREAD

**Issue by vallecas** [eventum/eventum#437]
Before I used an old version of eventum 2.2 and could send mail from the page of the issue Is that option is not available now?

**Comment by glensc** [comment]
I don't understand the question. Can you link to documentation in wiki?

**Comment by glensc** [comment]
if it's a new installation, you probably need to enable the integration.

**Comment by vallecas** [comment]
Yes it´s a new installation.

I have the option enabled Administration -> General Setup -> Email Integration Feature -> Enable 
But it still does not leave the option to send mail from the issue page

Is that the option to be enabled?

Regards
Sergio

**Comment by glensc** [comment]
the `config/setup.php` key to enable the feature is:

```php
    'support_email' => 'enabled',
```

and in admin panel it's the exact same setting:
> Email Integration Feature

**Comment by glensc** [comment]
the block comes from [the setting I described](https://github.com/eventum/eventum/issues/437#issuecomment-462479739):
- https://github.com/eventum/eventum/blob/master/templates/view.tpl.html#L46-L52

the extra `$ema_id` seems to come that you do not have email account configured for that project.
