### ISSUE TITLE
Reduce amount of http requests per page

### ISSUE THREAD

**Issue by vladsf** [eventum/eventum#454]
Hi, 

Upgraded from 2.3.6 to 3.5.5 and noticed a lot of CSS and Javascript calls. Old Eventum pages were loading almost instantly. Now (3.5.x) I have to wait.
Only 1 request is PHP call, the rest 48 are static JS/CSS. Is there way to reduce requests number to 3-5?
```
49 requests
359.86 KB / 7.50 KB transferred
Finish: 7.66 s
DOMContentLoaded: 7.60 s
load: 7.72 s
```

**Comment by glensc** [comment]
The report is useless without detailed information like even page in your test.
The static content is likely cached, so it's not really an issue. I tested with `/list.php` and everything besides `list.php` came from memory or disk cache.

We do not have resources to develop new frontend anyway.

There was community effort, but the user dissapeared https://github.com/eventum/eventum/issues/144

**Comment by vladsf** [comment]
I see. Yes, static content is cached still 48 requests are sent to check if the caches entres is still valid.
Will try to tweak apache for now. 

JQuery is quite a bloatware will search for a minimizing/packaging solution.

**Comment by vladsf** [comment]
these FilesMatch lines improved apache response times:
```
 <Directory "/www/eventum/htdocs">
    DirectoryIndex login.php index.php
    ...
    <FilesMatch ".(ico|js|css)$">
      Header set Cache-Control "max-age=3600, private"
    </FilesMatch>
     AddOutputFilterByType DEFLATE text/html text/plain text/xml
 </Directory>


```

**Comment by glensc** [comment]
for javascript there are solutions:
- webpack
- rollup

just no resources to work on any of that (different priorities)

**Comment by vladsf** [comment]
Thanks! .htaccess sample worked perfectly. No need for webpack/rollup

**Comment by glensc** [comment]
if you want to help you can additionally:
1. update wiki docs about the htaccess example
2. add zlib deflate to htaccess example
