### ISSUE TITLE
Reply requires scrolling to find send email button

### ISSUE THREAD

**Issue by vladsf** [eventum/eventum#470]
Hi!

Reply (or Send Email) requires scrolling to find send email button. How do I increase the default height of the reply popup window? I tried to fix "function replyAsEmail(el)" in notes.tpl.html, but no effect.

![reply_popup](https://user-images.githubusercontent.com/4058524/52657701-4bd5ec00-2f0a-11e9-92d2-1cb7278b866b.png)

**Comment by glensc** [comment]
I'm not UI guru, but I'll happily accept PR that improves UI any way.

**Comment by cpinfold** [comment]
Vlad,

Take a look in page.js:
...

issue_view.replyIssue = function()
{
    var features =
'width=740,height=580,top=30,left=30,resizable=yes,scrollbars=yes,toolbar=no,location=no,menubar=no,status=no';
    var popupWin = window.open('send.php?cat=reply&ema_id=' +
issue_view.get_ema_id() + '&issue_id=' + issue_view.get_issue_id(),
'_replyIssue' + issue_view.get_issue_id(), features);
    popupWin.focus();
};

...
I too look forward to a fix..

Craig.

**Comment by vladsf** [comment]
thanks @cpinfold it worked with height=680! Not sure if I shall fix other 4 functions. Will send a PR.

**Comment by glensc** [comment]
the window height could dynamically adjust itself to make things fit...

**Comment by vladsf** [comment]
height=auto? Not sure if it would work. May be Stackoverflow hints with
height=0.65*parent_window_height is more predictable?

**Comment by glensc** [comment]
you forgot your stackoverflow link...

**Comment by vladsf** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/open#Window_features
https://stackoverflow.com/questions/31859280/dynamic-height-in-javascript-popup-window

I guess current height=(580 + some adjustment value) so the window keeps large enough even if
a parent resized to smaller size.

**Comment by glensc** [comment]
um, I would not resize according to the parent window, but the height of content itself of the popup (`window.innerHeight`):

- https://www.w3schools.com/jsref/prop_win_innerheight.asp

**Comment by vladsf** [comment]
`window.innerHeight ` is the height of the window not the content. I am not sure if `contentHeight` attribute exists.

**Comment by glensc** [comment]
my response was not to be taken directly, but rather as a hint. as i said, i'm no ui guru.

**Comment by vladsf** [comment]
I have given up on this. Just fixed page.js.

There are more weird troubles coming: zend-mail fails on emails with attachments, advanced search is unstable and works stable if only Excerpts are set "Hide".

**Comment by glensc** [comment]
1. send PR for page.js so we could benefit all
2. send PR with obfuscated enough testcase, we have quite some patches for broking mails to eat with zend-mail
3. see (or join) this discussion for switching backend https://github.com/eventum/eventum/issues/434
4. advanced search may just have issue unicode splitting. depends what backend you use, create separate issue if not same as #434
