### ISSUE TITLE
BUG: Issue with password reset template

### ISSUE THREAD

**Issue by areis422** [eventum/eventum#474]
When requesting a new password, the password_confirmation.tpl.txt file is passing the email address through rawurlencode. This was causing a double encoding, resulting in:

username%2540domain.tld

a % url encoded is %25. I was able to remediate this using escape:'hex' instead of rawurlencode. After which it encodes as:
username%40domain.tld

Can someone confirm this is a bug in 3.6.0?

**Comment by areis422** [comment]
Affected file: eventum/templates/notifications/password_confirmation.tpl.text

**Comment by glensc** [comment]
Please include the reason why you closed the issue: no longer relevant to you or fixed in a newer version?
