### ISSUE TITLE
Q: How to prepare a testcase for broken emails (for PR)?

### ISSUE THREAD

**Issue by vladsf** [eventum/eventum#476]
Hi,

I have two emails which break email processing in 3.5.5.
1. from Gnus Emacs mail client, eventum/bin/process_all_emails.php fails on it.
2. from Thunderbird, which partly processed: the raw email is saved in support_email_body.seb_full_email,
but seb_body is truncated, it has no headers, the body text is chopped.

I see the first step to save the emails in tests/data. What is the next step? How to make a testcase 
and see it failed/passed?

thanks.
[sample1.txt](https://github.com/eventum/eventum/files/2889098/sample1.txt)

**Comment by glensc** [comment]
get it to be reproducible outside your box:

- submit PR with the example inputs committed to `tests/data`. obfuscate out sensitive data, optionally cleanup irrelevant data
- if you can, add failing testcase, similar tests maybe in `tests/Mail`

**Comment by vladsf** [comment]
How I run my particular testcase in `tests/Mail`? I have searched the Wiki, but no hints on `phpunit`. Submitting obfuscated email without a failed test sounds no good.

**Comment by glensc** [comment]
I don't have to merge branch that is "not good", so just test data to get things going is fine.

I don't have energy to teach how to use phpunit, there should be plenty of documentation and howtos in search engines about that.

You can inspect git history in `tests` folder to see how things are done, I vaguely recall one PR even came from you submitting a test.
