### ISSUE TITLE
A0 (hex) character chops emails saved in support_email_body.seb_body

### ISSUE THREAD

**Issue by vladsf** [eventum/eventum#478]
If an incoming email body (reply to an issue) contains _non-breaking space_ `A0 (hex)` then Eventum chops the mail after `A0`
and saves the chopped email in `support_email_body.seb_body`.

Also it breaks `view_headers.php` while trying to view headers for the email. 

Noticed on emails from Thunderbird/60.4.0:
```
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Thunderbird/60.4.0^M
MIME-Version: 1.0^M
In-Reply-To: <59a6e098-3d85-4ddc-9f1f-397eccbd728b@oracle.com>^M
Content-Type: text/plain;^M
 charset="windows-1252";^M
 format="flowed"^M
Content-Transfer-Encoding: 8bit^M
Content-Language: en-US^M
```

**Comment by glensc** [comment]
are you sure it's not related to utf8mb3 truncation?

https://medium.com/@adamhooper/in-mysql-never-use-utf8-use-utf8mb4-11761243e434

there's WIP on switching: https://github.com/eventum/eventum/pull/433

**Comment by glensc** [comment]
also, need example email that caused the problem. unable to reproduce the problem otherwise.

**Comment by vladsf** [comment]
[message-chopped.zip](https://github.com/eventum/eventum/files/2896272/message-chopped.zip)
the tested `A0` message sample attached.

`mysql 5.7` returns ERROR on incorrect string both in utf8mb3 and utf8mb4, no partial saving. I guess it's PHP thing.
```
> create table a1 (str varchar(255)) DEFAULT CHARSET=utf8;
> insert into `a1` values(unhex("737472A0737472"));
ERROR 1366 (HY000): Incorrect string value: '\xA0str' for column 'str' at row 1
> select * from a1;
Empty set (0.00 sec)

> create table a1mb4 (str varchar(255)) DEFAULT CHARSET=utf8mb4;
> insert into `a1mb4` values(unhex("737472A0737472"));
ERROR 1366 (HY000): Incorrect string value: '\xA0str' for column 'str' at row 1
> select * from a1mb4;
Empty set (0.00 sec)
```

**Comment by vladsf** [comment]
Also `support_email_body.seb_full_email` raw email value is perfectly saved with `A0`.

**Comment by vladsf** [comment]
and `process_all_emails.php` returns no single error.

**Comment by glensc** [comment]
i think the thing is that your email is windows-1252 encoding, and it's not properly converted to utf8, and saving windows-1252 to utf8mb3 or utf8mb4 causes data loss, or that warning triggers no save...

**Comment by glensc** [comment]
`seb_body` is text version created from email, should be utf8. `seb_full_email` should be the original mail as it's blob column, it has no charset.

So, assume it's TextMessage problem like https://github.com/eventum/eventum/pull/477 was.

i'm not able to reproduce the truncation here, can you `mysqldump eventum support_email_body -wseb_sup_id=xxx` for analyze?

I get `Malformed header detected` with your provided data file, but you said you have no errors.

```
$ phpunit-5.7.phar tests/Mail/TextMessageTest.php
...
Malformed header detected
 vendor/zendframework/zend-mail/src/Headers.php:88
 vendor/zendframework/zend-mime/src/Decode.php:141
 vendor/zendframework/zend-mail/src/Storage/Part.php:99
 vendor/zendframework/zend-mail/src/Storage/Message.php:54
 src/Mail/MailMessage.php:66
 src/Mail/MailMessage.php:135
 tests/Mail/TextMessageTest.php:28
```

**Comment by vladsf** [comment]
I had no php errors with feeding email to "cat message.eml | php56 bin/process_all_emails.php". It silently added chopped email to issue email list.

(I'm afk, will drop the seb_body later)

**Comment by glensc** [comment]
wait. php56? what version are you running?

**Comment by glensc** [comment]
to my understanding this output is truncated in your environment:

```
$ php -r 'require "init.php"; var_dump(Eventum\Mail\MailMessage::createFromString(stream_get_contents(STDIN))->getMessageBody());' < tests/data/message-chopped.eml

Command line code:1:
string(456) "Hi,

On 2/12/19 9:47 AM, [Eventum] Aleandra Polar wrote:
> Hi Bob,
>
>     I was aaaaaaaa aa aaaaaaaaa aaa cccccc aaaaaaa aaaaaaa aaaar > taaaaa baaaaaae aa aaaaa-0.0 aa aaaaaaa. Then aaaaaaa and aaaa aaaa of > tps.  I taaaa  aaaaaaaaaa aa  aaaaa-0.0 dddld dd ddne ddd do ddt ddde > to take ccccccc bbb aaaaa also.This dddl dddd dd aa mdddddd dde iddddt > waaaaat aaaaaaaaag cccccccccc cccccc.
>
> Is taaa aaaa?

Best,
/Bob

--
Bbbbbbbb (Bob) Bobson"
```

**Comment by vladsf** [comment]
PHP 5.6.39 as recommended for Eventum 3.5.5.

**Comment by vladsf** [comment]
![img_20190223_150558](https://user-images.githubusercontent.com/4058524/53286263-daedca00-377c-11e9-90b6-09de68ecd13f.jpg)

Not truncated. (Droid Consolebot screenshot).

**Comment by glensc** [comment]
from your screenshot, i'd say it's not compatible with your terminal, thus maybe it's not utf8, altho the byte length is the same (456).

perhaps save the output to a file and attach here?

**Comment by glensc** [comment]
perhaps try the same commandline test with your original mail. maybe you obfuscated too much and not able to reproduce the original problem.

**Comment by vladsf** [comment]
I made a test 'cat message.eml| bin/process_all_emails.php' before
submitting the file. I made several tests to create the smallest sample.

The email is read Ok, but domehow is incorrectly saved in the database. I
need run tcpdump on mysql to see the actual queries sent. This might add
some light on the trouble.

**Comment by glensc** [comment]
unable to reproduce with your given input, tried php56 and 3.5.6, records in `support_email_body` table are as expected, not truncated.

is your table accurate?

```sql
show create table support_email_body;
```

is `APP_CHARSET` `utf8`?

**Comment by glensc** [comment]
please give mysqldump of your corrupted entry, maybe i'm looking at wrong thing. also i don't understand the thunderbird note in initial description.

**Comment by glensc** [comment]
the email is stored to database in `Support::insertEmail` method. you may add debugging code there.

**Comment by vladsf** [comment]
Enabled query log. That's mysql 5.7 server bug :/ Eventum is OK. Will post details later.

**Comment by vladsf** [comment]
> is `APP_CHARSET` `utf8`?
Yes, `APP_CHARSET` is `utf8`:
```
define('APP_CHARSET', 'UTF-8');
if (APP_CHARSET == 'UTF-8') {
    define('APP_EMAIL_ENCODING', '8bit');
} else {
    define('APP_EMAIL_ENCODING', '7bit');
}
```

**Comment by glensc** [comment]
this bug? https://bugs.mysql.com/bug.php?id=86421

**Comment by glensc** [comment]
please see what result gives if you do from php:

```sql
show variables like 'character%';
```

something like:

```
php -r 'require "init.php"; $sql = "show variables like \"character%\""; print_r(DB_Helper::getInstance()->getAll($sql));'
```

**Comment by vladsf** [comment]
[insert_A0A0A0.sql.gz](https://github.com/eventum/eventum/files/2897113/insert_A0A0A0.sql.gz)
This is the bad insert logged with A0A0A0 sequence.

**Comment by vladsf** [comment]
`> php -r 'require "init.php"; $sql = "show variables like \"character%\""; print_r(DB_Helper::getInstance()->getAll($sql));'
`
output looks OK to me.
[charset.txt](https://github.com/eventum/eventum/files/2897120/charset.txt)

**Comment by vladsf** [comment]
> this bug? https://bugs.mysql.com/bug.php?id=86421
I guess not. I am not using 8.0.2 client, also 8.0.2 was not GA.

**Comment by vladsf** [comment]
I am not sure if it is only a mysql server bug. It should have blamed the string sent, but PHP should have converted `A0` into proper utf8 two byte sequence.

**Comment by vladsf** [comment]
I got it. This issue affects only 3.5.5. Downloaded 3.5.6 and 
run `php56 -r 'require "init.php"; var_dump(Eventum\Mail\MailMessage::createFromString(stream_get_contents(STDIN))->getMessageBody());' < /tmp/message.eml` this worked the same way as for you - windows-1252 `A0 `converted to proper utf8 `C2 A0`.

**Comment by glensc** [comment]
can you git bisect to exact commit?

**Comment by glensc** [comment]
probably this changelog entry:
- Handle text/html only email rendering (@TexasGitHubber, @glensc, #399, #429, #400, #401)

**Comment by glensc** [comment]
bisecting is not easy, as there are merge commits. duh

```
$ git bisect start v3.5.5 v3.5.6 --
$ git bisect run ./bisect.php

The merge base 4406ba4995bc1053886cd8730a625102fd36635a is bad.
This means the bug has been fixed between 4406ba4995bc1053886cd8730a625102fd36635a and [0d8e160bc5b751ddab4a1efdae3dc82eac879843].
bisect run failed:
'bisect_state bad' exited with error code 3
```

duh, knew that already before automation

```
$ git checkout -b bisect-playground v3.5.6
$ git rebase v3.5.5
$ git bisect start HEAD v3.5.5  --
$ git bisect run ./bisect.php

c1d5e077ac46c747536a63d51ad0f75607d4ebb1 is the first bad commit
commit c1d5e077ac46c747536a63d51ad0f75607d4ebb1
Author: Elan Ruusamäe <glen@pld-linux.org>
Date:   Wed Dec 26 23:11:20 2018 +0200

    TextMessage: parse non multipart text/html as single part
```

which, as guessed, is this commit: 49a31074fda6dcfc5cf1f1cbe7e76d7f4c9ad854


what confused me the most, is that strlen of bad and good commit are both 456 bytes.

**Comment by glensc** [comment]
ok, it resolves your encoding issue, but as the text format now follows different code path, and that code path breaks RFC 3676 flowed text re-formatting.

**Comment by vladsf** [comment]
I can't do bisect, just made diff -u -r v3.5.5 v3.5.6.

I doubt about 49a3107, the change was made in `src/Mail/Helper/TextMessage.php` indeed, in `function getMessageBody()`. In 3.5.4/5 line 64 `$content = Mime_Helper::convertString((new DecodePart($part))->decode(), $charset);` under text/plain was never called so iconv from cp1252 to utf8 never happened.

In 3.5.6 the `convertString` call happens at line 112 in the new `function processPart($part)` so the message body is properly converted to utf8.

I believe this commit 83bcb6d made the change.

**Comment by vladsf** [comment]
or maybe 49a3107 it was. I will upgrade to 3.5.6 and see.

**Comment by glensc** [comment]
it was 49a3107, i bisected.

yes, this code path lacks iconv:
- https://github.com/eventum/eventum/blob/v3.5.6/src/Mail/Helper/TextMessage.php#L67

but as noted, i found another [bug](https://github.com/eventum/eventum/issues/478#issuecomment-466809832), so deciding on fix yet.

**Comment by glensc** [comment]
regarding the format=flowed bug:
- https://github.com/eventum/eventum/blob/ad8b66e4524bc1cf24663c7eb85846ca484a8524/tests/data/message-chopped.txt

you see that the current code moved the `> ` in beginning of line, to previous line(s), I don't think it's supposed to behave like that.

if it joined the lines, it should imho remove the `> ` character...

either some spaces got lost when you created the sample, or the `Mime_Helper::decodeFlowedBodies` is not working properly.

what do you think?

**Comment by vladsf** [comment]
Original message-chopped.eml (in zip file) submitted here above has all Unix line-endings `0A` in place right before `>` :
```
00000480   20 41 4D 2C  20 5B 45 76  65 6E 74 75  6D 5D 20 41  6C 65 61 6E  64 72 61 20  50 6F 6C 61  72 20 77 72   AM, [Eventum] Aleandra Polar wr
000004A0   6F 74 65 3A  0A 3E 20 48  69 20 42 6F  62 2C 0A 3E  0A 3E 20 A0  A0 A0 20 49  20 77 61 73  20 61 61 61  ote:.> Hi Bob,.>.> ... I was aaa
000004C0   61 61 61 61  61 20 61 61  20 61 61 61  61 61 61 61  61 61 20 61  61 61 20 63  63 63 63 63  63 20 61 61  aaaaa aa aaaaaaaaa aaa cccccc aa
000004E0   61 61 61 61  61 20 61 61  61 61 61 61  61 20 61 61  61 61 72 20  0A 3E 20 74  61 61 61 61  61 20 62 61  aaaaa aaaaaaa aaaar .> taaaaa ba
00000500   61 61 61 61  61 65 20 61  61 20 61 61  61 61 61 2D  30 2E 30 20  61 61 20 61  61 61 61 61  61 61 2E 20  aaaaae aa aaaaa-0.0 aa aaaaaaa.
00000520   54 68 65 6E  20 61 61 61  61 61 61 61  20 61 6E 64  20 61 61 61  61 20 61 61  61 61 20 6F  66 20 0A 3E  Then aaaaaaa and aaaa aaaa of .>
00000540   20 74 70 73  2E A0 20 49  20 74 61 61  61 61 A0 20  61 61 61 61  61 61 61 61  61 61 20 61  61 A0 20 61   tps.. I taaaa. aaaaaaaaaa aa. a
00000560   61 61 61 61  2D 30 2E 30  20 64 64 64  6C 64 20 64  64 20 64 64  6E 65 20 64  64 64 20 64  6F 20 64 64  aaaa-0.0 dddld dd ddne ddd do dd
```
I am afraid `Mime_Helper::decodeFlowedBodies` is not working properly. It joins the very next line if meets `A0` character.

**Comment by glensc** [comment]
Mime_Helper::decodeFlowedBodies will be replaced in #480, the other problem was solved (accidentally) in https://github.com/eventum/eventum/pull/429

**Comment by vladsf** [comment]
Thanks Elan!
