### ISSUE TITLE
Issue body adds bold tags (<b> </b>) to asterisks (*) in code block (``` ```)

### ISSUE THREAD

**Issue by tambetliiv** [eventum/eventum#482]
When adding this to issue body:
````
```
inside code block * shouldn't add * tags 
``` 
````
After saving, eventum shows this:
```
inside code block <b>* shouldn't add *</b> tags 
```

I guess this is unwanted behavior, since point of code block is to leave things as are and not format any more. 

Eventum version: `3.6.0-24-g8e4dc446e`

**Comment by glensc** [comment]
does not happen with prestine eventum; review your customizations.
