### ISSUE TITLE
List of available settings for setup.php and config.php

### ISSUE THREAD

**Issue by areis422** [eventum/eventum#484]
Can a list of array options be provided in the wiki for all available options and values to be used in setup.php?

**Comment by glensc** [comment]
wiki contributions are open, feel free to start!

**Comment by glensc** [comment]
as of 3.8.0, all settings are written to `config/setup.php`:
- #629, #642

... values from `config/config.php` are migrated to `config/setup.php` in the upgrade process and 3.9.0 will drop support reading `config/config.php` completely.
