### ISSUE TITLE
Blank screen in administator

### ISSUE THREAD

**Issue by OanaOita** [eventum/eventum#635]
Since 3.6.0 release i see nothing on the administrator part. Blanck scrren, no error no nothing. I know i might have something missing but i don´t know what. It´s a clean install.

**Comment by OanaOita** [comment]
Since 3.6.0 release i see nothing on the administrator part. Blank screen, no error no nothing. I know i might have something missing but i don´t know what. It´s a clean install.

**Comment by glensc** [comment]
maybe using https://pecl.php.net/package/scream helps to get errors out.

**Comment by OanaOita** [comment]
I can´t make scream work with php7.3.

 


Un saludo,

Oana Petronela Oita 


Departamento DTIC


 <mailto:pedro.ruiz@fluitecnik.com> ooita@fluitecnik.com


Tel: +34 670 37 07 19

 

 

De: Elan Ruusamäe [mailto:notifications@github.com] 
Enviado el: martes, 6 de agosto de 2019 9:04
Para: eventum/eventum
CC: OanaOita; State change
Asunto: Re: [eventum/eventum] Blank scrren in administator (#635)

 

maybe using https://pecl.php.net/package/scream helps to get errors out.

**Comment by glensc** [comment]
can't help if can't reproduce.

ps: remove your e-mail footer when replying by email. too noisy for just simple reply.

**Comment by OanaOita** [comment]
Hello,

 

I enabled the php errors and now when i acces the administrator menu it gives me this error:

Fatal error: Declaration of Eventum\Controller\Manage\ManageBaseController::canAccess() must be compatible with Eventum\Controller\BaseController::canAccess(): bool in /var/www/html/eventum/src/Controller/Manage/ManageBaseController.php on line 19

Can you please help?

 

De: Elan Ruusamäe [mailto:notifications@github.com] 
Enviado el: martes, 6 de agosto de 2019 14:20
Para: eventum/eventum
CC: OanaOita; State change
Asunto: Re: [eventum/eventum] Blank screen in administator (#635)

 

can't help if can't reproduce.

ps: remove your e-mail footer when replying by email. too noisy for just simple reply.

**Comment by glensc** [comment]
looks like PHP 7.3 is more strict than 7.1, the code is tested with PHP 7.1. I can't promise when I can look at the type errors, but you can try older PHP, or edit the files yourself.

**Comment by OanaOita** [comment]
I solved it by replacing /src/Controller/BaseController.php and  /src/Controller/Manage/ManageBaseController.php with the 3.6.0 versions.

**Comment by glensc** [comment]
what version you were getting the original error? declarations look okay in 3.7.4:
- https://github.com/eventum/eventum/blob/v3.7.4/src/Controller/BaseController.php#L243
- https://github.com/eventum/eventum/blob/v3.7.4/src/Controller/Manage/ManageBaseController.php#L37

**Comment by OanaOita** [comment]
Versions 3.6.3 to 3.7.3

**Comment by glensc** [comment]
Unclear how you had that error. no changes to these files from 3.7.3..3.7.4 and 3.7.4 is correct. perhaps you forgot to copy all files when installing? Can you attach here the original files you had error with?

**Comment by martin-dufka** [comment]
I had similar problem after fresh installation. Clearing cache dir helped.
