### ISSUE TITLE
Error at first connection

### ISSUE THREAD

**Issue by raspbeguy** [eventum/eventum#636]
**Version(s) affected**: 3.7.4

**Description**  
impossible to access to the service when deploying a fresh install. I have what seem to be a dev error page (see _Additional context_ section for the screenshot).

**How to reproduce**  
Deploy a fresh install. My configuration is Ubuntu 18.04 with nginx and php-fpm.
Output of `php -m`:
```
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imap
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache
```
My nginx config:
```
server {
    listen 80;
    server_name eventum.example.net;

    access_log /var/log/nginx/eventum-access.log;
    error_log /var/log/nginx/eventum-error.log;

    root /var/www/eventum/htdocs;

    location / {
            try_files $uri $uri/ =404;
            index index.php;
    }

    location ~ \.php {
            include fastcgi_params;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
            fastcgi_index index.php;
    }
}
```

**Possible Solution**  
I guess it would be fixed if the complete configuration were present but the setup process has not even started.

**Additional context**
Screenshot of the error:
![Screenshot_2019-08-07 Screenshot](https://user-images.githubusercontent.com/1781287/62623839-1b539580-b922-11e9-8e15-ba0741e1c834.png)

**Comment by glensc** [comment]
it's due weird Symfony caching. for me, the notice went away if I just refreshed the page. can you confirm this?

I have planned this for the next version to get rid of the constants: https://github.com/eventum/eventum/pull/629

**Comment by glensc** [comment]
altho this could be due PHP 7.2 version being used. I currently tested only with 7.1.

**Comment by raspbeguy** [comment]
The error doesn't go away after a refresh.

**Comment by glensc** [comment]
unable to reproduce in the docker image, not with 7.1 not with 7.2:
- https://github.com/eventum/docker

**Comment by raspbeguy** [comment]
the docker image comes with config file already set up. The problem here is exactly before the configuration generation.

**Comment by glensc** [comment]
which config file is setup in docker image?

I've removed config/setup.php and config/config.php and re-run the setup. no errors.

**Comment by raspbeguy** [comment]
This is what I did on a **fresh new LXC Ubuntu 18.04 instance**:
```
$> apt install nginx php-fpm php-ctype php-date php-intl php-fileinfo php-gd php-gettext php-iconv php-imap php-json php-mbstring php-pdo php-pdo-mysql vim
$> cd /var/www
$> wget https://github.com/eventum/eventum/releases/download/v3.7.4/eventum-3.7.4.tar.xz
$> tar xf eventum-3.7.4.tar.xz
$> mv eventum-3.7.4 eventum
$> chown -R www-data:www-data eventum
$> cd /etc/nginx/sites-available/
$> vim eventum

server {
    listen 80;
    server_name eventum.example.net;

    access_log /var/log/nginx/eventum-access.log;
    error_log /var/log/nginx/eventum-error.log;

    root /var/www/eventum/htdocs/;

    location / {
            try_files $uri $uri/ =404;
            index index.php;
    }

    location ~ \.php {
            include fastcgi_params;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
            fastcgi_index index.php;
    }
}

$> cd /etc/nginx/sites-enabled/
$> ln -s ../sites-available/eventum
$> systemctl restart nginx

**Comment by glensc** [comment]
works with docker image: https://github.com/eventum/docker

last tested with 3.8.0
