### ISSUE TITLE
DatabaseSetup have a user name key bug

### ISSUE THREAD

**Issue by crirus** [eventum/eventum#688]
**Version(s) affected**: master

**Description**  
[D:\www\eventum\src\Setup\DatabaseSetup.php:171](https://github.com/eventum/eventum/blob/v3.8.2/src/Setup/DatabaseSetup.php#L171)
should read key user not username

**How to reproduce**  
setup new account with new user
also user is not created in db

**Comment by glensc** [comment]
what is the bug? how the bug presents itself? what is done incorrectly? what can't you do?

**Comment by martin-dufka** [comment]
@crirus   This is creating new db user on fresh install about, isn't it?
What version of DB do you have? MySQL? MariaDB? OS?
