### ISSUE TITLE
Custom Fields - Sorting issues

### ISSUE THREAD

**Issue by areis422** [eventum/eventum#702]
**Version(s) affected**: 3.8.3 (looks to be > 3.7.1)

**Description**  
1. Currently set values for custom fields (which forms to display on, whether to show on list issues page) are not pulled from the database
2. Custom Field option sort (Alphabetical, reverse Alphabetical, etc) not honored. 

**How to reproduce**  
1. Create a custom field
2. change display options, save
3. reedit custom field, display options not shown

----

1. create custom field, change type to Combo Box
2. change sort type to alphabetical
3. save
4. add custom field options out of order (alphabetical)
5. save
6. create new issue, custom field options will be out of order

**Possible Solution**  
In one of the Custom Field models, make Doctrine lookup the order by value from custom_field

**Comment by glensc** [comment]
it orders bt cfo_value, but somewhy it also orders first with cfo_id:

```
mysql> SELECT t0.cfo_id AS cfo_id_1, t0.cfo_fld_id AS cfo_fld_id_2, t0.cfo_rank AS cfo_rank_3, t0.cfo_value AS cfo_value_4, t0.cfo_fld_id AS cfo_fld_id_5 FROM custom_field_option t0 WHERE t0.cfo_fld_id = 36 ORDER BY t0.cfo_id ASC, t0.cfo_value DESC;
+----------+--------------+------------+-------------+--------------+
| cfo_id_1 | cfo_fld_id_2 | cfo_rank_3 | cfo_value_4 | cfo_fld_id_5 |
+----------+--------------+------------+-------------+--------------+
|       30 |           36 |          1 | combo1      |           36 |
|       31 |           36 |          2 | zombo2      |           36 |
|       32 |           36 |          3 | nambo3      |           36 |
|       33 |           36 |          4 | fambo4      |           36 |
|       34 |           36 |          5 | rambo5      |           36 |
+----------+--------------+------------+-------------+--------------+
5 rows in set (0,01 sec)
```

**Comment by glensc** [comment]
and no, it's broken from 3.6.3:
- Refactor Custom Fields to use Interfaces and Doctrine Models (@glensc, #466, #506)
