### ISSUE TITLE
Upgrade from 3.5.6 to 3.6.1

### ISSUE THREAD

**Issue by lmoralesa** [eventum/eventum#729]
Upgrade from 3.5.6 to 3.6.1
**Description**  
I did an upgrade from version 3.5.6 to 3.6.1, PHP version install 7 in my OS, when finish the upgrade all tabs on Eventum works except for Administration tab, it does not open.

I would like to know if there is an specific PHP extencion to install in order to open Administration Tab.

**How to reproduce**  
Upgrade completed, I log in on eventum, navigate on all tabs but when open Administation tab, It does not open, the web page stays blanc.

**Possible Solution**  

**Additional context**

**Comment by lmoralesa** [comment]
PHP install 7.2

**Comment by lmoralesa** [comment]
PHP 7.1. install on my OS

**Comment by glensc** [comment]
https://lmgtfy.com/?q=how+do+i+view+php+error+logs&s=g&iie=1

**Comment by glensc** [comment]
read release notes for each specific release that you upgraded from:
- https://github.com/eventum/eventum/releases

**Comment by lmoralesa** [comment]
Problem fix

Thanks
