### ISSUE TITLE
Upgrade from v2.2 & v2.3.3 to v3.0.3 - There is no “logout” button in main screen

### ISSUE THREAD

**Issue by demas1976** [eventum/eventum#75]
When upgrading from v2.2 or v2.3.3 to v3.0.3:
The main screen (list.php) does not show the "logout" text.
I'm not a developer so the way I found to fix is described as follows: 

 - Modification in the file: “navigation.tpl.html”
Inserted the code just before the "administration" link.

                {if $core.current_role >= $core.roles.reporter}
                <li><a title="{t}logout from{/t} {$app_setup.tool_caption|default:$application_title}" target="_top" href="{$rel_url}logout.php" class="white_link">{t}Logout{/t}</a></li>
                {/if}

I hope I'm helping the community.
Thanks!

**Comment by glensc** [comment]
i don't see the error

the closing `{/if}` is there:

https://github.com/eventum/eventum/blob/v3.0.3/templates/navigation.tpl.html#L4

**Comment by glensc** [comment]
and i do have the logout link, even for `Viewer` role:

![screenshot](https://cloud.githubusercontent.com/assets/199095/10560488/137955ca-7515-11e5-9439-92cd64ec0951.png)

**Comment by glensc** [comment]
perhaps try cleaning `templates_c` directory?

**Comment by glensc** [comment]
no feedback from reporter, closing
