### ISSUE TITLE
Upgrade from v2.2 & v2.3.3 to v3.0.3 - "Error: Cookies support seem to be disabled in…”

### ISSUE THREAD

**Issue by demas1976** [eventum/eventum#76]
When upgrading from v2.2 or v2.3.3 to v3.0.3:

This is an old question in the FAQ provided.
The problem I found was, in the upgrading process there is no instruction or automatic change to update the "config.php" file.

When trying to login the system return:
"Error: Cookies support seem to be disabled in your browser. Please enable this feature and try again".

I solved it manually updating the config.php file.

// The old code was: define('APP_RELATIVE_URL', '/eventum-2.2/');
define('APP_RELATIVE_URL', '/eventum/htdocs/');

Just to include in the FAQ if it is possible.
Thanks!

**Comment by glensc** [comment]
FAQ is in wiki, and anybody can edit wiki.

however  your installation is wrong, you should not expose to web anything that is outside `htdocs` directory. your webserver document root should include `htdocs` subdir:

```
<VirtualHost *:80>
   ServerName eventum.example.org
   DocumentRoot /var/www/eventum/htdocs
</VirtualHost>
```

**Comment by glensc** [comment]
no feedback from reporter, closing
