### ISSUE TITLE
Problems Upgrading from 3.6.7 to 3.7.x

### ISSUE THREAD

**Issue by lmoralesa** [eventum/eventum#764]
**Version(s) affected**: 3.7.x

**Description**  
I'm upgrading Eventum from 3.6.7 to any 3.7.X version, I have install on my server php 7.4 and mysql 5.7

Version 3.6.7 works perfect

When I do the upgrade everythong wokrs fine except Administration option, when I click on It, it does not open the webpage.

I´ll go to apache logs and got the following.

192.168.250.117 - - [19/Nov/2019:11:00:18 -0600] "GET /manage/projects.php HTTP/1.1" 200 203 "http://192.168.248.207/list.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"

**How to reproduce**  

1-  rename /var/www/html/eventum-3.6.7 to eventum.old
2- copy eventum-3.7.x in /var/www/html/
3- copy /eventum.old/config to /var/www/html/eventum-3.7.x
4- in /eventum-3.7.x/config/setup.php change the line 'partition' => '/var/www/html/eventum-3.7.X'
5- modify /etc/apache2/sites-available/000-default.conf line DocumentRoot /var/www/html/eventum-3.7.x/htdocs
6- go to /var/www.html/eventum-3.7.x/bin/ and do ./upgrade 
7- go to open eventum on web
8- login and navigate through eventum, all windows work except Administration tab

**Additional context**  

![apache-access-log](https://user-images.githubusercontent.com/23003333/69168888-0e1b7a80-0abd-11ea-87c1-8ef3599e2b65.PNG)
![apache-error-log](https://user-images.githubusercontent.com/23003333/69169000-3efbaf80-0abd-11ea-9f2f-bcd925d9a467.PNG)

**Comment by lmoralesa** [comment]
php ldap extension already enable

![php ldap enable](https://user-images.githubusercontent.com/23003333/69170841-699b3780-0ac0-11ea-8449-11c407a26310.PNG)

**Comment by glensc** [comment]
The exception comes from Symfony Component:
- https://github.com/symfony/ldap/blob/v4.3.8/Adapter/ExtLdap/Adapter.php#L28-L30

this code particularly returns `false`:
```php
extension_loaded('ldap')
```

Re-check your setup, maybe the extension was not enabled for Apache SAPI, maybe restart failed, inspect [phpinfo()](http://php.net/phpinfo) output.

Also, while the current issue is not about the PHP version, but PHP 7.4 may be too new, you might run into random corner case issues, The current recommended is 7.1, but I myself use PHP 7.2. But CI jobs pass, so it might just work fine.

**Comment by lmoralesa** [comment]
Thanks for your answer, I will downgrade PHP to 7.2 and follow your recomendations

**Comment by glensc** [comment]
Made ldap check non-fatal: https://github.com/eventum/eventum/pull/765

**Comment by glensc** [comment]
@lmoralesa I'm sure your `ext-ldap` not working is not php version related

**Comment by lmoralesa** [comment]
I now have eventum 3.7.4 working but there is only a issue with one tab that is giving me the following error.

![apache-error-log-3 7 4](https://user-images.githubusercontent.com/23003333/69187156-aaef0f80-0adf-11ea-88f6-8cd714f708c2.PNG)

**Comment by lmoralesa** [comment]
There is a error about memory_peak-usage, is there a way i can fix that?

[Tue Nov 19 15:10:33.288416 2019] [php7:notice] [pid 17997] [client 192.168.250.117:7794] app.ERROR: Uncaught Exception Error: "Call to a member function toArray() on null" at /var/www/html/eventum-3.7.4/src/Controller/Manage/AuthController.php line 100 {"exception":"[object] (Error(code: 0): Call to a member function toArray() on null at /var/www/html/eventum-3.7.4/src/Controller/Manage/AuthController.php:100)\n[stacktrace]\n#0 /var/www/html/eventum-3.7.4/src/Controller/Manage/AuthController.php(43): Eventum\\\\Controller\\\\Manage\\\\AuthController->getAuthAdapterConfig()\n#1 /var/www/html/eventum-3.7.4/src/Controller/BaseController.php(67): Eventum\\\\Controller\\\\Manage\\\\AuthController->configure()\n#2 /var/www/html/eventum-3.7.4/src/Controller/Manage/ManageBaseController.php(28): Eventum\\\\Controller\\\\BaseController->__construct()\n#3 /var/www/html/eventum-3.7.4/htdocs/manage/auth.php(16): Eventum\\\\Controller\\\\Manage\\\\ManageBaseController->__construct()\n#4 {main}\n"} {"url":"/manage/auth.php","ip":"192.168.250.117","http_method":"GET","server":"192.168.248.207","referrer":"http://192.168.248.207/manage/general.php","file":null,"line":null,"class":null,"function":null,"memory_usage":"2 MB","memory_peak_usage":"2 MB","version":"v3.7.4","usr_id":"72"}, referer: http://192.168.248.207/manage/general.php

**Comment by glensc** [comment]
there's no error about memory peak, error is `Call to a member function toArray() on null" at /var/www/html/eventum-3.7.4/src/Controller/Manage/AuthController.php line 100`. you can format the error context (between `{` and `}`) with online tools like this one:

- https://jsonformatter.curiousconcept.com/

```json
{
   "exception":"[object] (Error(code: 0): Call to a member function toArray() on null at /var/www/html/eventum-3.7.4/src/Controller/Manage/AuthController.php:100)\n[stacktrace]\n#0 /var/www/html/eventum-3.7.4/src/Controller/Manage/AuthController.php(43): Eventum\\Controller\\Manage\\AuthController->getAuthAdapterConfig()\n#1 /var/www/html/eventum-3.7.4/src/Controller/BaseController.php(67): Eventum\\Controller\\Manage\\AuthController->configure()\n#2 /var/www/html/eventum-3.7.4/src/Controller/Manage/ManageBaseController.php(28): Eventum\\Controller\\BaseController->__construct()\n#3 /var/www/html/eventum-3.7.4/htdocs/manage/auth.php(16): Eventum\\Controller\\Manage\\ManageBaseController->__construct()\n#4 {main}\n"
}{
   "url":"/manage/auth.php",
   "ip":"192.168.250.117",
   "http_method":"GET",
   "server":"192.168.248.207",
   "referrer":"http://192.168.248.207/manage/general.php",
   "file":null,
   "line":null,
   "class":null,
   "function":null,
   "memory_usage":"2 MB",
   "memory_peak_usage":"2 MB",
   "version":"v3.7.4",
   "usr_id":"72"
}
```

**Comment by glensc** [comment]
according to the error:
- https://github.com/eventum/eventum/blob/v3.7.4/src/Controller/Manage/AuthController.php#L100

your `$config['auth']['options']` is missing from `config/setup.php`, which means auth migration patch was not executed:
- https://github.com/eventum/eventum/blob/v3.7.4/db/migrations/20190115211455_eventum_auth_adapter_setup.php

**Comment by lmoralesa** [comment]
Thanks for your support, from whitch path, do I have to run the pacth you mention.

**Comment by lmoralesa** [comment]
Thanks for your support, In not an expert, I would like to know how do I run that pacth.
![patch](https://user-images.githubusercontent.com/23003333/69246862-1c29d380-0b6f-11ea-826e-6a92f7f3b48e.PNG)

**Comment by lmoralesa** [comment]
It seems I dond have some librarys used on the scrit Eventum\Db\AbstractMigration, where can I get them

**Comment by glensc** [comment]
the patches are applied automatically with `./bin/upgrade.php`, or if installed from git and composer, `./vendor/bin/phinx migrate`

apparently you run the patches, but restored older `config/setup.php` the patch apply status is recorded in database `phinxlog` table.

```
mysql> select * from phinxlog where migration_name like '%adapter%';
+----------------+-------------------------+---------------------+---------------------+------------+
| version        | migration_name          | start_time          | end_time            | breakpoint |
+----------------+-------------------------+---------------------+---------------------+------------+
| 20190115211455 | EventumAuthAdapterSetup | 2019-11-19 22:40:02 | 2019-11-19 22:40:02 |          0 |
+----------------+-------------------------+---------------------+---------------------+------------+
1 row in set (0.00 sec)
```

you can delete that row, and re-run upgrade script, if you really did what I suspect, there may be more migrations that are applied to config but you restored older config.

**Comment by areis422** [comment]
Otherwise, depending on your OS you can run:
`sudo apt update
sudo apt install php7.4-ldap
sudo phpenmod ldap
sudo systemctl restart apache2
#IF php7.4-fpm
sudo systemctl restart php7.4-fpm
`

**Comment by areis422** [comment]
> **Version(s) affected**: 3.7.x
> 
> **Description**
> I'm upgrading Eventum from 3.6.7 to any 3.7.X version, I have install on my server php 7.4 and mysql 5.7
> 
> Version 3.6.7 works perfect
> 
> When I do the upgrade everythong wokrs fine except Administration option, when I click on It, it does not open the webpage.
> 
> I´ll go to apache logs and got the following.
> 
> 192.168.250.117 - - [19/Nov/2019:11:00:18 -0600] "GET /manage/projects.php HTTP/1.1" 200 203 "http://192.168.248.207/list.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
> 
> **How to reproduce**
> 
> 1- rename /var/www/html/eventum-3.6.7 to eventum.old
> 2- copy eventum-3.7.x in /var/www/html/
> 3- copy /eventum.old/config to /var/www/html/eventum-3.7.x
> 4- in /eventum-3.7.x/config/setup.php change the line 'partition' => '/var/www/html/eventum-3.7.X'
> 5- modify /etc/apache2/sites-available/000-default.conf line DocumentRoot /var/www/html/eventum-3.7.x/htdocs
> 6- go to /var/www.html/eventum-3.7.x/bin/ and do ./upgrade
> 7- go to open eventum on web
> 8- login and navigate through eventum, all windows work except Administration tab
> 
> **Additional context**
> 
> ![apache-access-log](https://user-images.githubusercontent.com/23003333/69168888-0e1b7a80-0abd-11ea-87c1-8ef3599e2b65.PNG)
> ![apache-error-log](https://user-images.githubusercontent.com/23003333/69169000-3efbaf80-0abd-11ea-9f2f-bcd925d9a467.PNG)

This error says that the ldap PHP module isn't loaded, NOT the apache module.

**Comment by glensc** [comment]
closing as stale. answers given to problems. if you have new problem, create new issue.
