### ISSUE TITLE
Error on logout

### ISSUE THREAD

**Issue by adicretu** [eventum/eventum#791]
**Version(s) affected**: 3.8.7

**Description**  
After upgrade to 3.8.7 from 3.5.2 when users click on logout the following eror is thrown:
An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)

**How to reproduce**  
Click on logout

**Possible Solution**  

**Additional context**  

![Capture1](https://user-images.githubusercontent.com/25267222/70798027-89b3d300-1dae-11ea-8695-78507c0cfbb1.PNG)
![Capture3](https://user-images.githubusercontent.com/25267222/70798028-89b3d300-1dae-11ea-93db-a8b269134f38.PNG)
![Capture2](https://user-images.githubusercontent.com/25267222/70798029-8a4c6980-1dae-11ea-93f6-84b8c7ea3d9e.PNG)

**Comment by glensc** [comment]
likely connection settings are incorrect when doctrine initialized from symfony.

**Comment by adicretu** [comment]
Is that a matter of settings or anything wrong in the DB ?

**Comment by glensc** [comment]
probably such code path does not initialize variables before symfony.

meanwhile you can confirm that the values you pasted in trace are correct/incorrect.

**Comment by glensc** [comment]
do you confirm that the values you pasted in the trace you shared are correct/incorrect?
