### ISSUE TITLE
[BUG] - Emails not deleted when they contain specific terms in subject or body.

### ISSUE THREAD

**Issue by areis422** [eventum/eventum#793]
**Version(s) affected**: 3.8.6

**Description**  
When Eventum is checking a POP3 or IMAP account for messages, it repeatedly downloads any messages that seem to relate to credential issues. Examples are: can't seem to log in, not able to log in, access to application, problem to log in, username and password recovery, etc. Eventum creates the initial issue, but fails to delete the message after download, and repeatedly creates issues from the same email until the email is manually deleted.

**How to reproduce**  
Send an email to a mailbox that eventum checks with the following:
Subject: Password and Username Recovery
Body: Hi, had some trouble with my email and have lost the login and password to application.

**Possible Solution**  

**Additional context**  
Is it possible there's some sort of regex/blacklist/whitelist that filters on terms like that?

**Comment by glensc** [comment]
Seems you're just assuming things. I don't think there is anywhere in codebase logic you are describing in this issue title. Eventum doesn't care what is your email subject. You need to describe better reproducer and/or trace of errors. The better reproducer is that someone else is able to reproduce on their system without extra details from you.
