### ISSUE TITLE
process mail queue error

### ISSUE THREAD

**Issue by OanaOita** [eventum/eventum#800]
**Version(s) affected**: x.y.z

**Description**  
I have uploaded out eventum  to en external server (ionos). Now it doesn't sends mails. I created a cron to launch process_mail_queue.php every 10 minutes.
When i tried to execute the php via SSH command it gives me this error:
<b>Parse error</b>:  syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in <b>/homepages/7/d320379408/htdocs/eventum/bin/process_mail_queue.php</b> on line <b>18</b>
Looks like is about this line "use Eventum\Console\Application;".
Can somebody help me?

**Comment by glensc** [comment]
File corrupted or wrong PHP version. See the installation documentation for the PHP version required for the appropriate eventum version that you installed.

**Comment by OanaOita** [comment]
thank you for the answer. Where i can find the installation documentation?

**Comment by glensc** [comment]
you omitted important question about your version:
> Version(s) affected: x.y.z

documentation is in docs folder, wiki subdir

**Comment by OanaOita** [comment]
version 3.6.7

**Comment by OanaOita** [comment]
I can´t find the required php version for eventum 3.6.7. can you help me please?

**Comment by OanaOita** [comment]
found it is 7.1. Thanks
