### ISSUE TITLE
My hosting provider blocks my eventum emails 

### ISSUE THREAD

**Issue by OanaOita** [eventum/eventum#806]
My hosting provider started to block may eventum emails 2 days ago.

The error that gives is :

```
#!/usr/bin/php Mail_Queue: Can't send mail (x tries): issue #10421: Transaction failed Reject due to policy restrictions. For explanation visit 
```

The only solution that they gave me is to change the programming to send the mail by PHP.

Did it ever occur to you something like that? Where I could find some logs or something to narrow down why did they block my emails?

Version affected 3.6.7 and 3.7.0

**Comment by OanaOita** [comment]
My hosting provider started to block may eventum emails 2 days ago.
The error that gives is : "#!/usr/bin/php Mail_Queue: Can't send mail (x tries): issue #10421: Transaction failed Reject due to policy restrictions. For explanation visit "
The only solution that they gave me is to change the programing to send the mail by php.
Did it ever occurred to you something like that? Where i could find some logs or something to narrow down why did they blocked my emails?

**Comment by glensc** [comment]
Unclear what is the error. "Change the programming to send the mail by PHP." sentence makes no sense. Find someone with a technical background to describe the error.

Also your error message has link truncated.

**Comment by cpinfold** [comment]
Sounds like it is your email provider.

If it is your hosting provider and not your email provider, consider
switching to a provider like Digital Ocean (inexpensive and works well)

If it is your email provider you could host email sending locally on the
server using something like Postfix (if a Linux machine).

Hope this helps,

Craig.

**Comment by OanaOita** [comment]
Do you have a paid option for support?
