### ISSUE TITLE
Issue Hiden

### ISSUE THREAD

**Issue by shivrajsinhdhummad** [eventum/eventum#838]
**Version(s) affected**: 3.0.6 

**PHP Version**: dont know

**Description**  

We have many projects on this eventum, thank you for this best application, we are facing small issue that, when we create new issue in new project then only we get orange box but its totally blank.
**How to reproduce**  

**Possible Solution**  

![Issue](https://user-images.githubusercontent.com/65294185/81821771-e418b180-954f-11ea-9bf0-820b275bfff1.png)

**Additional context**  

please tell me what the solution.

**Comment by glensc** [comment]
you have to troubleshoot that yourself, look at browser console, look at the error log on the server side.

**Comment by shivrajsinhdhummad** [comment]
please somebody provide me installation guide.
