### ISSUE TITLE
Q: how to migrate from APP_AUTH_BACKEND?

### ISSUE THREAD

**Issue by vladsf** [eventum/eventum#847]
Hi,
I have Eventum 3.5.5 and custom SSO auth class in eventum/auth/class.my_sso_auth_backend.php
plugged with define('APP_AUTH_BACKEND', 'My_Sso_Auth_Backend');
(Eventum users are synced with a backend script and a web server SSO sets REMOTE_USER)

I can not find APP_AUTH_BACKEND in the latest release. How do I plug my custom SSO in the latest Eventum?

**Comment by glensc** [comment]
This was changed in https://github.com/eventum/eventum/pull/441

There seems to be admin interface to configure adapters:
- `/manage/auth.php`

but it supports only built in versions....

however, if you update your class to implement new [AdapterInterface](https://github.com/eventum/eventum/tree/v3.8.12/src/Auth/Adapter/AdapterInterface.php) you can just load it manually from config/setup.php:

```php
    'auth' => [
        'adapter' => 'Eventum\\Auth\\Adapter\\My_Sso_Auth_Backend',
        'options' => [
        ],
    ],
```

I guess best would be to add support to [extensions](https://github.com/eventum/eventum/tree/v3.8.12/docs/examples/extension) to be able to provide classes for auth providers, then you can configure it using admin interface.

**Comment by glensc** [comment]
I've added such support to select custom auth adapter if your extension provides it:
- https://github.com/eventum/eventum/pull/849

**Comment by vladsf** [comment]
Thanks!
