### ISSUE TITLE
Time Tracking URL bug

### ISSUE THREAD

**Issue by assom974** [eventum/eventum#859]
**Version(s) affected**: 3.8.2

![eventum-question](https://user-images.githubusercontent.com/33230310/90660673-38e55b80-e214-11ea-81dc-715a079e8556.JPG)

**PHP Version**: PHP 7.1.32-1

**Description**  
When opening an issue with a 'Time Tracking' entry, if you click on the time tracking entry you get an error message:
"Sorry, you are not allowed to access this page."
With the URL pointing to :
eventum.*****.com/time_tracking.php?ttr_id=undefined
But if you right-click and choose open in new tab/window the URL is generated correctly and it works:
http://eventum.*****.com/time_tracking.php?ttr_id=3480

**How to reproduce**  
Open an existing issue that has a time tracking entry.
Click on the URL of the time tracking entry and the pop-up will give the error message:
"Sorry, you are not allowed to access this page."

**Possible Solution**  
Right-click and open on a new tab/window fix it.

**Additional context**  
I tried replicating the issue with the latest Eventum version of 3.8.15(on my test VM) and the same problem occurs.

**Comment by glensc** [comment]
Looks like it's changed in the browser itself:
- https://github.com/eventum/eventum/blob/v3.9.3/res/assets/scripts/pages/IssueView.js#L442

this expands to `<p>` tag what's inside `<a>` somewhy:
```diff
-        const ttr_id = $target.data('ttr-id');
+        const ttr_id = $target.closest('a').data('ttr-id');
```
