### ISSUE TITLE
Why does my event keep sending emails to my work mailbox, with more than 1000 items

### ISSUE THREAD

**Issue by Mapperslave** [eventum/eventum#872]
I have a question. Why does my event keep sending emails to my work mailbox, with more than 1000 items? How can I troubleshoot the problems

**Comment by glensc** [comment]
With so few information given you should your contact your eventum administrator. this is open source project of the eventum code. we do not manage your installation.

**Comment by Mapperslave** [comment]
So how do I troubleshoot email problems

**Comment by Mapperslave** [comment]
We've been using this feature for a long time, and we've only recently discovered that it automatically sends timeout alerts to our Outlook, but it used to send them at 0, and it's been sending them all the time.How do I check my event

**Comment by glensc** [comment]
Abstract problems get abstract replies.
