### ISSUE TITLE
assignment field not popping over in update form

### ISSUE THREAD

**Issue by jpelletier-sv** [eventum/eventum#916]
**Version(s) affected**: 3.9.3

**PHP Version**: 7.2.33

**Description**  
Unlike on the new issue form, the update form does not pop over with the list of possible assigments, and shows up-down arrows on the right instead, with the list being hidden if not scrolling

**How to reproduce**  
update an issue and click in the assignment field

**Possible Solution**  
not sure how but it's apparently a minor change to make it match the issue creation form

**Additional context**  
I just upgraded from version 3.6 where that issue was not present

**Comment by glensc** [comment]
Please attach a screenshot, difficult to understand what are you talking about.

**Comment by jpelletier-sv** [comment]
Here is the issue creation form showing a pop-over of the list of possible assignees when clicked:

![image](https://user-images.githubusercontent.com/68342307/90770282-88cd2c80-e2bf-11ea-86e6-6a0a6f9cf4d2.png)

Here is what I get doing the same on the update form:

![image](https://user-images.githubusercontent.com/68342307/90770509-e19cc500-e2bf-11ea-9c3c-0e544f1ccd23.png)

As you can see, the list of possible assignees div is not popping over like the creation form.  I need to press the down arrow on the right to see them one by one.

**Comment by glensc** [comment]
Ok, I've bisected the breakage to be somewhere v3.8.7..v3.8.8:

- https://github.com/eventum/eventum/compare/v3.8.7...v3.8.8
