### ISSUE TITLE
[Question] Is the Sphinx config listed in eventum/docs/sphinx.txt still valid?

### ISSUE THREAD

**Issue by areis422** [eventum/eventum#925]
Is the Sphinx config listed in eventum/docs/sphinx.txt still valid?

I ask because wasn't there an issue that was recently tagged that essentially ignores config.php now? If so, what's the expected settings in setup.php, in addition to fulltext=>sphinx (pseudo code there)?

**Comment by areis422** [comment]
Never mind, I'm an idiot and didn't check for the migration into setup.php before I asked the question. Sorry!

**Comment by glensc** [comment]
You are welcome to send documentation update PR!

**Comment by glensc** [comment]
The PR in topic: https://github.com/eventum/eventum/pull/629
