### ISSUE TITLE
Q: Broken links with trailing '>' char

### ISSUE THREAD

**Issue by vladsf** [eventum/eventum#932]
**Description**  
Hi, Thunderbird 68.11.0 sends plain text emails and surrounds links with < > chars. E.g. <http://example.com>.
Eventum renders it as "http://example.com>" link with trainling >. 
Such emails also have 'html' copy in the message body, so I guess this is a Thunderbird issue when a user has
"create html emails" enabled. 

Strictly speaking, > at the link end is a OK char and can be a part of the link. So this is not a bug, but a 
email client issue.

Would you please point me which Eventum class/func to look at so I can fix my own instance only. 

Eventum ver. 3.5.5

**Comment by glensc** [comment]
please use markdown code or code-fence so the formatting is raw in issue body. screenshot of your problem?

there is no simple answer, all depends how your email entered the system, and what is the problem.

Rather setup xdebug and trace with a breakpoint if you want to debug. 

and add for exact reproducer, perhaps attach as text file?

**Comment by vladsf** [comment]
Easy steps to reproduce:
Post internal note from Eventum web interface with a single line `Text <http://example.com> text`
![broken_link](https://user-images.githubusercontent.com/4058524/92103435-a4205780-ede8-11ea-8afb-c8712e42d510.png)
 
So this might be even an external lib problem :/

**Comment by glensc** [comment]
Unable to reproce with latest version:

![image](https://user-images.githubusercontent.com/199095/92118020-9a095380-edfe-11ea-820e-f780acf351e0.png)

**Comment by vladsf** [comment]
Thanks, so upgrade is the fix.

**Comment by glensc** [comment]
Yes, with 3.5.5:

![image](https://user-images.githubusercontent.com/199095/92119095-06d11d80-ee00-11ea-8284-01fc5356fb00.png)
