### ISSUE TITLE
404 on install

### ISSUE THREAD

**Issue by federico-razzoli** [eventum/eventum#938]
**Version(s) affected**: x.y.z

3.9.5

**PHP Version**: x.y.z

7.3

**Description**  

When trying to install, I try to do to `/eventum/htdocs/` but I get a generic "404 error" generated by Eventum (not the web server).
From the URL bar I see there was a redirection to `/eventum/htdocs/setup/`.

After modifying `config/setup.php` to force error diplaying, I see:

`Fatal error: Uncaught InvalidArgumentException: The file "/home/vettabas/public_html/eventum/config/setup.php" did not return a valid PHP array when included in /home/vettabas/public_html/eventum/src/Config/ConfigPersistence.php:45 Stack trace: #0 /home/vettabas/public_html/eventum/lib/eventum/class.setup.php(314): Eventum\Config\ConfigPersistence->load('/home/vettabas/...') #1 /home/vettabas/public_html/eventum/lib/eventum/class.setup.php(40): Setup::initialize() #2 /home/vettabas/public_html/eventum/lib/eventum/class.setup.php(157): Setup::get() #3 /home/vettabas/public_html/eventum/init.php(38): Setup::getDefaultTimezone() #4 /home/vettabas/public_html/eventum/htdocs/index.php(16): require('/home/vettabas/...') #5 {main} thrown in /home/vettabas/public_html/eventum/src/Config/ConfigPersistence.php on line 45`

**Comment by glensc** [comment]
you must not modify `config/setup.php` manually, revert your changes and the error will go away.

**Comment by glensc** [comment]
installing eventum as subdir is not supported, there's already long issue open: https://github.com/eventum/eventum/issues/634

it maybe has working workarounds, haven't checked.

**Comment by federico-razzoli** [comment]
I really suggest that Eventum says this. The 404 doesn't help new users in this case.

**Comment by glensc** [comment]
patches are welcome! while at it, fix the actual problem? :)
