### ISSUE TITLE
Wrong config file name in the documentation?

### ISSUE THREAD

**Issue by federico-razzoli** [eventum/eventum#939]
Please check:

https://github.com/eventum/eventum/blob/master/docs/wiki/System-Admin/Displaying-PHP-errors.md

The mentioned file `config/config.php` does not exist on a fresh install. If I should create the file myself, the documentation should mention this in a place that is easy to find. If it means `config/setup.php` or another file it should be fixed.

**Comment by glensc** [comment]
that's all outdated, submitted update: https://github.com/eventum/eventum/pull/940
