### ISSUE TITLE
Error updating 'Completion Percentage'

### ISSUE THREAD

**Issue by plindry** [eventum/eventum#94]
if you update an issue and change the value it's not recorded. Always 0.
In update.php

Regards

**Comment by balsdorf** [comment]
Thanks for finding all these missing / broken fields. Fixed

**Comment by plindry** [comment]
Hi Balsdorf,
I'm getting this error when i update 
call to undefined method Misc::trim ()
It comes from 
https://github.com/eventum/eventum/blob/v3.0.5/lib/eventum/class.issue.php#L1417
I remove "Misc::" from code because it seems i haven't this class. 
Regards

**Comment by plindry** [comment]
Hi Balsdorf,
I'm getting this error:
call to undefined Method Misc:trim() from this line
https://github.com/eventum/eventum/blob/master/lib/eventum/class.issue.php#L1417
I remove "Misc::" since it seems i haven't this class or I haven't visibility from this point. 
Now is working fine.
Regards

**Comment by glensc** [comment]
well. you should use whole codebase, not just single files.

`Misc::trim` was added in 3227a068acf984cd20a1c0bfbe66d5c660b696af
and if you do "blame" you'll navigate to exactly that commit:
https://github.com/eventum/eventum/blame/master/lib/eventum/class.issue.php#L1417
https://github.com/eventum/eventum/commit/3227a068acf984cd20a1c0bfbe66d5c660b696af

if you intended to add only commits, then you should used the patches not copy the affected files!
https://github.com/eventum/eventum/issues/94.patch

and just removing "Misc" you actually broke your code, "Misc::trim()" accepts arrays, "trim()" does not.

**Comment by plindry** [comment]
You are right glensc i should use the commit points. I'll wait to the 3.0.6 release because with my test i changed some files and download another ones so my enviroment is not so clean.

Regards

**Comment by glensc** [comment]
it is [released](https://github.com/eventum/eventum/releases/tag/v3.0.6) now. enjoy!

**Comment by glensc** [comment]
also, you should really consider [upgrading](https://github.com/eventum/eventum/wiki/Upgrading) instead of re-installing with each release.

**Comment by plindry** [comment]
Great!!. Tomorrow I'll try this new versión. I'll maintein de database from 3.0.2 (test enviroment) because i configured many fields, option, groups, people and so on.

In our production enviroment we use 2.2. Thanks for the link glensc. I think we can start next year with a fresh installation and let the old one in read mode and perhaps shut down it.

**Comment by glensc** [comment]
i still recommend to upgrade, even from 2.2, the upgrade process hasn't changed since 2.2 version. the same upgrade link works.
