### ISSUE TITLE
ERROR: Uncaught Exception TypeError: "Return value of Setup::isMaintenance() must be of the type boolean, null returned

### ISSUE THREAD

**Issue by vladsf** [eventum/eventum#941]
**Version(s) affected**: 3.9.5

While testing upgrade from 3.5.5 to 3.9.5 it triggers an error on bin/upgrade.php script

```
# php bin/upgrade.php
app.ERROR: Uncaught Exception TypeError: "Return value of Setup::isMaintenance() must be of the type boolean, null returned" at /export/ddd/intranet/eventum-3.9.5/lib/eventum/class.setup.php line 205 {"exception":"[object] (TypeError(code: 0): Return value of Setup::isMaintenance() must be of the type boolean, null returned at /export/ddd/intranet/eventum-3.9.5/lib/eventum/class.setup.php:205)
[stacktrace]
#0 /export/ddd/intranet/eventum-3.9.5/init.php(47): Setup::isMaintenance()
#1 /export/ddd/intranet/eventum-3.9.5/bin/upgrade.php(31): require_once('/export/home/in...')
```

**PHP Version**: 7.2.33

**Comment by glensc** [comment]
use code-fence or details for paste blocks

- https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks
- https://github.blog/2020-04-09-github-protips-tips-tricks-hacks-and-secrets-from-lee-reilly/#the-devils-in-the-details

**Comment by glensc** [comment]
I guess you need to update to each minor version separately:

- 3.5.5 -> 3.6.0
- 3.6.0 -> 3.7.0
- 3.7.0 -> 3.8.0
- 3.8.0 -> 3.9.0
- 3.9.0 -> 3.9.5

I'll see if there's a way to make this graceful, or need to update upgrade instructions.

**Comment by vladsf** [comment]
Ouch, that is a long path! 
OK, trying this way.

**Comment by glensc** [comment]
Well. if you read the changelog you may be able to short circuit. but each minor version a time should be safest route.

But in the end still need to find release that added isMaintenance method

**Comment by vladsf** [comment]
May I go all this path with PHP 7.2.33? Is PHP 7.1 required until 3.9.x?

**Comment by vladsf** [comment]
> But in the end still need to find release that added isMaintenance method
I have add "maintenance" => true in config/setup.php, but it only caused next error app.ERROR: Uncaught Exception TypeError: "Return value of Setup::getBaseUrl() must be of the type string, null returned"

**Comment by glensc** [comment]
this patch is causing you the issues:
- db/migrations/20190802211351_eventum_convert_const.php

after the migration has been applied, the new code starts to work, so find what version added the migration.

**Comment by vladsf** [comment]
Got to 3.9.0. It is not really clear what is the right namespace for `config/custom_field/*.php` files?
```
include_once(APP_INC_PATH . "/custom_field/class.dynamic.php");
include_once(APP_INC_PATH . "/class.custom_field.php");
```

**Comment by glensc** [comment]
The classes are in root namespace. In fact this is documented in upgrade documentation:
- https://github.com/eventum/eventum/blob/v3.9.0/docs/wiki/Upgrading.md

> 
> -   Modify your workflow/customer classes not to require any Eventum core classes, they are autoloaded now. So you can just remove such lines:
> 
> ```php
> require_once(APP_INC_PATH."workflow/class.abstract_workflow_backend.php");
> require_once(APP_INC_PATH."customer/class.abstract_customer_backend.php");
> ```

the instruction to remove those require calls has been there since eventum 2.2 upgrade!

**Comment by glensc** [comment]
the conver const patch was added to 3.8.0:
- https://github.com/eventum/eventum/issues/941#issuecomment-694890627

so, perhaps say in docs that before updating to 3.9, need to update to 3.8.0 first:

```
## Upgrading from versions before 3.9.0

You need to upgrade to 3.8.0 first before you can upgrade to versions 3.9.x and above

```

altho I find the sentence very confusing, how to explain to the user that the best way to upgrade is via minor versions:
- https://github.com/eventum/eventum/issues/941#issuecomment-694871752

**Comment by vladsf** [comment]
> the instruction to remove those require calls has been there since eventum 2.2 upgrade!
yeah, I fixed that while upgrading to 3.5.5. Yet config/custom_field/*.php files did not produce any warnings on bin/upgrade.php until 3.9.0. It started only on 3.9.0

**Comment by vladsf** [comment]
> altho I find the sentence very confusing, how to explain to the user that the best way to upgrade is via minor versions:
"Eventum supports sequential upgrade path using released minor versions e.g. `3.x.x -> 3.(x+1).0 -> 3.(x+2).0 ..` "

**Comment by vladsf** [comment]
My server wide authentication provides the username using the REMOTE_USER environment variable. This variable (login) can be trusted by Eventum since the authentication happened before the request reached it.

Earlier in 3.5.5 I used slightly modified `LoginController.php` to set  `$this->login`. Can't grep it now. It seems Authetication has been drastically changed.

**Comment by vladsf** [comment]
I guess `src/Auth/Adapter/CasAdapter.php` fits the best for my case.

**Comment by vladsf** [comment]
Modified CasAdapter.php worked for my case with preset REMOTE_USER. It might make sense to contribute my code to examples.

**Comment by glensc** [comment]
Yes. please do that. I've never used it, so don't know how it works. it's @balsdorf's contribution.

**Comment by glensc** [comment]
Updating the doc matrix: https://github.com/eventum/eventum/pull/960
