### ISSUE TITLE
3.9.5 'quick search' form layout problem on list.php

### ISSUE THREAD

**Issue by vladsf** [eventum/eventum#942]
**Version(s) affected**: 3.9.5

**PHP Version**: 7.2.33

**Browser and Version**: Firefox 68, Firefox 80

**Description**
Search form layout on list.php looks broken:  
![image](https://user-images.githubusercontent.com/4058524/93767076-1fbf3880-fc20-11ea-892c-f906114608d1.png)
I tried Firefox 68 Linux, Firefox 80 Windows. The same result.

**Comment by vladsf** [comment]
nope, the patch has no effect for my issue.

**Comment by glensc** [comment]
yes, seems you did not follow the discussion. you should have ended up here:
- https://github.com/eventum/eventum/pull/943#issuecomment-696322453

just patching does nothing, you need to compile assets. see contributing doc.

**Comment by vladsf** [comment]
My bug was introduced with this change -
https://github.com/eventum/eventum/commit/d9249a37836d57cfeb93c0cf288ca0f1056647ac#diff-2432c025b7b9d37b8d66d94d00fac971

Is it possible to revert?
