### ISSUE TITLE
Eventum Migration

### ISSUE THREAD

**Issue by Championface** [eventum/eventum#944]
Apologies if this is covered elsewhere, but I can't seem to find information on this. Is there any documentation on how to migrate Eventum to a new host/server? We're looking at moving an existing instance to a new CentOS 8 host. Is it as simple as installing on the new host, and restoring the database?

Thanks

**Comment by glensc** [comment]
you should also transfer:
- config/*
- var/storage/*

**Comment by vladsf** [comment]
https://github.com/eventum/eventum/blob/master/docs/wiki/Upgrading.md

**Comment by glensc** [comment]
@vladsf 


🚧 Never link to branches, share a permalink 🚧
- see https://news.ycombinator.com/item?id=8046710
  and https://help.github.com/articles/getting-permanent-links-to-files/
  and https://docs.gitlab.com/ee/user/shortcuts.html#project-files
- hit `y`
- and perhaps for https://github.com/josephfrazier/octopermalinker (GitHub)

NOTE: edit your post and fix it with a permalink!

**Comment by vladsf** [comment]
OK, thank you. The link has been fixed.
