### ISSUE TITLE
Upgrading from 2.2.0 to 3.0.1 CSS Issue

### ISSUE THREAD

**Issue by jvan1997** [eventum/eventum#945]
**Version(s) affected**: 2.2.0 to 3.0.1

**PHP Version**: 5.3.13

**Browser and Version**: Google Chrome (Latest Version)

**Description**  
From the looks of it, the CSS is not loading for 3.0.1 for my end. All I did was download and extract the tar.gz file since I was upgrading from 2.2, therefore I should go to 3.0.1. After that, I copied the contents of the old_eventum/config director to the eventum/config directory. Upon loading the page, it showed no css. I also upgraded the database i had using php upgrade/upgrade-database.php. Any advice/guidance would be appreciated, thank you.

**How to reproduce**  

I'm not really sure how this is reproduceable, since all I did was copy the contents of my config folder to the newer version. 

**Possible Solution**  

**Additional context**  

![image](https://user-images.githubusercontent.com/32347479/94326765-308ee780-ff5b-11ea-95fb-0710a3510265.png)

**Comment by glensc** [comment]
the last version is 3.9.5, upgrade!

you need to open your browser console and see what URLs it requests, and where you content really is.

**Comment by vladsf** [comment]
I guess css directory moved in 3.x version. Do step by step (byt miro version) upgrade to 3.5.6. It is possible.

**Comment by glensc** [comment]
each version on its own should work. this bug report doesn't indicate they mix or customize themselves.

**Comment by glensc** [comment]
looks like last version with php 5.3 support is 3.1.0

**Comment by jvan1997** [comment]
Figured it out. You were right in that the content was in the wrong location. So thank you for that.
