### ISSUE TITLE
How to replace APP_SYSTEM_USER_ID?

### ISSUE THREAD

**Issue by vladsf** [eventum/eventum#948]
**Version(s) affected**: 3.9.6

**PHP Version**: 7.2.34
Hi,

I used following line of code in /config/workflow/* in 3.5.5 version. It fails now. APP_ globals gone if I read correctly.
Notification::subscribeEmail(APP_SYSTEM_USER_ID, $issue_id, $email, Notification::getDefaultActions());

Please suggest on how to replace APP_SYSTEM_USER_ID?

**Comment by glensc** [comment]
changelog entries:

- Migrate `SPHINX_` constants to setup.php, #705
- Get rid of global constants (moved to `setup.php`) (@glensc, #629, #642)

replacement is `Setup::getSystemUserId()`, for the rest of the constants use setup config keys.

**Comment by vladsf** [comment]
Thank you I got it back to work!
Though I can not say APP_ constants is worse than Setup::get()['aaa']['bbb'] call;

**Comment by glensc** [comment]
you can read the reasons from the PR themselves. commonly used values have method in Setup class.

also, you can close yourself your own created issues.
