### ISSUE TITLE
Argument "eventName" not found

### ISSUE THREAD

**Issue by vladsf** [eventum/eventum#949]
**Version(s) affected**: 3.9.6

**PHP Version**: 7.2.34

**Description**  
Workflow extensions cause errors while following docs/examples/workflow/class.example.php

```
app.ERROR: Argument "eventName" not found. {"account":"localhost [tickets@example.com]/MBOX_REQ","resource":"[object] (Eventum\\Mail\\Imap\\ImapResource: #1 <87dfa5f0-aa50-4780-bebb-16e946244010@default>)","class":"InvalidArgumentException","e":"[object] (InvalidArgumentException(code: 0): Argument \"eventName\" not found. at /intranet/eventum-3.9.6/vendor/symfony/event-dispatcher/GenericEvent.php:63)
[stacktrace]
```

My workflow extension worked OK in 3.5.5. Now in 3.9.6 they all fail on mail downloading, i.e. during issue creation.
I guess docs/examples/workflow/class.example.php is not correct anymore.

Even such a simple workflow extension fails:
```
class Git_Requests_Workflow_Backend extends Abstract_Workflow_Backend
{
    /**
     * This allows anyone to reply to an issue without first being added to the Authorized Repliers list, 
     * so they won't get blocked.
     */
    function canEmailIssue($prj_id, $issue_id, $email)
    {
        return true;
    }
}
```

**Comment by glensc** [comment]
please use markdown code fence when pasting logs!

**Comment by vladsf** [comment]
OK, I followed the bug submitting form.

**Comment by glensc** [comment]
many errors

1. docs/examples/workflow/class.example.php does not have such a method that you pasted here, so technically should close this issue with WONTFIX.
2. can not find any such errors in canEmailIssue and SystemEvents::ACCESS_ISSUE_EMAIL usage

however:
1. getAdditionalEmailAddresses uses $event['eventName'] and it's not filled correctly:
- https://github.com/eventum/eventum/blob/v3.9.6/lib/eventum/class.workflow.php#L492

submitting fix for that:
- https://github.com/eventum/eventum/pull/950

consider fixing issue details

**Comment by vladsf** [comment]
Thank you, this patch eliminated the error.
Let me test more with a longer workflow file.

**Comment by vladsf** [comment]
Curious if I can "allow anyone to reply to an issue without first being added to the Authorized Repliers list" in a setup.php without
writing a custom workflow?

**Comment by glensc** [comment]
Don't know answer to that. You may need to trace code to see if possible.
