### ISSUE TITLE
Move "hide closed issues" checkbox to the top

### ISSUE THREAD

**Issue by vladsf** [eventum/eventum#951]
**Description**  

![hci](https://user-images.githubusercontent.com/4058524/95207245-54221f80-07f0-11eb-9edc-7d07e1d2f3bb.png)
Hi, 

Would you accept a patch which moves "Hide closed issues" checkbox to the top? The way it looks on the picture attached.

**Comment by glensc** [comment]
sure, seems non-intrusive. but don't move, add it as additional checkbox.

**Comment by vladsf** [comment]
Adding this as a second checkbox makes JS code less elegant. Need to google for a better js/css solution.

**Comment by vladsf** [comment]
My patch is not good enough so I close it until I find an optimal way.
