### ISSUE TITLE
validateForm() fails to validate on "Send Mail" button

### ISSUE THREAD

**Issue by vladsf** [eventum/eventum#953]
**Version(s) affected**: 3.9.6

**PHP Version**: 7.2.34

**Browser and Version**: Mozilla for Linux 68.12.0esr (64-bit)

**Description**  
Eventum allows to send empty emails from the web interface.

**How to reproduce**  
Open any issue. Click "Send mail" btn at the bottom. Click "Send mail" in the pop-up window. Click "OK".
Eventum sends empty email despite the warning.

**Possible Solution**  
Browsed through the code. Can't find the issue.

**Comment by glensc** [comment]
To debug the javascript code:
2. run `yarn` to install node modules
1. add `debugger;` anywhere in the code to create breakpoint
2. run `yarn dev` or `yarn watch` to compile js changes
3. open browser debugger console
3. perform some actions
4. code will be stopped at breakpoint you set

**Comment by glensc** [comment]
I noticed there are two send buttons when I click "send email" button on the issue page

![image](https://user-images.githubusercontent.com/199095/95833498-6518e680-0d44-11eb-8378-568b3a3d3854.png)

**Comment by glensc** [comment]
Created fix to the reported problem: https://github.com/eventum/eventum/pull/954

**Comment by vladsf** [comment]
Thank you, the fix solved the trouble.
