### ISSUE TITLE
Eventum keeps saying "Please select a valid date of work"

### ISSUE THREAD

**Issue by eventumrcf** [eventum/eventum#963]
**Version(s) affected**: 3.9.6
**PHP Version**: 7.3
**Browser and Version**: Chrome 86.0.4240.111
**Description**  

Hi I upgraded to the latest version, but now am experiencing issues:

1) Whenever I try to add a time tracking entry I get the message "Please select a valid date of work" (SOLVED)

2) When downloading e-mail I get 

app.ERROR: Eventum\Model\Repository\IssueRepository 0 not found

Any insights would be appreciated.
Ruan

**Comment by eventumrcf** [comment]
Hi managed to sort it out

**Comment by glensc** [comment]
Please explain how for future readers.

**Comment by martin-dufka** [comment]
How it was "solved"? I have the same error "Please select a valid date of work" in 3.9.9 after update.
