### ISSUE TITLE
Routing error

### ISSUE THREAD

**Issue by eventumrcf** [eventum/eventum#967]
Using latest version of Eventum, when I go to logout, I get Oops 404 error. Also, when clicking on a link from an email without logging in first. How do I enable debug mode so I can see what the actual file is that it is looking for? Symfony is intercepting everything, apache logs show nothing, neither does the php logs or the eventum error log. I also added ini_set("display_errors", 1); error_reporting(E_ALL); but to no avail. My logs are all writable and nothing shows up in enventum's error log?

Some more info: I also had a legacy routes.yml from a previous upgrade under config/ but I removed that too (I read that in another post) but to no avail. 

Any help would be appreciated!

**Comment by eventumrcf** [comment]
Figured it out, had to remove 

UrlMatcher.*
and UrlGenerator.* from cache

Hope this helps someone else.

Regards
Ruan

**Comment by glensc** [comment]
Please use issue template. in other words, fix formatting and include version information.

You can see copy of issue template here (click on raw top copy contents):
- https://github.com/eventum/eventum/blob/v3.9.7/.github/ISSUE_TEMPLATE/1_Bug_report.md
