### ISSUE TITLE
Sticky drop-down in notification.php

### ISSUE THREAD

**Issue by vladsf** [eventum/eventum#972]
**Version(s) affected**: 3.9.5

**PHP Version**: 7.1.xx

**Browser and Version**: Firefox 78.4.1 Linux and Windows

Hi,
 
_How to repeat:_
Open "Edit Notification List" on a issue page, a pop-up window with a user selection tool appears.
Then try to select/search a user in the drop-down, the list appears and never goes away.
It keeps sticky covering other options.

![Screenshot from 2020-11-30 10-59-26](https://user-images.githubusercontent.com/4058524/100584662-72daf900-32fd-11eb-9f9a-30bd04d5ae2a.png)

A workaround is to type something like "abcdeefg" to reduce the drop-down. 
[Chosen samples](https://harvesthq.github.io/chosen/ ) works OK for me, so I guess this is a side effect of some Eventum CSS changes.

Can you confirm this bug in the latest 3.9.8? 

Thanks, Vlad.

**Comment by glensc** [comment]
I'm not able to reproduce this not in the latest code (3.9.8), nor in 3.9.6.

are you sure you are using javascript from the release tarball? 

if you are deploying from source, you may need to run asset compilation:
- https://github.com/eventum/eventum/blob/v3.9.8/CONTRIBUTING.md#development

**Comment by vladsf** [comment]
Ok, thank you. I will look into with a debugger.
I always use release tarballs, using standard method - untar, copy config/ into, upgrade. 
Never deployed from sources so far.

**Comment by vladsf** [comment]
Tried 3.9.6, then upgraded to 3.9.8 - the same issue, then ran out of ideas. No JS or networks rlated errors. 
Just unrelated things like 
`Cookie “eventum” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite view.php`

I will continue tomorrow.

**Comment by glensc** [comment]
It doesn't seem to be an error, but rather CSS not pure. I guess inspector could give some ideas.

**Comment by vladsf** [comment]
Partly located the issue, Eventum looks OK in OSX Safari and Opera Linux browsers, but not in Firefox (Linux).
