### ISSUE TITLE
BUG: Ldap config - 'encryption' option not being used. Fix suggested/hotfixed on hosted instance.

### ISSUE THREAD

**Issue by areis422** [eventum/eventum#985]
in src/Auth/Ldap/LdapConnection.php
in function getConnectionConfig()
the encryption parameter from needs to also be returned:

    private function getConnectionConfig()
    {
        return [
            'host' => $this->config['host'],
            'port' => $this->config['port'],
            'encryption' => $this->config['encryption'],
        ];
    }

DOES NOT work without the extra return:
error in apache log:
AH01071: Got error 'PHP message: auth.CRITICAL: Can't contact LDAP server {"e
xception":"[object] (Symfony\\\\Component\\\\Ldap\\\\Exception\\\\ConnectionException(code: 0):
 Can't contact LDAP server at /var/www/eventum-3.8.6/vendor/symfony/ldap/Adapter/ExtLdap/Connec
tion.php:53)\n[stacktrace]\n#0 /var/www/eventum-3.8.6/src/Auth/Ldap/LdapConnection.php(113): Sy
mfony\\\\Component\\\\Ldap\\\\Adapter\\\\ExtLdap\\\\Connection->bind('CN=WI Backup,OU...', 'bac
kup$')\n#1 /var/www/eventum-3.8.6/src/Auth/Ldap/LdapConnection.php(126): Eventum\\\\Auth\\\\Lda
p\\\\LdapConnection->connect()\n

in setup.php:
       'host' => 'server.domain.tld',
        'port' => '636',
        'encryption' => 'ssl',
with the extra return line, connection succeeds and a verified TLS handshake occurs (verified with tcpdump/wireshark).

same goes for the following in setup.php:
       'host' => 'server.domain.tld',
        'port' => '389',
        'encryption' => 'tls',
with the extra return line, connection succeeds and a verified STARTTLS is issued (verified with tcpdump/wireshark).

and of course, setting encryption to none with port = 389 works without issue. this came up due to our domain admins enforcing the sign and seal requirements for all ldap communications.

**Comment by areis422** [comment]
Can provide anonymized config file is required for reference, along with relevant auth logs.

**Comment by areis422** [comment]
Never mind, I see in later versions it's fixed.

**Comment by glensc** [comment]
By "fixed", You mean that encryption support was added in #797?
