### ISSUE TITLE
Error updating associated issues in update.php

### ISSUE THREAD

**Issue by plindry** [eventum/eventum#99]
In the new 3.0.6 there is an strange circunstance:
1. you create an issue without any state selected
2. You select the issue and update buttom
3. Fill the the associated issue field with the number of other associated issue. 
4. Then you open the other associated issue and then the number of the original issue is not shown but if you put a state or select a default state in the new issue this behavior doesn't occur and in the other associated issue this field is automatically updated .

It's not a logical situation creating issues wihtout an state and moreover associating with others but perhaps is designed in this way because is not a logical situation.

**Comment by glensc** [comment]
By `state` you mean `Status` field? how you create issue without `Status`? any screenshot to explain this better?

**Comment by plindry** [comment]
Yes glensc, status

**Comment by plindry** [comment]
Glensc close this issue i tried with a fresh installation 3.0.11 and i can't reproduce the error.

Thanks

**Comment by glensc** [comment]
if you are reporter, you can close your reported tickets yourself
